import { Link, useRouterState } from "@tanstack/react-router";
import { Check, CircleDollarSign, Clock, FileCheck2, FileSignature, ShieldCheck, UserRound } from "lucide-react";
import { CompactMetrics, InfoGrid, SimpleTable, Timeline } from "@/components/sales/sales-ui";
import { DashboardCard, ProgressBar, StatusBadge } from "@/components/ui/crm";
import { eligibilityChecks, type ResaleCase, type ResaleStatus } from "./resale-data";

export function RegistrationNavigation(){const pathname=useRouterState({select:s=>s.location.pathname});const items=[{label:"Oqood",to:"/registration" as const,active:pathname==="/registration"||pathname==="/registration/"||pathname.startsWith("/registration/cases")||pathname.startsWith("/registration/reports")},{label:"Resale / NOC",to:"/registration/resale" as const,active:pathname.startsWith("/registration/resale")||pathname.startsWith("/registration/noc")},{label:"Assignments",to:"/registration/assignments" as const,active:pathname.startsWith("/registration/assignments")}];return <nav aria-label="Registration areas" className="mb-5 flex gap-1 overflow-x-auto border-b border-border">{items.map(item=><Link key={item.label} to={item.to} className={`shrink-0 border-b-2 px-3 pb-2 text-[13px] font-semibold ${item.active?"border-primary text-primary":"border-transparent text-muted-foreground hover:text-foreground"}`}>{item.label}</Link>)}</nav>}
export function ResaleStatusBadge({status}:{status:ResaleStatus|string}){const tone=status==="Completed"||status==="Executed"||status.includes("Cleared")?"success":status==="On Hold"||status==="Rejected"||status==="Cancelled"?"danger":status.includes("Pending")||status.includes("Review")||status==="Finance Clearance"?"warning":"info";return <StatusBadge tone={tone}>{status}</StatusBadge>}
export function ResaleSummary({record:r}:{record:ResaleCase}){return <CompactMetrics items={[{label:"Case status",value:r.status,detail:r.updated,icon:<FileCheck2/>},{label:"Finance clearance",value:r.financeClearance,detail:r.paymentAccount,icon:<CircleDollarSign/>},{label:"NOC",value:r.nocId,detail:"Approval workflow",icon:<ShieldCheck/>},{label:"Assignment",value:r.assignmentId,detail:"Version 2",icon:<FileSignature/>},{label:"Case owner",value:r.owner,detail:r.targetDate,icon:<UserRound/>}]}/>} 
export function ProcessTracker({status}:{status:ResaleStatus}){const stages=["Request","Eligibility","Finance","NOC","Agreement","Signatures","Transfer"];const map:Record<string,number>={"Eligibility Review":1,"Finance Clearance":2,"NOC Approval":3,"Assignment Draft":4,"Awaiting Signatures":5,"Transfer In Progress":6,"Completed":7,"On Hold":2,"Rejected":1,"Cancelled":0};const current=map[status]??0;return <DashboardCard className="p-4"><div className="flex min-w-[680px] items-center overflow-x-auto pb-1">{stages.map((stage,index)=><div key={stage} className="contents"><div className="flex shrink-0 flex-col items-center gap-1"><span className={`grid size-7 place-items-center rounded-full border text-[10px] ${index<current?"border-success bg-success-soft text-success":index===current?"border-primary bg-primary text-primary-foreground":"border-border bg-surface text-muted-foreground"}`}>{index<current?<Check size={13}/>:index+1}</span><span className="text-[10px] text-muted-foreground">{stage}</span></div>{index<stages.length-1&&<span className={`mb-4 h-px min-w-8 flex-1 ${index<current?"bg-success":"bg-border"}`}/>}</div>)}</div></DashboardCard>}
export function EligibilityPanel(){return <DashboardCard className="overflow-hidden"><div className="p-4"><h2 className="text-lg font-bold">Eligibility checklist</h2><p className="text-xs text-muted-foreground">Checks use current linked CRM records and are preserved with each decision.</p></div><SimpleTable headers={["Check","Result","Evidence"]} rows={eligibilityChecks} badges={[1]}/></DashboardCard>}
export function TransferTimeline(){return <DashboardCard className="p-5"><h2 className="text-lg font-bold">Resale activity</h2><div className="mt-4"><Timeline items={[{icon:FileSignature,title:"Assignment version 2 approved",detail:"Legal Team · immutable version retained",time:"Today · 2:20 PM"},{icon:ShieldCheck,title:"NOC legal review approved",detail:"Management approval pending",time:"Today · 11:15 AM"},{icon:CircleDollarSign,title:"Finance clearance issued",detail:"FC-2026-00071",time:"Today · 9:30 AM"},{icon:Clock,title:"Resale request created",detail:"Omar Khan",time:"Today · 8:45 AM"}]}/></div></DashboardCard>}
export function FinanceSnapshot({record:r}:{record:ResaleCase}){return <DashboardCard className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-bold">Canonical finance clearance</h2><p className="text-xs text-muted-foreground">Amounts remain maintained in Payment 360.</p></div><ResaleStatusBadge status={r.financeClearance}/></div><div className="mt-4"><InfoGrid items={r.paymentAccount==="ACC-2026-00482"?[["Payment account",r.paymentAccount],["Total value","AED 1,225,000"],["Received","AED 420,000"],["Outstanding","AED 805,000"],["Overdue","AED 0"],["ERP status","Synced"]]:[["Payment account",r.paymentAccount],["Clearance",r.financeClearance],["Source","Payment 360"],["Review","Finance Team"]]}/></div><Link to="/payments/accounts/$accountId" params={{accountId:r.paymentAccount}} className="mt-4 inline-block text-sm font-semibold text-primary">Open Payment 360</Link></DashboardCard>}
export function Pipeline(){const items=[["Request",9,100],["Eligibility",6,67],["Finance",4,45],["NOC",5,56],["Agreement",3,34],["Signatures",3,34],["Transfer",2,23]] as const;return <DashboardCard className="p-5"><h2 className="text-lg font-bold">Resale pipeline</h2><div className="mt-5 space-y-3">{items.map(([label,count,value])=><div key={label}><div className="mb-1 flex justify-between text-xs"><span>{label}</span><strong>{count}</strong></div><ProgressBar value={value}/></div>)}</div></DashboardCard>}
