import { useState, type FormEvent, type ReactNode } from "react";
import { AlertTriangle, FileUp } from "lucide-react";
import { z } from "zod";
import { InfoGrid } from "@/components/sales/sales-ui";
import { Button, FieldError, FormField, Input, ModalShell, SelectMenu, Textarea } from "@/components/ui/crm";

type Props={open:boolean;onOpenChange:(open:boolean)=>void};
const remarks=z.string().trim().min(5,"Add at least 5 characters").max(500);
function Actions({close,label}:{close:()=>void;label:string}){return <div className="mt-5 flex justify-end gap-2"><Button type="button" variant="secondary" onClick={close}>Cancel</Button><Button type="submit">{label}</Button></div>}
function DecisionModal({open,onOpenChange,title,action,children}:{open:boolean;onOpenChange:(v:boolean)=>void;title:string;action:string;children:ReactNode}){const [error,setError]=useState("");function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const result=z.object({decision:z.string().min(1),remarks:z.string().max(500).optional()}).safeParse(data);if(!result.success){setError("Select a decision");return}const needsReason=result.data.decision!=="Approve"&&result.data.decision!=="Clear";if(needsReason&&!remarks.safeParse(result.data.remarks??"").success){setError("Remarks are required for this decision");return}setError("");onOpenChange(false)}return <ModalShell open={open} onOpenChange={onOpenChange} title={title}><form onSubmit={submit}>{children}<div className="mt-4 grid gap-4"><FormField label="Decision *"><select name="decision" defaultValue="" className="h-control rounded-md border border-input bg-surface px-3 text-sm"><option value="" disabled>Select decision</option><option>Approve</option><option>Clear</option><option>Return</option><option>Reject</option><option>On Hold</option></select></FormField><FormField label="Remarks"><Textarea name="remarks" maxLength={500}/><FieldError>{error}</FieldError></FormField></div><Actions close={()=>onOpenChange(false)} label={action}/></form></ModalShell>}
export function EligibilityDecisionModal(props:Props){return <DecisionModal {...props} title="Record eligibility decision" action="Save decision"><InfoGrid columns="sm:grid-cols-2" items={[["Property","Horizon Residences · A-1204"],["SPA","Executed"],["Registration","Linked"],["Finance","Current snapshot"]]}/></DecisionModal>}
export function FinanceDecisionModal(props:Props){return <DecisionModal {...props} title="Finance clearance review" action="Record finance decision"><div className="rounded-md bg-info-soft p-3 text-xs text-info">This decision references Payment Account ACC-2026-00482; it does not change finance balances.</div></DecisionModal>}
export function NocDecisionModal(props:Props){return <DecisionModal {...props} title="NOC approval decision" action="Record approval"><p className="text-xs text-muted-foreground">Finance, Legal and Management decisions remain separate and traceable.</p></DecisionModal>}
export function ShareDocumentModal({open,onOpenChange,type="NOC"}:Props&{type?:string}){const [error,setError]=useState("");function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const result=z.object({recipient:z.string().trim().min(2).max(120),email:z.string().trim().email().max(255),message:z.string().max(500).optional()}).safeParse(data);if(!result.success){setError("Enter a valid recipient and email address");return}setError("");onOpenChange(false)}return <ModalShell open={open} onOpenChange={onOpenChange} title={`Share ${type}`}><form onSubmit={submit}><div className="grid gap-4"><FormField label="Recipient *"><Input name="recipient" defaultValue="Sarah Ahmed" maxLength={120}/></FormField><FormField label="Email *"><Input name="email" type="email" defaultValue="sarah.ahmed@email.com" maxLength={255}/></FormField><FormField label="Message"><Textarea name="message" maxLength={500}/><FieldError>{error}</FieldError></FormField></div><p className="mt-3 text-xs text-muted-foreground">Delivery and signature status are represented in this workspace; live delivery requires an integration.</p><Actions close={()=>onOpenChange(false)} label={`Share ${type}`}/></form></ModalShell>}
export function GenerateDocumentModal({open,onOpenChange,type="NOC"}:Props&{type?:string}){return <ModalShell open={open} onOpenChange={onOpenChange} title={`Generate ${type}`}><InfoGrid columns="sm:grid-cols-2" items={[["Approved template","Current configured template"],["Case","RSL-2026-00042"],["Version","New immutable version"],["Linked records","Refreshed now"]]}/><div className="mt-4 rounded-md bg-success-soft p-3 text-xs text-success">Current linked data passed validation.</div><div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={()=>onOpenChange(false)}>Cancel</Button><Button onClick={()=>onOpenChange(false)}>Generate document</Button></div></ModalShell>}
export function FeeAdjustmentModal(props:Props){return <DecisionModal {...props} title="Request fee adjustment or waiver" action="Submit request"><div className="grid gap-4"><FormField label="Fee"><SelectMenu label="Assignment processing fee" items={["NOC administration fee","Assignment processing fee"]}/></FormField><FormField label="Requested amount"><Input name="amount" inputMode="decimal" defaultValue="0"/></FormField></div></DecisionModal>}
export function HoldTransferModal({open,onOpenChange}:Props){const [error,setError]=useState("");function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const result=z.object({reason:z.string().min(1),owner:z.string().trim().min(2).max(120),date:z.string().min(1),remarks,next:z.string().trim().min(3).max(250)}).safeParse(data);if(!result.success){setError("Reason, owner, date, remarks and next action are required");return}onOpenChange(false)}return <ModalShell open={open} onOpenChange={onOpenChange} title="Place transfer on hold"><form onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2"><FormField label="Reason *"><select name="reason" className="h-control rounded-md border border-input bg-surface px-3 text-sm"><option>Document clarification</option><option>Finance review</option><option>Signature issue</option><option>Linked data changed</option><option>Other</option></select></FormField><FormField label="Date *"><Input name="date" type="date" defaultValue="2026-09-24"/></FormField><FormField label="Responsible owner *"><Input name="owner" defaultValue="Mariam Saleh" maxLength={120}/></FormField><FormField label="Next action *"><Input name="next" defaultValue="Resolve issue and refresh linked records" maxLength={250}/></FormField><div className="sm:col-span-2"><FormField label="Remarks *"><Textarea name="remarks" maxLength={500}/><FieldError>{error}</FieldError></FormField></div></div><Actions close={()=>onOpenChange(false)} label="Place on hold"/></form></ModalShell>}
export function EndCaseModal({open,onOpenChange,mode}:Props&{mode:"Cancel"|"Reject"}){const [error,setError]=useState("");function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const value=String(new FormData(e.currentTarget).get("remarks")??"");if(!remarks.safeParse(value).success){setError(`${mode} reason is required`);return}onOpenChange(false)}return <ModalShell open={open} onOpenChange={onOpenChange} title={`${mode} resale request`}><form onSubmit={submit}><div className="flex gap-2 rounded-md bg-warning-soft p-3 text-xs text-warning"><AlertTriangle size={15}/>The case remains visible with its documents, decisions, and audit history.</div><div className="mt-4"><FormField label={`${mode} reason *`}><Textarea name="remarks" maxLength={500}/><FieldError>{error}</FieldError></FormField></div><Actions close={()=>onOpenChange(false)} label={mode}/></form></ModalShell>}
export function CompleteTransferModal({open,onOpenChange}:Props){return <ModalShell open={open} onOpenChange={onOpenChange} title="Complete ownership transfer"><div className="grid gap-2">{["Eligibility approved","Finance clearance valid","NOC approved","Required documents complete","Assignment executed","Required fees satisfied"].map(item=><div key={item} className="flex items-center gap-2 rounded-md bg-success-soft p-3 text-xs text-success"><span>✓</span>{item}</div>)}</div><div className="mt-4"><InfoGrid columns="sm:grid-cols-2" items={[["Outgoing owners","Sarah Ahmed · Omar Ahmed"],["Incoming owner","Yousef Al Mansoori"],["Unit","Horizon Residences · A-1204"],["Effective date","24 Sep 2026"]]}/></div><p className="mt-3 text-xs text-muted-foreground">Completion retains the prior owners in immutable ownership history.</p><div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={()=>onOpenChange(false)}>Back</Button><Button onClick={()=>onOpenChange(false)}>Confirm transfer</Button></div></ModalShell>}
export function UploadSupportingDocument({open,onOpenChange}:Props){return <ModalShell open={open} onOpenChange={onOpenChange} title="Upload supporting document"><label className="flex h-24 cursor-pointer items-center justify-center gap-2 rounded-md border border-dashed border-border text-xs"><FileUp size={16}/>Choose document<input className="sr-only" type="file"/></label><div className="mt-4"><FormField label="Configurable category"><SelectMenu label="Supporting document" items={["Supporting document","Customer document","Fee receipt","Eligibility evidence"]}/></FormField></div><div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={()=>onOpenChange(false)}>Cancel</Button><Button onClick={()=>onOpenChange(false)}>Upload</Button></div></ModalShell>}
