import { Link, useRouterState } from "@tanstack/react-router";
import { AlertTriangle, Building2, CircleDollarSign, Clock, Grid3X3, History, LockKeyhole, type LucideIcon } from "lucide-react";
import { useSyncExternalStore, type ReactNode } from "react";
import { CompactMetrics, InfoGrid, SimpleTable, Timeline, toneFor } from "@/components/brokers/broker-ui";
import { Button, DashboardCard, StatusBadge } from "@/components/ui/crm";
import { formatAed, getInventoryServerUnits, getInventoryUnits, subscribeInventory, type InventoryStatus, type InventoryUnit } from "./inventory-data";

export { CompactMetrics, InfoGrid, SimpleTable, Timeline, toneFor };

const links=[
  {label:"Projects",to:"/projects" as const},
  {label:"Units",to:"/projects/units" as const},
  {label:"Availability",to:"/projects/availability" as const},
  {label:"Pricing",to:"/projects/pricing" as const},
  {label:"Reports",to:"/projects/reports" as const},
];
export function ProjectsNavigation(){const path=useRouterState({select:s=>s.location.pathname});return <div className="mt-5 flex gap-6 overflow-x-auto border-b border-border">{links.map(item=><Link key={item.label} to={item.to} activeOptions={{exact:item.to==="/projects"}} className={`-mb-px shrink-0 border-b-2 pb-2 text-[13px] font-medium ${path===item.to||path.startsWith(`${item.to}/`)?"border-primary text-primary":"border-transparent text-muted-foreground"}`}>{item.label}</Link>)}</div>}
export function useInventory(){return useSyncExternalStore(subscribeInventory,getInventoryUnits,getInventoryServerUnits)}

export function InventoryStatusBadge({status}:{status:InventoryStatus}){const tone=status==="Available"?"success":status==="Reserved"?"info":status==="On Hold"?"warning":status==="Blocked"?"danger":"neutral";return <StatusBadge tone={tone}>{status}</StatusBadge>}
export function InventoryDistributionBar({compact=false}:{compact?:boolean}){return <div><div className={`flex overflow-hidden rounded-full ${compact?"h-2":"h-4"}`}><span className="bg-mint" style={{width:"37.5%"}}/><span className="bg-info" style={{width:"13.3%"}}/><span className="bg-primary" style={{width:"44.2%"}}/><span className="bg-warning-soft" style={{width:"5%"}}/></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs sm:grid-cols-4"><Legend color="bg-mint" label="Available" value="180"/><Legend color="bg-info" label="Reserved" value="64"/><Legend color="bg-primary" label="Sold" value="212"/><Legend color="bg-warning-soft" label="On hold" value="24"/></div></div>}
function Legend({color,label,value}:{color:string;label:string;value:string}){return <div className="flex items-center gap-2"><i className={`size-2 rounded-full ${color}`}/><span className="text-muted-foreground">{label}</span><strong className="ml-auto">{value}</strong></div>}

export function FloorSelector({projectId,buildingId,current=12,floors=20}:{projectId:string;buildingId:string;current?:number;floors?:number}){return <nav aria-label="Select floor" className="flex max-h-[360px] gap-2 overflow-auto xl:flex-col">{Array.from({length:floors},(_,i)=>floors-i).map(floor=><Link key={floor} to="/projects/$projectId/buildings/$buildingId/floors/$floorNumber" params={{projectId,buildingId,floorNumber:String(floor)}} className={`flex h-9 shrink-0 items-center justify-between rounded-md px-3 text-xs font-medium ${floor===current?"bg-primary text-primary-foreground":"border border-border bg-surface hover:bg-muted"}`}><span>Floor {floor}</span>{floor===current&&<span className="ml-4">8 units</span>}</Link>)}</nav>}
export function UnitCard({unit}:{unit:InventoryUnit}){return <Link to="/projects/units/$unitId" params={{unitId:unit.id}} className="block rounded-card border border-border bg-surface p-3 hover:border-primary"><div className="flex items-center justify-between gap-2"><strong>{unit.number}</strong><InventoryStatusBadge status={unit.status}/></div><p className="mt-2 text-xs text-muted-foreground">{unit.subtype}</p><p className="mt-1 text-sm font-semibold">{formatAed(unit.approvedPrice)}</p></Link>}
export function InventoryMatrix({units}:{units:InventoryUnit[]}){const floors=[...new Set(units.map(unit=>unit.floor))].sort((a,b)=>b-a);return <div className="overflow-x-auto"><div className="min-w-[720px] space-y-2">{floors.map(floor=><div key={floor} className="grid grid-cols-[90px_repeat(4,minmax(125px,1fr))] gap-2"><strong className="flex items-center text-xs">Floor {floor}</strong>{units.filter(unit=>unit.floor===floor).slice(0,4).map(unit=><UnitCard key={unit.id} unit={unit}/>)}</div>)}</div></div>}
export function UnitSummary({unit}:{unit:InventoryUnit}){return <CompactMetrics items={[{label:"Approved price",value:formatAed(unit.approvedPrice),detail:"Inventory master price",icon:<CircleDollarSign/>},{label:"Size",value:`${unit.size.toLocaleString()} sq ft`,detail:`${unit.subtype} · ${unit.bathrooms} bathrooms`,icon:<Grid3X3/>},{label:"Payment plan",value:"20 / 40 / 40",detail:unit.paymentPlan,icon:<Clock/>},{label:"Availability",value:unit.status,detail:unit.lastUpdated,icon:<Building2/>}]}/>} 
export function PaymentPlanSummary({price=1250000}:{price?:number}){const stages:[[string,number,string],[string,number,string],[string,number,string]]=[["Booking",20,"Reservation"],["During construction",40,"Construction milestones"],["Handover",40,"Handover notice"]];return <DashboardCard className="overflow-hidden"><div className="p-4"><div className="flex flex-wrap items-center gap-2"><div><h2 className="text-lg font-bold">Standard 20 / 40 / 40</h2><p className="text-xs text-muted-foreground">Linked default plan · Unit price {formatAed(price)}</p></div><StatusBadge tone="success" className="ml-auto">Default plan</StatusBadge></div></div><SimpleTable headers={["Milestone","Percentage","Amount","Due trigger"]} rows={stages.map(([name,percent,trigger])=>[name,`${percent}%`,formatAed(price*percent/100),trigger])}/></DashboardCard>}
export function UnitConflictWarning({status="Reserved"}:{status?:InventoryStatus}){return <div role="alert" className="rounded-card border border-danger/20 bg-danger-soft p-4 text-danger"><div className="flex gap-3"><AlertTriangle className="shrink-0" size={18}/><div><strong className="text-xs uppercase">Unit no longer available</strong><p className="mt-1 text-sm">Unit A-1204 is currently {status.toLowerCase()} for another customer.</p><div className="mt-3 grid gap-2 text-xs sm:grid-cols-3"><span>Current status: <strong>{status}</strong></span><span>Reservation: <strong>RSV-2026-00182</strong></span><span>Since: <strong>24 Sep · 1:20 PM</strong></span></div></div></div></div>}
export function PermissionNotice({children}:{children:ReactNode}){return <div className="flex items-center gap-2 rounded-md bg-muted p-3 text-xs text-muted-foreground"><LockKeyhole size={14}/>{children}</div>}
export function ActivityPanel(){const items:{icon:LucideIcon;title:string;detail:string;time:string}[]=[{icon:Clock,title:"Approved price updated",detail:"AED 1.25M → AED 1.225M · September campaign",time:"24 Sep · 2:30 PM"},{icon:Building2,title:"Unit released",detail:"Customer hold expired · status Available",time:"23 Sep · 4:18 PM"},{icon:History,title:"Payment plan changed",detail:"Investor plan → Standard 20 / 40 / 40",time:"22 Sep · 11:10 AM"}];return <Timeline items={items}/>} 