import { useState } from "react";
import { AlertTriangle, Clock, FileUp } from "lucide-react";
import { Button, FormField, Input, ModalShell, SelectMenu, Textarea } from "@/components/ui/crm";
import { getUnit, updateUnitStatus, type InventoryStatus } from "./inventory-data";
import { InfoGrid, UnitConflictWarning } from "./projects-ui";

type OpenProps={open:boolean;onOpenChange:(open:boolean)=>void;unitId:string};
function Actions({close,primary,danger=false,onSubmit}:{close:()=>void;primary:string;danger?:boolean;onSubmit?:()=>void}){return <div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={close}>Cancel</Button><Button className={danger?"bg-danger hover:bg-danger/90":""} onClick={()=>{onSubmit?.();close()}}>{primary}</Button></div>}
export function HoldUnitModal({open,onOpenChange,unitId}:OpenProps){const unit=getUnit(unitId);const [type,setType]=useState("Customer hold");const conflict=unit.status==="Reserved"||unit.status==="Sold";return <ModalShell open={open} onOpenChange={onOpenChange} title="Hold unit"><InfoGrid columns="sm:grid-cols-2" items={[["Unit",unit.number],["Current status",unit.status],["Project",unit.project],["Approved price",`AED ${unit.approvedPrice.toLocaleString()}`]]}/>{conflict?<div className="mt-4"><UnitConflictWarning status={unit.status}/><div className="mt-4 flex justify-end gap-2"><Button variant="secondary" onClick={()=>onOpenChange(false)}>View unit</Button><Button onClick={()=>onOpenChange(false)}>Select another unit</Button></div></div>:<><div className="mt-4 grid gap-4 sm:grid-cols-2"><FormField label="Hold type *"><SelectMenu label={type} items={["Customer hold","Management hold","Internal block"]}/></FormField><FormField label="Lead / customer reference"><Input defaultValue="Sarah Ahmed · CU-2026-00482"/></FormField><FormField label="Hold duration"><SelectMenu label="24 hours" items={["4 hours","12 hours","24 hours","48 hours","Custom expiry"]}/></FormField><FormField label="Expiry date / time"><Input type="datetime-local" defaultValue="2026-09-25T17:00"/></FormField><FormField label="Salesperson"><Input defaultValue="Omar Khan"/></FormField><div className="sm:col-span-2"><FormField label="Hold reason *"><Textarea required defaultValue="Customer reviewing sales offer"/></FormField></div><div className="sm:col-span-2"><FormField label="Notes"><Textarea/></FormField></div></div><div className="mt-4 flex gap-2 rounded-md bg-warning-soft p-3 text-xs text-warning"><Clock size={15}/>Hold expires 25 Sep 2026 at 5:00 PM. Expiry will be preserved in history before release.</div><Actions close={()=>onOpenChange(false)} primary="Hold unit" onSubmit={()=>updateUnitStatus(unit.id,type==="Internal block"?"Blocked":"On Hold")}/></>}</ModalShell>}
export function ReleaseUnitModal({open,onOpenChange,unitId}:OpenProps){const unit=getUnit(unitId);return <ModalShell open={open} onOpenChange={onOpenChange} title="Release unit"><InfoGrid columns="sm:grid-cols-2" items={[["Unit",unit.number],["Current status",unit.status],["Held by","Omar Khan"],["Customer","Sarah Ahmed"]]}/><div className="mt-4"><FormField label="Reason for release *"><SelectMenu label="Select reason" items={["Customer withdrew","Hold expired","Management release","Duplicate allocation","Transaction cancelled","Other"]}/></FormField></div><div className="mt-4"><FormField label="Remarks"><Textarea/></FormField></div><div className="mt-4 flex gap-2 rounded-md bg-warning-soft p-3 text-xs text-warning"><AlertTriangle size={15}/>Releasing the unit returns it to Available and creates an immutable audit entry.</div><Actions close={()=>onOpenChange(false)} primary="Release unit" danger onSubmit={()=>updateUnitStatus(unit.id,"Available")}/></ModalShell>}
export function BlockUnitModal({open,onOpenChange,unitId}:OpenProps){const unit=getUnit(unitId);return <ModalShell open={open} onOpenChange={onOpenChange} title="Block unit"><InfoGrid columns="sm:grid-cols-2" items={[["Unit",unit.number],["Current status",unit.status]]}/><div className="mt-4 grid gap-4"><FormField label="Reason *"><SelectMenu label="Pricing review" items={["Legal issue","Management block","Technical issue","Pricing review","Internal use"]}/></FormField><FormField label="Internal remarks *"><Textarea required/></FormField></div><Actions close={()=>onOpenChange(false)} primary="Block unit" onSubmit={()=>updateUnitStatus(unit.id,"Blocked")}/></ModalShell>}
export function PriceUpdateModal({open,onOpenChange,unitId}:OpenProps){const unit=getUnit(unitId);return <ModalShell open={open} onOpenChange={onOpenChange} title="Update approved price"><InfoGrid columns="sm:grid-cols-2" items={[["Unit",unit.number],["Current approved price",`AED ${unit.approvedPrice.toLocaleString()}`]]}/><div className="mt-4 grid gap-4 sm:grid-cols-2"><FormField label="New price *"><Input required type="number" defaultValue={String(unit.approvedPrice)}/></FormField><FormField label="Effective date *"><Input required type="date" defaultValue="2026-09-24"/></FormField><FormField label="Approval reference"><Input placeholder="APR-2026-..."/></FormField><div className="sm:col-span-2"><FormField label="Reason *"><Textarea required placeholder="Business reason for the price change"/></FormField></div></div><p className="mt-4 text-xs text-muted-foreground">The current price remains in history. This action requires Management approval.</p><Actions close={()=>onOpenChange(false)} primary="Submit update"/></ModalShell>}
export function ImportPreviewModal({open,onOpenChange}:{open:boolean;onOpenChange:(open:boolean)=>void}){return <ModalShell open={open} onOpenChange={onOpenChange} title="Upload unit schedule"><label className="flex min-h-28 items-center justify-center gap-2 rounded-md border border-dashed border-border text-sm text-muted-foreground"><FileUp size={18}/>Choose CSV or Excel file<input type="file" accept=".csv,.xlsx,.xls" className="sr-only"/></label><p className="mt-3 text-xs text-muted-foreground">Expected: Project, Building, Floor, Unit number, Unit type, Bedrooms, Size, Base price, Approved price, Status, Payment plan.</p><Actions close={()=>onOpenChange(false)} primary="Validate file"/></ModalShell>}
export function ConcurrentChangeWarning(){return <div role="alert" className="rounded-card border border-warning/20 bg-warning-soft p-4 text-warning"><div className="flex gap-3"><AlertTriangle size={18}/><div><strong>Inventory status changed</strong><p className="mt-1 text-xs">This unit was updated by another user. Previous: Available · Current: On Hold. Refresh latest inventory before continuing.</p><Button variant="secondary" className="mt-3 h-9">Refresh inventory</Button></div></div></div>}