import {createFileRoute,Link} from "@tanstack/react-router";
import {AlertTriangle,CalendarCheck,CheckCircle2,Lock} from "lucide-react";
import {useState} from "react";
import {AppShell} from "@/components/app-shell";
import {closeTasks,periods} from "@/components/finance/accounting-data";
import {AuditPanel,Kpis,Panel,Placeholder,RecordTable,pageMeta} from "@/components/finance/accounting-ui";
import {ReasonModal} from "@/components/finance/accounting-workflows";
import {FinancePage} from "@/components/finance/finance-ui";
import {Button,ProgressBar,Tabs} from "@/components/ui/crm";
export const Route=createFileRoute("/finance/close/")({head:()=>pageMeta("Financial Close","Accounting periods, month-end checklist, period close and controlled reopen."),component:Page});
function Page(){const [tab,setTab]=useState("dashboard");const [rows,setRows]=useState(periods);const [tasks,setTasks]=useState(closeTasks);const [modal,setModal]=useState<{kind:"close"|"reopen";id:string}|null>(null);const [log,setLog]=useState<string[][]>([]);const [err,setErr]=useState("");
const done=tasks.filter(t=>t[5]==="Complete").length;
const tryClose=(id:string)=>{if(id==="FY2026-09"&&done<tasks.length){setErr(`Cannot close Sep 2026: ${tasks.length-done} checklist tasks are incomplete.`);return}setErr("");setModal({kind:"close",id})};
const apply=(kind:"close"|"reopen",id:string,reason:string)=>{setRows(r=>r.map(p=>p[0]===id?[p[0]??"",p[1]??"",p[2]??"",kind==="close"?"Closed":"Reopened",`Maya Joseph · just now`,p[5]??""]:p));setLog(l=>[["Just now","Maya Joseph",id,`${kind==="close"?"Period closed":"Period reopened"} — ${reason}`,kind==="close"?"Soft closed":"Closed",kind==="close"?"Closed":"Reopened"],...l])};
return <AppShell crumbs={["Workspace","Finance ERP","Financial close"]}><FinancePage eyebrow="FINANCIAL CLOSE" title="Financial close" description="Month and year-end close with checklist control and audited reopen.">
<div className="mt-3 rounded-md border border-border bg-surface p-3 text-xs">Borrowing costs: <strong>3 records pending review</strong> (AED 666K) · 0 approved journals unposted · <Link to="/finance/borrowing" className="font-semibold text-primary">Review borrowing costs</Link></div>
<div className="mt-5"><Kpis items={[["Current period","Sep 2026","Open · closes 05 Oct",<CalendarCheck/>],["Checklist progress",`${done} / ${tasks.length}`,`${Math.round(done/tasks.length*100)}% complete`,<CheckCircle2/>],["Blocked tasks",String(tasks.filter(t=>t[5]==="Blocked").length),"Trial balance review",<AlertTriangle/>],["Closed periods",String(rows.filter(r=>r[3]==="Closed").length),"FY2026",<Lock/>]]}/></div>
<div className="mt-4"><Tabs value={tab} onValueChange={setTab} items={[{value:"dashboard",label:"Close checklist"},{value:"periods",label:"Accounting periods"},{value:"audit",label:"Close audit"}]}/></div>
<div className="mt-4 space-y-4">{tab==="dashboard"&&<Panel flush title="Sep 2026 close checklist" subtitle="All tasks must be complete before the period can be closed" actions={<div className="w-40"><ProgressBar value={done/tasks.length*100}/></div>}><RecordTable headers={["Task","Module","Role","Owner","Due","Status","Action"]} badges={[5]} rows={tasks.map((t,i)=>[...t,t[5]!=="Complete"?<Button variant="secondary" className="h-7 px-2 text-[11px]" onClick={()=>setTasks(ts=>ts.map((x,j)=>j===i?[...x.slice(0,5),"Complete"]:x))}>Mark complete</Button>:"—"])}/></Panel>}
{tab==="periods"&&<><Placeholder title="Period controls">Closed periods reject new postings. Reopening requires the Finance Controller permission, a reason, and is recorded in the audit trail.</Placeholder>{err&&<p className="rounded-md bg-danger-soft p-3 text-xs font-medium text-danger">{err}</p>}<Panel flush title="Accounting periods — FY2026"><RecordTable headers={["Period","Name","Dates","Status","Closed by","Checklist","Action"]} badges={[3]} rows={rows.map(p=>[...p,p[3]==="Open"||p[3]==="Soft closed"||p[3]==="Reopened"?<Button variant="secondary" className="h-7 px-2 text-[11px]" onClick={()=>tryClose(p[0]??"")}>Close period</Button>:p[3]==="Closed"?<Button variant="ghost" className="h-7 px-2 text-[11px]" onClick={()=>setModal({kind:"reopen",id:p[0]??""})}>Reopen</Button>:"—"])}/></Panel></>}
{tab==="audit"&&<AuditPanel rows={[...log,["06 Sep · 6:10 PM","Maya Joseph","FY2026-08","Soft close","Open","Soft closed"],["08 Aug · 5:40 PM","Ahmed Malik","FY2026-07","Hard close","Soft closed","Closed"]]}/>}</div>
<ReasonModal open={!!modal} onOpenChange={o=>!o&&setModal(null)} title={modal?.kind==="reopen"?`Reopen ${modal.id}`:`Close ${modal?.id??""}`} label={modal?.kind==="reopen"?"Reopen period":"Close period"} note={modal?.kind==="reopen"?"Reopening allows postings again. Finance Controller approval is required.":"Closing locks the period against further postings."} onConfirm={r=>modal&&apply(modal.kind,modal.id,r)}/></FinancePage></AppShell>}
