import {createFileRoute,Link} from "@tanstack/react-router";
import {CircleDollarSign,Clock,TrendingUp,Wallet} from "lucide-react";
import {useState} from "react";
import {AppShell} from "@/components/app-shell";
import {JournalLines,Kpis,Panel,Placeholder,RecordTable,pageMeta} from "@/components/finance/accounting-ui";
import {FinancePage} from "@/components/finance/finance-ui";
import {A,eligibilityFor,policies,scheduleFor} from "@/components/finance/revenue-data";
import {AdjustmentModal,RevBadge,revStore} from "@/components/finance/revenue-ui";
import {Button,Tabs} from "@/components/ui/crm";

export const Route=createFileRoute("/finance/revenue/$revenueId")({head:({params})=>pageMeta(`${params.revenueId} · Revenue record`,"Revenue recognition record with schedule, accounting entries and CRM contract linkage."),component:Page});

function Page(){const {revenueId}=Route.useParams();const [r,setR]=useState(()=>revStore.records.find(x=>x.id===revenueId)??revStore.records[0]!);const [tab,setTab]=useState("overview");const [adj,setAdj]=useState(false);const [log,setLog]=useState<string[][]>([]);const [confirmRev,setConfirmRev]=useState(false);
const pol=policies.find(p=>`${p.id} ${p.version}`===r.policy);
const update=(patch:Partial<typeof r>,entry:string[])=>{revStore.set(r.id,patch);setR({...r,...patch});setLog(l=>[entry,...l])};
const reverse=()=>{update({status:"Reversed",accounting:"Reversed",recognized:0},["Now","Maya Joseph",r.id,`Reversal journal JE-2026-04470 created (${A(r.recognized)})`,r.status,"Reversed"]);setConfirmRev(false)};
return <AppShell crumbs={["Workspace","Finance ERP","Revenue recognition",r.id]}><FinancePage eyebrow="REVENUE RECORD" title={r.id} description={`${r.customer} · ${r.project} · ${r.unit} · ${r.spa}`} actions={<div className="flex flex-wrap items-center gap-2"><RevBadge s={r.status}/><Button variant="secondary" onClick={()=>setAdj(true)} disabled={r.status==="Reversed"}>Adjust</Button>{confirmRev?<><span className="text-xs">Reverse {A(r.recognized)}?</span><Button onClick={reverse}>Confirm reversal</Button><Button variant="secondary" onClick={()=>setConfirmRev(false)}>Cancel</Button></>:<Button variant="secondary" disabled={!r.recognized||r.status==="Reversed"} onClick={()=>setConfirmRev(true)}>Reverse</Button>}</div>}>
<div className="mt-5"><Kpis items={[["Contract value",A(r.contract),`From ${r.spa} · CRM`,<CircleDollarSign/>],["Recognized to date",A(r.recognized),`Last recognition: ${r.lastPeriod}`,<TrendingUp/>],["Remaining",A(r.contract-r.recognized),"Unrecognized revenue",<Clock/>],["Collections",A(r.collected),`Outstanding ${A(r.contract-r.collected)}`,<Wallet/>]]}/></div>
<div className="mt-4"><Tabs value={tab} onValueChange={setTab} items={["Overview","Recognition schedule","Accounting entries","Contract / SPA","Collections","Documents","Activity","History"].map(l=>({value:l.toLowerCase().split(" ")[0]!.replace("/",""),label:l}))}/></div>
<div className="mt-4 space-y-4">
{tab==="overview"&&<div className="grid gap-4 xl:grid-cols-2"><Panel title="Recognition policy" subtitle="Managed in Settings / Finance accounting policies"><RecordTable headers={["Field","Value"]} rows={[["Recognition method","Configured policy"],["Basis",r.basis],["Policy",pol?pol.name:"Not assigned"],["Version",pol?.version??"—"],["Effective",pol?.effective??"—"],["Trigger",pol?.trigger??"—"]]}/><div className="mt-3 text-right"><Link to="/settings/accounting-policies" className="text-xs text-primary">Open policy settings →</Link></div></Panel><Panel flush title="Recognition eligibility" subtitle="Configurable checks — inputs, not recognition dates"><RecordTable headers={["Check","Input","Result"]} badges={[2]} rows={eligibilityFor(r)}/></Panel></div>}
{tab==="recognition"&&<><Panel flush title="Revenue recognition schedule" subtitle="Separate from the customer payment schedule unless the policy explicitly links them."><RecordTable headers={["Period","Eligible amount","Recognized amount","Cumulative recognized","Remaining","Journal","Status"]} badges={[6]} right={[1,2,3,4]} rows={scheduleFor(r).map(s=>[s[0],s[1],s[2],s[3],s[4],s[5]!=="—"?<Link to="/finance/ledger/journals/$journalId" params={{journalId:s[5]!}} className="text-primary">{s[5]}</Link>:"—",s[6]==="Scheduled"?"Pending":s[6]])}/></Panel><Placeholder title="Payment schedule is a separate concept">The customer installment plan lives in Payments & Collections. Recognition timing follows {pol?.name??"the assigned policy"}.</Placeholder></>}
{tab==="accounting"&&<Panel flush title="Accounting entries" subtitle={`Source: Revenue recognition · ${r.id} · one journal per period (no duplicate posting)`}>{r.recognized?<JournalLines lines={[{account:"2410 Customer advances",description:`${r.id} · ${r.lastPeriod}`,debit:r.recognized,credit:0,costCentre:"CC-SAL-01",project:r.project},{account:"4110 Property sales revenue",description:`${r.unit} · ${r.spa}`,debit:0,credit:r.recognized,costCentre:"CC-SAL-01",project:r.project}]}/>:<p className="p-6 text-center text-xs text-muted-foreground">No revenue has been posted for this record.</p>}</Panel>}
{tab==="contract"&&<Panel flush title="Contract / SPA linkage" subtitle="Read from CRM — not duplicated"><RecordTable headers={["Field","Value"]} rows={[["SPA",<Link to="/sales/spa/$spaId" params={{spaId:r.spa}} className="text-primary">{r.spa}</Link>],["SPA status",r.spaStatus],["Execution date",r.spaDate],["Contract value",`${A(r.contract)} (single value, not split per purchaser)`],["Purchasers",r.purchasers.join(" · ")],["CRM customer",<Link to="/customers/$customerId" params={{customerId:r.customerId}} className="text-primary">{r.customer} · {r.customerId}</Link>],["Unit",<Link to="/projects/units/$unitId" params={{unitId:r.unitId}} className="text-primary">{r.unit} · {r.unitType}</Link>],["Handover status",r.handover]]}/></Panel>}
{tab==="collections"&&<Panel flush title="Collections" subtitle="From Receivables — cash is not revenue"><RecordTable headers={["Receipt","Date","Amount","Status"]} badges={[3]} right={[2]} rows={r.collected?[["RCT-2026-00941","18 Sep 2026",A(Math.min(r.collected,122500)),"Posted"],["RCT-2026-00812","14 Jun 2026",A(Math.max(r.collected-122500,0)),"Posted"]]:[]} empty="No collections received yet."/></Panel>}
{tab==="documents"&&<Panel flush title="Documents"><RecordTable headers={["Document","Type","Uploaded"]} rows={[[`${r.spa}.pdf`,"Executed SPA","CRM"],["Recognition memo Sep 2026.pdf","Finance working","Layla Noor"]]}/></Panel>}
{(tab==="activity"||tab==="history")&&<Panel flush title={tab==="activity"?"Activity":"History"} subtitle="Policy version used at each recognition is preserved"><RecordTable headers={["Time","User","Record","Action","Before","After"]} rows={[...log,["30 Sep · 6:10 PM","System",r.id,`Recognized under ${r.policy}`,"Eligible",r.status],["14 Jun · 10:00 AM","System",r.spa,"SPA executed in CRM — revenue record created","—","Not Evaluated"]]}/></Panel>}
</div>
<AdjustmentModal open={adj} onOpenChange={setAdj} record={r} onSubmit={(n,reason)=>update({status:"Pending Review"},["Now","Maya Joseph",r.id,`Adjustment ${A(n)} submitted — ${reason}`,r.status,"Pending Review"])}/>
</FinancePage></AppShell>}
