import {createFileRoute,Link} from "@tanstack/react-router";
import {BookOpen,CheckCircle2,FilePlus2,ListChecks,Plus} from "lucide-react";
import {useState} from "react";
import {AppShell} from "@/components/app-shell";
import {fmt,glAccounts,journals,ledgerLines} from "@/components/finance/accounting-data";
import {Kpis,Panel,RecordTable,Toolbar,pageMeta} from "@/components/finance/accounting-ui";
import {GlAccountModal,JournalModal} from "@/components/finance/accounting-workflows";
import {FinancePage} from "@/components/finance/finance-ui";
import {Button,SelectMenu,StatusBadge,Tabs} from "@/components/ui/crm";
export const Route=createFileRoute("/finance/ledger/")({head:()=>pageMeta("General Ledger","Chart of accounts, journal entries, ledger view and trial balance."),component:Page});
function Page(){const [tab,setTab]=useState("coa");const [acct,setAcct]=useState(false);const [je,setJe]=useState(false);const [type,setType]=useState("All");
const tb=glAccounts.filter(a=>a.posting&&a.balance!==0);const dr=tb.reduce((s,a)=>s+(a.balance>0?a.balance:0),0),cr=tb.reduce((s,a)=>s+(a.balance<0?-a.balance:0),0);
return <AppShell crumbs={["Workspace","Finance ERP","General ledger"]}><FinancePage eyebrow="GENERAL LEDGER" title="General ledger" description="Chart of accounts, journals, posting workflow, ledger drill-down and trial balance." actions={<div className="flex gap-2"><Button variant="secondary" onClick={()=>setAcct(true)}><Plus size={15}/>GL account</Button><Button onClick={()=>setJe(true)}><FilePlus2 size={15}/>New journal</Button></div>}>
<div className="mt-5"><Kpis items={[["Active GL accounts",String(glAccounts.filter(a=>a.status==="Active").length),"Across 5 account types",<BookOpen/>],["Journals this period","412","Sep 2026 · open",<ListChecks/>],["Pending approval",String(journals.filter(j=>j.status==="Pending Approval").length),"Awaiting Finance Manager",<FilePlus2/>],["Trial balance",dr===cr?"Balanced":"Out of balance",`Dr ${fmt(dr)}`,<CheckCircle2/>]]}/></div>
<div className="mt-4"><Tabs value={tab} onValueChange={setTab} items={[{value:"coa",label:"Chart of accounts"},{value:"journals",label:"Journal entries"},{value:"ledger",label:"Ledger view"},{value:"tb",label:"Trial balance"}]}/></div>
<div className="mt-4">
{tab==="coa"&&<Panel flush title="Chart of accounts" subtitle="Header accounts cannot receive postings"><div className="flex flex-wrap gap-2 px-4 pb-3">{["All","Asset","Liability","Equity","Revenue","Expense"].map(t=><button key={t} onClick={()=>setType(t)} className={`rounded-full border px-3 py-1 text-[11px] ${type===t?"border-primary bg-primary text-primary-foreground":"border-border text-muted-foreground"}`}>{t}</button>)}</div><Toolbar placeholder="Search code or account name"/><RecordTable headers={["Code","Account name","Type","Parent","Normal balance","Posting","Balance","Status"]} badges={[7]} right={[6]} rows={glAccounts.filter(a=>type==="All"||a.type===type).map(a=>[a.code,a.posting?a.name:<strong>{a.name}</strong>,a.type,a.parent,a.normal,a.posting?"Posting":"Header",fmt(a.balance),a.status])}/></Panel>}
{tab==="journals"&&<Panel flush title="Journal entries" subtitle="System journals originate from AR, AP, bank, assets and accruals"><Toolbar placeholder="Search journal, source reference or description" filters={[["Status",["All","Draft","Pending Approval","Posted","Reversed"]],["Source",["All sources","AR Receipt","AP Payment","Bank Transfer","Depreciation","Manual"]]]}/><RecordTable headers={["Journal","Date","Period","Type","Source","Source ref","Description","Amount","Status"]} badges={[8]} right={[7]} rows={journals.map(j=>[<Link to="/finance/ledger/journals/$journalId" params={{journalId:j.id}} className="font-semibold text-primary">{j.id}</Link>,j.date,j.period,j.type,j.source,j.sourceRef,j.description,fmt(j.amount),j.status])}/></Panel>}
{tab==="ledger"&&<Panel flush title="Ledger — 1110 Bank — Operating" subtitle="Sep 2026 · running balance" actions={<div className="flex gap-2"><SelectMenu label="Account" items={glAccounts.filter(a=>a.posting).map(a=>`${a.code} ${a.name}`)}/><SelectMenu label="Period" items={["Sep 2026","Aug 2026","Q3 2026"]}/></div>}><RecordTable headers={["Date","Journal","Description","Debit","Credit","Source","Balance"]} right={[3,4,6]} rows={ledgerLines.map(l=>[l[0],l[1]?.startsWith("JE-")&&journals.some(j=>j.id===l[1])?<Link to="/finance/ledger/journals/$journalId" params={{journalId:l[1]}} className="text-primary">{l[1]}</Link>:l[1],l[2],l[3],l[4],l[5],l[6]])}/></Panel>}
{tab==="tb"&&<Panel flush title="Trial balance — as at 30 Sep 2026" subtitle="Posted journals only" actions={<StatusBadge tone={dr===cr?"success":"danger"}>{dr===cr?"Balanced":`Difference ${fmt(dr-cr)}`}</StatusBadge>}><RecordTable headers={["Code","Account","Type","Debit","Credit"]} right={[3,4]} rows={[...tb.map(a=>[a.code,a.name,a.type,a.balance>0?fmt(a.balance):"—",a.balance<0?fmt(-a.balance):"—"]),[<strong>Total</strong>,"","",<strong>{fmt(dr)}</strong>,<strong>{fmt(cr)}</strong>]]}/></Panel>}
</div><GlAccountModal open={acct} onOpenChange={setAcct}/><JournalModal open={je} onOpenChange={setJe}/></FinancePage></AppShell>}
