import {createFileRoute,Link} from "@tanstack/react-router";
import {Building,Layers,PieChart,Wallet} from "lucide-react";
import {useState} from "react";
import {AppShell} from "@/components/app-shell";
import {costCategories,directCosts,fmt,indirectCosts,overheadAllocation,overheads,projectCosts} from "@/components/finance/accounting-data";
import {Kpis,Panel,Placeholder,RecordTable,pageMeta} from "@/components/finance/accounting-ui";
import {FinancePage} from "@/components/finance/finance-ui";
import {ProgressBar,Tabs} from "@/components/ui/crm";
export const Route=createFileRoute("/finance/costing/")({head:()=>pageMeta("Project Costing","Project budgets, direct, indirect and overhead costs with allocation."),component:Page});
function Page(){const [tab,setTab]=useState("projects");const b=projectCosts.reduce((s,p)=>s+p.budget,0),a=projectCosts.reduce((s,p)=>s+p.actual,0),c=projectCosts.reduce((s,p)=>s+p.committed,0);return <AppShell crumbs={["Workspace","Finance ERP","Costing"]}><FinancePage eyebrow="PROJECT COSTING" title="Costing" description="Project cost control across direct, indirect and overhead cost pools.">
<div className="mt-5"><Kpis items={[["Total budget",`AED ${(b/1e6).toFixed(0)}M`,"3 active projects",<Building/>],["Actual cost",`AED ${(a/1e6).toFixed(1)}M`,`${Math.round(a/b*100)}% of budget`,<Wallet/>],["Committed",`AED ${(c/1e6).toFixed(1)}M`,"Open purchase commitments",<Layers/>],["Overhead this month","AED 730K","3 allocation runs",<PieChart/>]]}/></div>
<div className="mt-4"><Tabs value={tab} onValueChange={setTab} items={[{value:"projects",label:"Projects"},{value:"categories",label:"Cost categories"},{value:"direct",label:"Direct costs"},{value:"indirect",label:"Indirect costs"},{value:"overheads",label:"Overheads"}]}/></div>
<div className="mt-4 space-y-4">{tab==="projects"&&<Panel flush title="Project cost summary"><RecordTable headers={["Project","Budget","Committed","Actual","Remaining","Utilisation","Status"]} badges={[6]} right={[1,2,3,4]} rows={projectCosts.map(p=>[<Link to="/finance/costing/$projectId" params={{projectId:p.id}} className="font-semibold text-primary">{p.project}</Link>,fmt(p.budget),fmt(p.committed),fmt(p.actual),fmt(p.budget-p.actual-p.committed),<div className="w-28"><ProgressBar value={(p.actual+p.committed)/p.budget*100}/></div>,p.status==="At risk"?"Pending review":p.status])}/></Panel>}
{tab==="categories"&&<Panel flush title="Cost categories"><RecordTable headers={["Category","Classification","GL","Actual to date"]} right={[3]} rows={costCategories}/></Panel>}
{tab==="direct"&&<Panel flush title="Direct costs" subtitle="Sourced from approved AP invoices"><RecordTable headers={["Project","Category","Document","AP reference","Amount","Journal","Status"]} badges={[6]} right={[4]} rows={directCosts.map(d=>[d[0],d[1],d[2],<Link to="/finance/payables/$payableId" params={{payableId:d[3]??""}} className="text-primary">{d[3]}</Link>,d[4],d[5],d[6]])}/></Panel>}
{tab==="indirect"&&<Panel flush title="Indirect costs"><RecordTable headers={["Project","Category","Cost centre","Amount","Period","Status"]} badges={[5]} right={[3]} rows={indirectCosts}/></Panel>}
{tab==="overheads"&&<><Panel flush title="Overhead pools"><RecordTable headers={["Pool","Description","Cost centre","Amount","Driver","Period","Status"]} badges={[6]} right={[3]} rows={overheads}/></Panel><div className="grid gap-4 xl:grid-cols-2"><Panel flush title="Allocation result — Sep 2026" subtitle="Driver: revenue share"><RecordTable headers={["Receiving project","Share","Allocated"]} right={[1,2]} rows={overheadAllocation}/></Panel><Placeholder title="Allocation architecture">Overhead pools collected on cost centres are allocated monthly to projects by configurable drivers (revenue share, headcount, area). Each run produces an allocation journal crediting the source cost centre and debiting project cost.</Placeholder></div></>}</div></FinancePage></AppShell>}
