import {createFileRoute,Link,notFound} from "@tanstack/react-router";
import {useState} from "react";
import {AppShell} from "@/components/app-shell";
import {AuditPanel,Panel,pageMeta} from "@/components/finance/accounting-ui";
import {FinancePage} from "@/components/finance/finance-ui";
import {conflicts} from "@/components/finance/integration-data";
import {Button,FieldError,FormField,StatusBadge,Textarea} from "@/components/ui/crm";
export const Route=createFileRoute("/finance/integration/conflicts/$conflictId")({loader:({params})=>{const conflict=conflicts.find(c=>c.id===params.conflictId);if(!conflict)throw notFound();return {conflict}},head:({loaderData})=>loaderData?pageMeta(`${loaderData.conflict.id} · Data conflict`,`Resolve ${loaderData.conflict.field} mismatch for ${loaderData.conflict.customer}.`):{meta:[{title:"Conflict not found"},{name:"robots",content:"noindex"}]},notFoundComponent:()=><AppShell><div className="p-8 text-sm">Conflict not found. <Link to="/finance/integration" className="text-primary">Back</Link></div></AppShell>,component:Page});
function Page(){const {conflict:c}=Route.useLoaderData();const [choice,setChoice]=useState(c.authority.startsWith("Finance")?"finance":"crm");const [reason,setReason]=useState("");const [error,setError]=useState("");const [status,setStatus]=useState(c.status);const [log,setLog]=useState<string[][]>([]);
const resolve=()=>{if(reason.trim().length<10)return setError("Enter a resolution note (10+ characters) for the audit trail");setError("");setLog(l=>[["Just now","Maya Joseph",c.id,`Resolved using ${choice==="crm"?"CRM":"Finance"} value — ${reason.trim()}`,"Open","Resolved"],...l]);setStatus("Resolved")};
return <AppShell crumbs={["Finance ERP","Integration monitor",c.id]}><FinancePage eyebrow="DATA CONFLICT" title={c.field} description={`${c.customer} · raised ${c.raised} · event ${c.event}`} actions={<StatusBadge tone={status==="Resolved"?"success":"warning"}>{status}</StatusBadge>}>
<div className="mt-5 grid gap-4 md:grid-cols-2">{([["crm","CRM value",c.crm],["finance","Finance ERP value",c.finance]] as const).map(([k,l,v])=><button key={k} disabled={status==="Resolved"} onClick={()=>setChoice(k)} className={`rounded-md border bg-surface p-4 text-left ${choice===k?"border-primary ring-1 ring-primary":"border-border"}`}><span className="text-[11px] text-muted-foreground">{l}</span><strong className="mt-1 block text-lg">{v}</strong>{c.authority.toLowerCase().startsWith(k==="crm"?"crm":"finance")&&<StatusBadge tone="info" className="mt-2">Authoritative source</StatusBadge>}</button>)}</div>
<div className="mt-4"><Panel title="Resolution" subtitle={`Rule: ${c.authority}`}>{status==="Resolved"?<p className="text-xs text-success">Resolved. Both systems now hold the selected value; the prior value is kept in history.</p>:<><FormField label="Resolution note"><Textarea value={reason} maxLength={500} onChange={e=>setReason(e.target.value)}/></FormField><FieldError>{error}</FieldError><div className="mt-3 flex justify-end"><Button onClick={resolve}>Apply {choice==="crm"?"CRM":"Finance"} value</Button></div></>}</Panel></div>
<div className="mt-4"><AuditPanel rows={[...log,[c.raised,"System",c.id,"Conflict detected","—","Open"]]}/></div></FinancePage></AppShell>}
