import {unitProfitRows} from "@/components/finance/client-feedback";
import {aed} from "@/components/payments/payment-data";
import {createFileRoute,Link} from "@tanstack/react-router";
import {Percent,TrendingDown,TrendingUp,Wallet} from "lucide-react";
import {useState} from "react";
import {AppShell} from "@/components/app-shell";
import {Kpis,Panel,Placeholder,RecordTable,pageMeta} from "@/components/finance/accounting-ui";
import {K,projectFinancing} from "@/components/finance/borrowing-data";
import {FinancePage} from "@/components/finance/finance-ui";
import {profitability} from "@/components/finance/spend-data";
import {M,projectSales} from "@/components/finance/revenue-data";
import {SalesDistinction} from "@/components/finance/revenue-ui";
import {ProgressBar,Tabs} from "@/components/ui/crm";
export const Route=createFileRoute("/finance/profitability/")({head:()=>pageMeta("Profitability","Project and business-unit profitability from revenue, cost and overhead."),component:Page});
const ids:Record<string,string>={"Horizon Residences":"PC-HR","Green Park":"PC-GP","Creek Vista":"PC-CV","Resale & services":"PC-SVC"};
function Page(){const [dim,setDim]=useState("project");return <AppShell crumbs={["Workspace","Finance ERP","Profitability"]}><FinancePage eyebrow="PROFITABILITY" title="Profitability" description="Revenue, direct cost, overhead and margin sourced from the ledger, costing and profit centres.">
<div className="mt-5"><Kpis items={[["Revenue FY2026","AED 87.6M","Recognised to date",<TrendingUp/>],["Total cost","AED 72.5M","Direct + allocated overhead",<Wallet/>],["Net contribution","AED 15.1M","After overhead",<TrendingDown/>],["Net margin","17%","Target 20%",<Percent/>]]}/></div>
<div className="mt-4"><Tabs value={dim} onValueChange={setDim} items={[{value:"project",label:"By project"},{value:"sales",label:"Sales vs revenue"},{value:"finance",label:"Finance cost"},{value:"unit",label:"By unit"},{value:"contribution",label:"Contribution"},{value:"sources",label:"Data sources"}]}/></div>
<div className="mt-4 space-y-4">{dim==="project"&&<Panel flush title="Project profitability"><RecordTable headers={["Project","Revenue","Direct cost","Overhead","Net contribution","Margin","Status"]} badges={[6]} right={[1,2,3,4,5]} rows={profitability.map(p=>[<Link to="/finance/profit-centres/$centreId" params={{centreId:ids[p[0]??""]??"PC-HR"}} className="font-semibold text-primary">{p[0]}</Link>,p[1],p[2],p[3],p[4],p[5],p[6]==="At risk"?"Pending review":p[6]==="On target"?"Active":p[6]])}/></Panel>}
{dim==="sales"&&<><SalesDistinction/><Panel flush title="Project sales summary" subtitle="Profitability uses recognized revenue — not contract value or collections."><RecordTable headers={["Project","Units sold","Contract value","Recognized","Unrecognized","Collected","Outstanding","Project cost","Margin on recognized"]} right={[1,2,3,4,5,6,7,8]} rows={projectSales.map(p=>[<Link to="/finance/revenue/projects/$projectId" params={{projectId:p.id}} className="font-semibold text-primary">{p.project}</Link>,String(p.sold),M(p.contract),M(p.recognized),M(p.contract-p.recognized),M(p.collected),M(p.contract-p.collected),M(p.cost),`${Math.round((p.recognized-p.cost*p.recognized/p.contract)/p.recognized*100)}%`])}/></Panel></>}
{dim==="unit"&&<Panel flush title="Unit profitability" subtitle="Snapshots finalized at handover; estimates before handover."><RecordTable headers={["Unit","Project","Customer","Revenue","Total cost","Profit","Margin","Status"]} badges={[7]} right={[3,4,5,6]} rows={unitProfitRows.map(u=>[u[0],u[1],u[2],aed(u[3]),aed(u[4]),aed(u[3]-u[4]),`${(((u[3]-u[4])/u[3])*100).toFixed(1)}%`,u[5]==="Finalized at Handover"?"Active":u[5]==="Adjusted after Handover"?"Pending review":u[5]])}/></Panel>}{dim==="contribution"&&<Panel title="Contribution to net profit">{[["Horizon Residences",94],["Resale & services",6],["Green Park",28],["Creek Vista",-27]].map(([l,v])=><div key={String(l)} className="mb-3"><div className="mb-1 flex justify-between text-xs"><span>{l}</span><strong className={Number(v)<0?"text-danger":""}>{v}%</strong></div><ProgressBar value={Math.abs(Number(v))}/></div>)}</Panel>}
{dim==="finance"&&<Panel flush title="Finance cost in profitability" subtitle="Capitalized borrowing cost is part of project cost (via Costing); expensed finance cost is shown separately below gross margin — never counted twice."><RecordTable headers={["Project","Capitalized borrowing cost (in project cost)","Expensed finance cost (P&L)","Pending review","Basis"]} right={[1,2,3]} rows={projectFinancing.map(p=>[p.project,K(p.cap),K(p.exp),K(p.pending),p.policy])}/></Panel>}
{dim==="sources"&&<Placeholder title="Single source of truth">Revenue from GL 4xxx (AR / SPA milestones) · direct cost from Project Costing (AP & expenses) · overhead from monthly allocation runs · all figures drill down to posted journals. Nothing is re-entered here.</Placeholder>}</div></FinancePage></AppShell>}
