import {createFileRoute,Link,notFound} from "@tanstack/react-router";
import {useState} from "react";
import {AppShell} from "@/components/app-shell";
import {assets,fmt} from "@/components/finance/accounting-data";
import {AuditPanel,Panel,Placeholder,RecordTable,pageMeta} from "@/components/finance/accounting-ui";
import {DisposalModal} from "@/components/finance/accounting-workflows";
import {FinancePage} from "@/components/finance/finance-ui";
import {InfoGrid} from "@/components/sales/sales-ui";
import {Button,StatusBadge,Tabs} from "@/components/ui/crm";
export const Route=createFileRoute("/finance/assets/$assetId")({loader:({params})=>{const asset=assets.find(a=>a.id===params.assetId);if(!asset)throw notFound();return {asset}},head:({loaderData})=>loaderData?pageMeta(`${loaderData.asset.name} · Asset 360`,`Acquisition, depreciation and lifecycle for ${loaderData.asset.id}.`):{meta:[{title:"Asset not found"},{name:"robots",content:"noindex"}]},notFoundComponent:()=><AppShell><div className="p-8 text-sm">Asset not found. <Link to="/finance/assets" className="text-primary">Back</Link></div></AppShell>,component:Page});
function Page(){const {asset:a}=Route.useLoaderData();const [tab,setTab]=useState("overview");const [status,setStatus]=useState(a.status);const [dispose,setDispose]=useState(false);const nbv=a.cost-a.accumulated;const years=Number(a.life.split(" ")[0])||5;const monthly=Math.round(a.cost/(years*12));
return <AppShell crumbs={["Finance ERP","Assets",a.id]}><FinancePage eyebrow={`ASSET 360 · ${a.id}`} title={a.name} description={`${a.category} · ${a.location} · ${a.costCentre}`} actions={<div className="flex gap-2"><StatusBadge tone={status==="In use"?"success":"warning"}>{status}</StatusBadge>{status!=="Disposal pending approval"&&<Button variant="secondary" onClick={()=>setDispose(true)}>Dispose</Button>}</div>}>
<div className="mt-5"><Tabs value={tab} onValueChange={setTab} items={[{value:"overview",label:"Overview"},{value:"dep",label:"Depreciation"},{value:"audit",label:"Audit"}]}/></div>
<div className="mt-4 space-y-4">{tab==="overview"&&<div className="grid gap-4 xl:grid-cols-2"><Panel title="Financials"><InfoGrid items={[["Acquisition cost",fmt(a.cost)],["Accumulated depreciation",fmt(a.accumulated)],["Net book value",fmt(nbv)],["Acquired",a.acquired],["Method",a.method],["Useful life",a.life]]}/></Panel><Panel title="Acquisition source" subtitle="Linked to Step 01 Accounts Payable — not duplicated"><InfoGrid columns="grid-cols-1" items={[["Supplier",a.supplier],["AP document",a.apRef],["Capitalisation journal","JE-2025-01184"]]}/><Link to="/finance/payables" className="mt-4 inline-block text-xs font-medium text-primary">Open Accounts payable</Link></Panel></div>}
{tab==="dep"&&<><Placeholder title="Depreciation architecture">{a.method} over {a.life} · monthly charge {fmt(monthly)} · Dr 6410 Depreciation expense / Cr 1590 Accumulated depreciation · posted by the month-end depreciation run.</Placeholder><Panel flush title="Depreciation schedule"><RecordTable headers={["Period","Charge","Accumulated","NBV","Journal","Status"]} badges={[5]} right={[1,2,3]} rows={["Jul 2026","Aug 2026","Sep 2026","Oct 2026"].map((p,i)=>{const acc=Math.min(a.cost,a.accumulated-monthly*(2-i));return [p,fmt(monthly),fmt(acc),fmt(a.cost-acc),i<2?`JE-2026-0${4188+i*202}`:"—",i<2?"Posted":"Scheduled"]})}/></Panel></>}
{tab==="audit"&&<AuditPanel rows={[["Just now","Maya Joseph",a.id,"Status",a.status,status],["31 Aug · 6:00 PM","System",a.id,"Depreciation posted","—","JE-2026-04390"]]}/>}</div>
<DisposalModal open={dispose} onOpenChange={setDispose} nbv={nbv} onConfirm={()=>setStatus("Disposal pending approval")}/></FinancePage></AppShell>}
