import {createFileRoute,Link} from "@tanstack/react-router";
import {AlertTriangle,Clock,Plus,Receipt,Wallet} from "lucide-react";
import {useState} from "react";
import {AppShell} from "@/components/app-shell";
import {fmt} from "@/components/finance/accounting-data";
import {Kpis,Panel,RecordTable,Toolbar,pageMeta} from "@/components/finance/accounting-ui";
import {FinancePage} from "@/components/finance/finance-ui";
import {auditIssues,budgets,expenses,reimbursements} from "@/components/finance/spend-data";
import {ExpenseModal} from "@/components/finance/spend-workflows";
import {Button,Tabs} from "@/components/ui/crm";
export const Route=createFileRoute("/finance/expenses/")({head:()=>pageMeta("Expenses","Expense capture, budget checks, approval queue, reports and expense audit."),component:Page});
const link=(id:string)=><Link to="/finance/expenses/$expenseId" params={{expenseId:id}} className="font-semibold text-primary">{id}</Link>;
function Page(){const [tab,setTab]=useState("list");const [create,setCreate]=useState(false);const [issues,setIssues]=useState(auditIssues);const pending=expenses.filter(e=>e.status==="Pending approval");
return <AppShell crumbs={["Workspace","Finance ERP","Expenses"]}><FinancePage eyebrow="EXPENSE MANAGEMENT" title="Expenses" description="Employee, company and project expenses checked against budget and routed through finance approval." actions={<Button onClick={()=>setCreate(true)}><Plus size={15}/>New expense</Button>}>
<div className="mt-5"><Kpis items={[["Expenses this month","AED 305K","148 submissions",<Receipt/>],["Pending approval",String(pending.length+11),"AED 212K awaiting",<Clock/>],["Paid this month","AED 184K","Via AP, card and payroll",<Wallet/>],["Audit flags",String(issues.filter(i=>i[4]!=="Resolved").length),"Duplicates & missing receipts",<AlertTriangle/>]]}/></div>
<div className="mt-4"><Tabs value={tab} onValueChange={setTab} items={[{value:"list",label:"All expenses"},{value:"queue",label:"Approval queue"},{value:"reports",label:"Reports"},{value:"audit",label:"Expense audit"}]}/></div>
<div className="mt-4 space-y-4">{tab==="list"&&<Panel flush title="Expenses"><Toolbar placeholder="Search expense, employee, vendor or project" filters={[["Type",["All types","Employee expense","Company expense","Project expense"]],["Status",["All","Pending approval","Approved","Paid","Returned","Rejected","Missing documents"]],["Project",["All projects","Horizon Residences","Green Park","Creek Vista"]]]}/><RecordTable headers={["Expense","Date","Employee","Type","Category","Vendor","Project","Cost centre","Amount","Docs","Status"]} badges={[10]} right={[8]} rows={expenses.map(e=>[link(e.id),e.date,e.employee,e.type,e.category,e.vendor,e.project,e.costCentre,fmt(e.amount),String(e.docs),e.status])}/></Panel>}
{tab==="queue"&&<Panel flush title="Finance approval queue" subtitle="Expenses and reimbursements awaiting your decision · configured in Settings → Workflows"><RecordTable headers={["Item","Type","Requester","Amount","Budget","Waiting","Status"]} badges={[6]} right={[3]} rows={[...pending.map(e=>{const b=budgets.find(x=>x.id===e.budgetId);return [link(e.id),"Expense",e.employee,fmt(e.amount),b&&b.actual+b.committed+e.amount>b.amount?"Over budget":"Within budget","2 days","Pending approval"]}),...reimbursements.filter(r=>r.status==="Pending approval").map(r=>[<Link to="/finance/reimbursements/$reimbursementId" params={{reimbursementId:r.id}} className="font-semibold text-primary">{r.id}</Link>,"Reimbursement",r.employee,fmt(r.amount),"Within budget","8 days · escalated","Pending approval"])]}/></Panel>}
{tab==="reports"&&<><Panel flush title="Expense by category — Sep 2026"><RecordTable headers={["Category","Count","Amount","Budget","Variance"]} right={[1,2,3,4]} rows={[["Events & launches","6","AED 180,000","AED 150,000","AED -30,000"],["Digital campaigns","22","AED 65,000","AED 130,000","AED 65,000"],["Site utilities","4","AED 48,200","AED 52,000","AED 3,800"],["Travel","18","AED 6,800","AED 25,000","AED 18,200"],["Client entertainment","31","AED 4,900","AED 12,000","AED 7,100"]]}/></Panel><Panel title="Monthly trend" subtitle="AED thousands"><div className="grid h-32 grid-cols-6 items-end gap-3 border-b border-border px-2">{[210,246,198,262,288,305].map((v,i)=><div key={i} className="mx-auto w-5 rounded-t-sm bg-primary" style={{height:`${v/3.2}%`}}/>)}</div><div className="mt-2 grid grid-cols-6 text-center text-[10px] text-muted-foreground">{["Apr","May","Jun","Jul","Aug","Sep"].map(m=><span key={m}>{m}</span>)}</div></Panel></>}
{tab==="audit"&&<Panel flush title="Audit review queue" subtitle="Duplicate detection, missing documents and policy compliance"><RecordTable headers={["Issue","Expense","Finding","Type","Status","Action"]} badges={[4]} rows={issues.map((i,k)=>[i[0],link(i[1]??""),i[2],i[3],i[4],i[4]!=="Resolved"?<Button variant="secondary" className="h-7 px-2 text-[11px]" onClick={()=>setIssues(x=>x.map((y,j)=>j===k?[...y.slice(0,4),"Resolved"]:y))}>Resolve</Button>:"—"])}/></Panel>}</div>
<ExpenseModal open={create} onOpenChange={setCreate}/></FinancePage></AppShell>}
