import {createFileRoute,Link} from "@tanstack/react-router";
import {CheckCircle2,ClipboardList,Download,FileBarChart,Play,TrendingUp,Wallet} from "lucide-react";
import {useState} from "react";
import {AppShell} from "@/components/app-shell";
import {Kpis,Panel,Placeholder,RecordTable,Toolbar,pageMeta} from "@/components/finance/accounting-ui";
import {FinancePage} from "@/components/finance/finance-ui";
import {A,M,contractChanges,exceptions,policyOptions,projectSales,revStatuses,revenueAudit,revenueReports,revenueTrend,reviewQueue} from "@/components/finance/revenue-data";
import {RevBadge,RunRecognitionModal,SalesDistinction,revStore} from "@/components/finance/revenue-ui";
import {Button,DashboardCard,ProgressBar,SelectMenu,Tabs} from "@/components/ui/crm";

export const Route=createFileRoute("/finance/revenue/")({head:()=>pageMeta("Revenue recognition","Track contracted sales, recognized revenue and accounting treatment across projects and units."),component:Page});

function Page(){
const [tab,setTab]=useState("records");const [run,setRun]=useState(false);const [records,setRecords]=useState(revStore.records);const [queue,setQueue]=useState(reviewQueue);const [statusF,setStatusF]=useState("All");const [msg,setMsg]=useState("");
const contract=projectSales.reduce((s,p)=>s+p.contract,0),recog=projectSales.reduce((s,p)=>s+p.recognized,0);
const counts=revStatuses.map(s=>[s,records.filter(r=>r.status===s).length] as const);
const onRun=(ids:string[],amount:number)=>{setQueue(q=>[["RRB-2026-09-03","Sep 2026","All projects",`${ids.length} records`,A(amount),"Maya Joseph","Pending approval"],...q]);ids.forEach(id=>revStore.set(id,{status:"Pending Review",accounting:"Pending posting"}));setRecords(revStore.records)};
const decide=(id:string,approve:boolean)=>{setQueue(q=>q.map(r=>r[0]===id?[...r.slice(0,6),approve?"Posted":"Rejected"]:r));if(id==="RRB-2026-09-03"){revStore.records.filter(r=>r.accounting==="Pending posting").forEach(r=>revStore.set(r.id,approve?{status:"Partially Recognized",accounting:"Posted",recognized:r.recognized+Math.round((r.contract-r.recognized)*0.2),lastPeriod:"Sep 2026"}:{status:"Eligible",accounting:"Not posted"}));setRecords(revStore.records)}setMsg(approve?`${id} approved — journals JE-2026-04460…posted to General ledger (Dr 2410 / Cr 4110).`:`${id} rejected and returned to preparer.`)};
const shown=records.filter(r=>statusF==="All"||r.status===statusF);
return <AppShell crumbs={["Workspace","Finance ERP","Revenue recognition"]}><FinancePage eyebrow="REVENUE ACCOUNTING" title="Revenue recognition" description="Track contracted sales, recognized revenue and accounting treatment across projects and units." actions={<div className="flex flex-wrap gap-2"><SelectMenu label="Period: Sep 2026" items={["Sep 2026","Aug 2026","Jul 2026","FY2026"]}/><SelectMenu label="All projects" items={["All projects",...projectSales.map(p=>p.project)]}/><Button variant="secondary"><Download size={15}/>Export</Button><Button onClick={()=>setRun(true)}><Play size={15}/>Run recognition</Button></div>}>
<div className="mt-5"><Kpis items={[["Contracted sales",M(contract),"Executed SPAs · CRM",<FileBarChart/>],["Recognized revenue",M(recog),"Posted per configured policy",<TrendingUp/>],["Unrecognized revenue",M(contract-recog),"Remaining contract value",<Wallet/>],["Pending review",String(records.filter(r=>r.status==="Pending Review").length+16),"Transactions awaiting Finance review",<ClipboardList/>]]}/></div>
<DashboardCard className="mt-4 grid grid-cols-2 gap-px overflow-hidden bg-border sm:grid-cols-4 xl:grid-cols-8">{counts.map(([s,n])=><button key={s} onClick={()=>{setStatusF(s);setTab("records")}} className={`bg-surface p-3 text-left hover:bg-muted ${statusF===s?"bg-muted":""}`}><span className="block text-[11px] text-muted-foreground">{s}</span><strong className="text-lg">{n}</strong></button>)}</DashboardCard>
<div className="mt-3"><Placeholder title="IFRS 15-ready revenue recognition workflow">Revenue is recognized according to the company's approved accounting policy configured in Settings → Finance accounting policies. Booking, SPA, payment and handover dates are inputs only — none is assumed to be the recognition date.</Placeholder></div>
<div className="mt-4"><Tabs value={tab} onValueChange={setTab} items={[{value:"records",label:"Revenue records"},{value:"projects",label:"Project sales"},{value:"review",label:"Review queue"},{value:"exceptions",label:"Exceptions"},{value:"changes",label:"Contract changes"},{value:"dashboard",label:"Dashboard"},{value:"reports",label:"Reports"},{value:"audit",label:"Close & audit"}]}/></div>
{msg&&<p className="mt-3 rounded-md border border-border bg-success-soft p-2 text-xs text-success">{msg}</p>}
<div className="mt-4 space-y-4">
{tab==="records"&&<Panel flush title="Revenue records" subtitle={statusF==="All"?"All recognition statuses":`Filtered: ${statusF}`} actions={statusF!=="All"?<Button variant="secondary" className="m-4 h-7 px-2 text-[11px]" onClick={()=>setStatusF("All")}>Clear filter</Button>:undefined}><Toolbar placeholder="Search reference, customer, unit or SPA" filters={[["Recognition basis",policyOptions],["SPA status",["Executed","Pending signature","Amended","Terminated"]],["Accounting status",["Posted","Pending posting","Not posted","Reversed"]]]}/><RecordTable headers={["Reference","Customer","Project / Unit","Contract value","Recognition basis","Recognized","Remaining","Accounting","Recognition","Actions"]} right={[3,5,6]} rows={shown.map(r=>[<Link to="/finance/revenue/$revenueId" params={{revenueId:r.id}} className="font-semibold text-primary">{r.id}</Link>,r.customer,`${r.project} · ${r.unit}`,A(r.contract),r.basis,A(r.recognized),A(r.contract-r.recognized),<RevBadge s={r.accounting}/>,<RevBadge s={r.status}/>,<Link to="/finance/revenue/$revenueId" params={{revenueId:r.id}} className="text-primary">Open</Link>])}/></Panel>}
{tab==="projects"&&<><SalesDistinction/><Panel flush title="Project sales" subtitle="From CRM units & SPAs — no separate sales figures are entered."><Toolbar placeholder="Search project" filters={[["Building / tower",["All","Tower A","Tower B","Block C"]],["Unit type",["All","Studio","1 BR","2 BR","3 BR","Townhouse"]],["SPA status",["All","Executed","Amended"]]]}/><RecordTable headers={["Project","Units sold","Contract value","Recognized","Unrecognized","Collected","Outstanding","Recognition status","Actions"]} right={[1,2,3,4,5,6]} rows={projectSales.map(p=>[<Link to="/finance/revenue/projects/$projectId" params={{projectId:p.id}} className="font-semibold text-primary">{p.project}</Link>,`${p.sold} / ${p.totalUnits}`,M(p.contract),M(p.recognized),M(p.contract-p.recognized),M(p.collected),M(p.contract-p.collected),<RevBadge s={p.status}/>,<Link to="/finance/revenue/projects/$projectId" params={{projectId:p.id}} className="text-primary">Drill down</Link>])}/></Panel></>}
{tab==="review"&&<Panel flush title="Recognition review queue" subtitle="Maker-checker: the preparer cannot approve their own batch."><RecordTable headers={["Batch","Period","Scope","Records","Amount","Prepared by","Status","Action"]} right={[4]} rows={queue.map(q=>[...q.slice(0,6),<RevBadge s={q[6]==="Pending approval"?"Pending Review":q[6]==="Rejected"?"Reversed":q[6]??""}/>,q[6]==="Pending approval"?<div className="flex gap-1"><Button className="h-7 px-2 text-[11px]" onClick={()=>decide(q[0]??"",true)}><CheckCircle2 size={13}/>Approve & post</Button><Button variant="secondary" className="h-7 px-2 text-[11px]" onClick={()=>decide(q[0]??"",false)}>Reject</Button></div>:"—"])}/></Panel>}
{tab==="exceptions"&&<Panel flush title="Recognition exceptions" subtitle="Records blocked by eligibility checks are never recognized automatically."><RecordTable headers={["Exception","Record","Reason","Customer","Next step","Status"]} badges={[5]} rows={exceptions.map(e=>[e[0],<Link to="/finance/revenue/$revenueId" params={{revenueId:e[1]??""}} className="text-primary">{e[1]}</Link>,e[2],e[3],e[4],e[5]==="Open"?"Pending review":"Closed"])}/></Panel>}
{tab==="changes"&&<Panel flush title="CRM contract changes" subtitle="Amendments, swaps and terminations from CRM require Finance review before revenue is adjusted or reversed."><RecordTable headers={["Change","SPA","Type","Value change","Customer","Status"]} badges={[5]} rows={contractChanges.map(c=>[...c.slice(0,5),c[5]==="Reviewed"?"Reviewed":"Pending review"])}/></Panel>}
{tab==="dashboard"&&<div className="grid gap-4 xl:grid-cols-2"><Panel title="Recognized revenue trend" subtitle="AED millions, posted per period">{revenueTrend.map(([m,v])=><div key={m} className="mb-2 grid grid-cols-[40px_1fr_70px] items-center gap-2 text-xs"><span>{m}</span><ProgressBar value={(v/35)*100}/><strong className="text-right">AED {v}M</strong></div>)}</Panel><Panel title="Project revenue distribution" subtitle="Share of recognized revenue">{projectSales.map(p=><div key={p.id} className="mb-3"><div className="mb-1 flex justify-between text-xs"><span>{p.project}</span><strong>{Math.round(p.recognized/recog*100)}% · {M(p.recognized)}</strong></div><ProgressBar value={p.recognized/recog*100}/></div>)}</Panel></div>}
{tab==="reports"&&<Panel flush title="Revenue reports" subtitle="Filters: period, project, building, unit type, policy, status"><RecordTable headers={["Report","Contents","Export"]} rows={revenueReports.map(r=>[r[0],r[1],<div className="flex gap-1"><Button variant="secondary" className="h-7 px-2 text-[11px]" onClick={()=>setMsg(`${r[0]} queued as Excel (sample — no file generated).`)}>Excel</Button><Button variant="secondary" className="h-7 px-2 text-[11px]" onClick={()=>setMsg(`${r[0]} queued as PDF (sample — no file generated).`)}>PDF</Button></div>])}/></Panel>}
{tab==="audit"&&<><Panel flush title="Financial close validation · Sep 2026" subtitle="Linked to Financial close checklist"><RecordTable headers={["Check","Result","Status"]} badges={[2]} rows={[["Recognition batch for period approved & posted",queue.some(q=>q[1]==="Sep 2026"&&q[6]==="Pending approval")?"Batch awaiting approval":"Complete",queue.some(q=>q[1]==="Sep 2026"&&q[6]==="Pending approval")?"Blocked":"Passed"],["Open recognition exceptions","4 open","Pending review"],["Revenue sub-ledger reconciled to GL 4110","Difference AED 0","Passed"],["Unreviewed CRM contract changes","2 pending","Pending review"]]}/><div className="border-t border-border p-3 text-right"><Link to="/finance/close" className="text-xs text-primary">Open Financial close →</Link></div></Panel><Panel flush title="Revenue audit trail" subtitle="Historical records keep the policy version used at the time"><RecordTable headers={["Time","User","Record","Action","Before","After"]} rows={revenueAudit}/></Panel></>}
</div>
<RunRecognitionModal open={run} onOpenChange={setRun} onRun={onRun}/>
</FinancePage></AppShell>}
