import {createFileRoute,Link,notFound} from "@tanstack/react-router";
import {useState} from "react";
import {AppShell} from "@/components/app-shell";
import {fmt} from "@/components/finance/accounting-data";
import {AuditPanel,JournalLines,Panel,Placeholder,RecordTable,pageMeta} from "@/components/finance/accounting-ui";
import {ReasonModal} from "@/components/finance/accounting-workflows";
import {FinancePage} from "@/components/finance/finance-ui";
import {budgets,expenses} from "@/components/finance/spend-data";
import {InfoGrid} from "@/components/sales/sales-ui";
import {Button,StatusBadge,Tabs} from "@/components/ui/crm";
export const Route=createFileRoute("/finance/expenses/$expenseId")({loader:({params})=>{const expense=expenses.find(e=>e.id===params.expenseId);if(!expense)throw notFound();return {expense}},head:({loaderData})=>loaderData?pageMeta(`${loaderData.expense.id} · Expense`,`${loaderData.expense.category} expense from ${loaderData.expense.vendor} with budget check and approval.`):{meta:[{title:"Expense not found"},{name:"robots",content:"noindex"}]},notFoundComponent:()=><AppShell><div className="p-8 text-sm">Expense not found. <Link to="/finance/expenses" className="text-primary">Back</Link></div></AppShell>,component:Page});
function Page(){const {expense:e}=Route.useLoaderData();const b=budgets.find(x=>x.id===e.budgetId);const avail=b?b.amount-b.actual-b.committed:0;const over=e.amount>avail;const [tab,setTab]=useState("overview");const [status,setStatus]=useState(e.status);const [modal,setModal]=useState<""|"reject"|"return">("");const [log,setLog]=useState<string[][]>([]);
const act=(next:string,action:string)=>{setLog(l=>[["Just now","Maya Joseph",e.id,action,status,next],...l]);setStatus(next)};const net=e.amount-e.vat;
return <AppShell crumbs={["Finance ERP","Expenses",e.id]}><FinancePage eyebrow={`EXPENSE · ${e.type.toUpperCase()}`} title={e.id} description={`${e.category} · ${e.vendor} · ${e.employee}`} actions={<div className="flex flex-wrap items-center gap-2"><StatusBadge tone={status==="Paid"||status==="Approved"?"success":status==="Rejected"?"danger":"warning"}>{status}</StatusBadge>{status==="Pending approval"&&<><Button variant="secondary" onClick={()=>setModal("return")}>Return</Button><Button variant="secondary" onClick={()=>setModal("reject")}>Reject</Button><Button onClick={()=>act("Approved","Approved")}>Approve</Button></>}{status==="Returned"&&<Button onClick={()=>act("Pending approval","Resubmitted")}>Resubmit</Button>}</div>}>
<div className="mt-5"><Tabs value={tab} onValueChange={setTab} items={[{value:"overview",label:"Overview"},{value:"approval",label:"Approval"},{value:"accounting",label:"Accounting & payment"},{value:"docs",label:"Documents"},{value:"audit",label:"Audit"}]}/></div>
<div className="mt-4 space-y-4">{tab==="overview"&&<div className="grid gap-4 xl:grid-cols-[1fr_360px]"><Panel title="Expense details"><InfoGrid items={[["Date",e.date],["Employee",`${e.employee} · ${e.department}`],["Vendor",e.vendor],["Category",e.category],["Project",e.project],["Cost centre",e.costCentre],["Net",fmt(net)],["VAT",fmt(e.vat)],["Total",fmt(e.amount)],["Source",e.source],["Payment method",e.payment],["AP reference",e.apRef]]}/></Panel>
<Panel title="Budget check" subtitle={b?`${b.id} · ${b.name}`:""}>{b&&<><InfoGrid columns="grid-cols-1" items={[["Available before",fmt(avail+(status==="Pending approval"?0:0))],["This expense",fmt(e.amount)],["Remaining after",fmt(avail-e.amount)]]}/><p className={`mt-3 rounded-md p-3 text-xs font-medium ${over?"bg-danger-soft text-danger":"bg-success-soft text-success"}`}>{over?"Over budget · routed to Finance Director as exception":"Within budget"}</p><Link to="/finance/budgets/$budgetId" params={{budgetId:b.id}} className="mt-3 inline-block text-xs font-medium text-primary">Open Budget 360</Link></>}</Panel></div>}
{tab==="approval"&&<Panel flush title="Approval workflow" subtitle="Sequential · configured in Settings → Workflows"><RecordTable headers={["Step","Approver","Rule","Status","Detail"]} badges={[3]} rows={[["1","Line manager","All expenses",status==="Pending approval"?"Approved":"Approved","Omar Haddad · 24 Sep"],["2","Finance Manager","> AED 10,000",status==="Pending approval"?"Pending":status,"Maya Joseph"],...(over?[["3","Finance Director","Over budget",status==="Approved"||status==="Paid"?"Approved":"Pending","Ahmed Malik"]]:[])]}/></Panel>}
{tab==="accounting"&&<><Placeholder title="Accounting impact">On approval the expense posts Dr expense GL / Dr VAT input / Cr {e.payment==="Supplier invoice"?"Accounts payable (via AP)":e.payment==="Reimbursement"?"Employee reimbursement payable":"Corporate card clearing"}. Payment settles through Cash & Bank.</Placeholder><Panel flush title="Proposed journal"><JournalLines lines={[{account:"6130 Expense",description:e.category,debit:net,credit:0,costCentre:e.costCentre,project:e.project},{account:"2320 VAT input recoverable",description:"VAT 5%",debit:e.vat,credit:0,costCentre:e.costCentre,project:e.project},{account:e.payment==="Supplier invoice"?"2110 Accounts payable":"2150 Employee payable",description:e.vendor,debit:0,credit:e.amount,costCentre:e.costCentre,project:e.project}]}/></Panel>{e.apRef!=="—"&&<Link to="/finance/payables" className="text-xs font-medium text-primary">Open linked payable {e.apRef}</Link>}</>}
{tab==="docs"&&<Panel flush title="Documents">{e.docs?<RecordTable headers={["Document","Type","Uploaded by","Date"]} rows={[[`${e.id}-receipt.pdf`,"Receipt / invoice",e.employee,e.date],...(e.docs>1?[[`${e.id}-quote.pdf`,"Quotation",e.employee,e.date]]:[])]}/>:<p className="p-6 text-center text-xs text-danger">Receipt missing — expense cannot be approved until a document is attached.</p>}</Panel>}
{tab==="audit"&&<AuditPanel rows={[...log,[e.date,e.employee,e.id,"Submitted","Draft","Pending approval"]]}/>}</div>
<ReasonModal open={modal==="reject"} onOpenChange={o=>!o&&setModal("")} title="Reject expense" label="Reject" onConfirm={r=>act("Rejected",`Rejected — ${r}`)}/><ReasonModal open={modal==="return"} onOpenChange={o=>!o&&setModal("")} title="Return for clarification" label="Return" onConfirm={r=>act("Returned",`Returned — ${r}`)}/></FinancePage></AppShell>}
