import {createFileRoute,Link} from "@tanstack/react-router";
import {Layers,Target,TrendingDown,Wallet} from "lucide-react";
import {AppShell} from "@/components/app-shell";
import {costCentres,fmt} from "@/components/finance/accounting-data";
import {Kpis,Panel,RecordTable,Toolbar,pageMeta} from "@/components/finance/accounting-ui";
import {FinancePage} from "@/components/finance/finance-ui";
export const Route=createFileRoute("/finance/cost-centres/")({head:()=>pageMeta("Cost Centres","Cost centre hierarchy, budget versus actual and cost allocation."),component:Page});
function Page(){const b=costCentres.filter(c=>c.level!=="Company").reduce((s,c)=>s+c.budget,0),a=costCentres.filter(c=>c.level!=="Company").reduce((s,c)=>s+c.actual,0);return <AppShell crumbs={["Workspace","Finance ERP","Cost centres"]}><FinancePage eyebrow="COST CENTRE ACCOUNTING" title="Cost centres" description="Track spend by department, function and project against budget.">
<div className="mt-5"><Kpis items={[["Cost centres",String(costCentres.length),"4 levels",<Layers/>],["Annual budget",`AED ${(b/1e6).toFixed(1)}M`,"FY2026",<Target/>],["Actual to date",`AED ${(a/1e6).toFixed(1)}M`,`${Math.round(a/b*100)}% utilised`,<Wallet/>],["Over 90% utilised","2","Marketing · Green Park",<TrendingDown/>]]}/></div>
<div className="mt-4 grid gap-4 xl:grid-cols-[320px_1fr]"><Panel title="Hierarchy" subtitle="Company → department → function / project"><div className="space-y-1 text-xs">{[["Corporate",0],["Finance",1],["Administration",1],["Sales",1],["Marketing",2],["Construction",1],["Creek Vista",2],["Green Park",2]].map(([n,l])=><div key={String(n)} style={{paddingLeft:Number(l)*16}} className="rounded-md py-1.5 hover:bg-muted">{Number(l)?"└ ":""}{n}</div>)}</div></Panel>
<Panel flush title="Cost centres"><Toolbar placeholder="Search cost centre or manager" filters={[["Level",["All levels","Department","Function","Project"]]]}/><RecordTable headers={["ID","Name","Parent","Level","Manager","Budget","Actual","Committed","Variance","Status"]} badges={[9]} right={[5,6,7,8]} rows={costCentres.map(c=>[<Link to="/finance/cost-centres/$centreId" params={{centreId:c.id}} className="font-semibold text-primary">{c.id}</Link>,c.name,c.parent,c.level,c.manager,fmt(c.budget),fmt(c.actual),fmt(c.committed),fmt(c.budget-c.actual-c.committed),c.status])}/></Panel></div></FinancePage></AppShell>}
