import {createFileRoute,Link} from "@tanstack/react-router";
import {AlertTriangle,ArrowLeftRight,Plus,Target,TrendingUp,Wallet} from "lucide-react";
import {useState} from "react";
import {AppShell} from "@/components/app-shell";
import {fmt} from "@/components/finance/accounting-data";
import {Kpis,Panel,RecordTable,Toolbar,pageMeta} from "@/components/finance/accounting-ui";
import {FinancePage} from "@/components/finance/finance-ui";
import {budgetMonthly,budgetTransfers,budgets} from "@/components/finance/spend-data";
import {BudgetModal,BudgetTransferModal} from "@/components/finance/spend-workflows";
import {Button,ProgressBar,Tabs} from "@/components/ui/crm";
export const Route=createFileRoute("/finance/budgets/")({head:()=>pageMeta("Budgets","Budget planning, allocation, utilisation, revisions and transfers."),component:Page});
function Page(){const [tab,setTab]=useState("list");const [create,setCreate]=useState(false);const [transfer,setTransfer]=useState(false);const fy=budgets.filter(b=>b.fy==="FY2026");const t=fy.reduce((s,b)=>s+b.amount,0),a=fy.reduce((s,b)=>s+b.actual,0),c=fy.reduce((s,b)=>s+b.committed,0);
return <AppShell crumbs={["Workspace","Finance ERP","Budgets"]}><FinancePage eyebrow="BUDGET MANAGEMENT" title="Budgets" description="Plan, allocate and control spend against approved budgets by cost centre and project." actions={<div className="flex gap-2"><Button variant="secondary" onClick={()=>setTransfer(true)}><ArrowLeftRight size={15}/>Transfer</Button><Button onClick={()=>setCreate(true)}><Plus size={15}/>New budget</Button></div>}>
<div className="mt-5"><Kpis items={[["Total budget FY2026",`AED ${(t/1e6).toFixed(1)}M`,`${fy.length} active budgets`,<Target/>],["Actual spend",`AED ${(a/1e6).toFixed(1)}M`,`${Math.round(a/t*100)}% utilised`,<Wallet/>],["Committed",`AED ${(c/1e6).toFixed(1)}M`,"Open POs & approved expenses",<TrendingUp/>],["Budget alerts","2","1 over · 1 above 90%",<AlertTriangle/>]]}/></div>
<div className="mt-4 grid gap-4 xl:grid-cols-[1.4fr_1fr]"><Panel title="Budget vs actual" subtitle="Cumulative % of annual budget · FY2026"><div className="grid h-40 grid-cols-6 items-end gap-3 border-b border-border px-2">{budgetMonthly.map(([m,p,ac])=><div key={m} className="flex h-full items-end justify-center gap-1"><div className="w-3 rounded-t-sm bg-primary" style={{height:`${p}%`}}/><div className={`w-3 rounded-t-sm ${ac>p?"bg-danger":"bg-action"}`} style={{height:`${ac}%`}}/></div>)}</div><div className="mt-2 grid grid-cols-6 text-center text-[10px] text-muted-foreground">{budgetMonthly.map(([m])=><span key={m}>{m}</span>)}</div><div className="mt-3 flex gap-4 text-[11px]"><span><i className="mr-1 inline-block size-2 bg-primary"/>Planned</span><span><i className="mr-1 inline-block size-2 bg-action"/>Actual</span><span><i className="mr-1 inline-block size-2 bg-danger"/>Above plan</span></div></Panel>
<Panel title="Distribution" subtitle="By budget type">{[["Project",110000000],["Operating",14100000],["Capital",1500000]].map(([l,v])=><div key={String(l)} className="mb-3"><div className="mb-1 flex justify-between text-xs"><span>{l}</span><strong>{fmt(Number(v))}</strong></div><ProgressBar value={Number(v)/t*100}/></div>)}</Panel></div>
<div className="mt-4"><Tabs value={tab} onValueChange={setTab} items={[{value:"list",label:"Budget list"},{value:"transfers",label:"Transfers"}]}/></div>
<div className="mt-4">{tab==="list"?<Panel flush title="Budgets"><Toolbar placeholder="Search budget, owner or cost centre" filters={[["Type",["All types","Project","Operating","Capital"]],["Fiscal year",["FY2026","FY2027"]],["Status",["All","Active","At risk","Over budget","Pending approval"]]]}/><RecordTable headers={["Budget","Name","Type","Cost centre","Project","Owner","Budget","Actual","Committed","Available","Utilisation","Status"]} badges={[11]} right={[6,7,8,9]} rows={budgets.map(b=>{const u=b.amount?Math.round((b.actual+b.committed)/b.amount*100):0;return [<Link to="/finance/budgets/$budgetId" params={{budgetId:b.id}} className="font-semibold text-primary">{b.id}</Link>,b.name,b.type,b.costCentre,b.project,b.owner,fmt(b.amount),fmt(b.actual),fmt(b.committed),fmt(b.amount-b.actual-b.committed),<div className="flex w-28 items-center gap-2"><ProgressBar value={Math.min(u,100)}/><span>{u}%</span></div>,b.status]})}/></Panel>:<Panel flush title="Budget transfers" subtitle="Transfers require approval and cannot exceed available balance"><RecordTable headers={["Transfer","From","To","Amount","Status"]} badges={[4]} right={[3]} rows={budgetTransfers}/></Panel>}</div>
<BudgetModal open={create} onOpenChange={setCreate}/><BudgetTransferModal open={transfer} onOpenChange={setTransfer}/></FinancePage></AppShell>}
