import {createFileRoute,Link} from "@tanstack/react-router";
import {Building2,ClipboardList,Download,Landmark,Plus,Receipt} from "lucide-react";
import {useState} from "react";
import {AppShell} from "@/components/app-shell";
import {Kpis,Panel,RecordTable,Toolbar,pageMeta} from "@/components/finance/accounting-ui";
import {FinancePage} from "@/components/finance/finance-ui";
import {A} from "@/components/finance/revenue-data";
import {projectCosts} from "@/components/finance/accounting-data";
import {K,allocationBases,bcAudit,bcPolicies,bcReports,bcStatuses,costTypes,facilities,projectFinancing,unitAllocations} from "@/components/finance/borrowing-data";
import {AddCostModal,AddFacilityModal,BcBadge,PolicyNote,bcStore} from "@/components/finance/borrowing-ui";
import {Button,SelectMenu,Tabs} from "@/components/ui/crm";

export const Route=createFileRoute("/finance/borrowing/")({head:()=>pageMeta("Borrowing costs","Track project-related financing costs, capitalization and accounting treatment."),component:Page});

function Page(){
const [tab,setTab]=useState("overview");const [costs,setCosts]=useState(bcStore.costs);const [facs,setFacs]=useState(facilities);const [addF,setAddF]=useState(false);const [addC,setAddC]=useState(false);const [msg,setMsg]=useState("");const [basis,setBasis]=useState(allocationBases[0]??"");
const pendingReview=costs.filter(c=>["Draft","Under Review","Pending Approval"].includes(c.status));
const link=(id:string)=><Link to="/finance/borrowing/costs/$costId" params={{costId:id}} className="font-semibold text-primary">{id}</Link>;
const flink=(id:string)=><Link to="/finance/borrowing/facilities/$facilityId" params={{facilityId:id}} className="font-semibold text-primary">{id}</Link>;
return <AppShell crumbs={["Workspace","Finance ERP","Borrowing costs"]}><FinancePage eyebrow="PROJECT FINANCING" title="Borrowing costs" description="Track project-related financing costs, capitalization and accounting treatment." actions={<div className="flex flex-wrap gap-2"><SelectMenu label="Period: Sep 2026" items={["Sep 2026","Aug 2026","Jul 2026","FY2026"]}/><SelectMenu label="All projects" items={["All projects",...projectFinancing.map(p=>p.project)]}/><Button variant="secondary" onClick={()=>setMsg("Borrowing cost summary queued as Excel (sample — no file generated).")}><Download size={15}/>Export</Button><Button onClick={()=>setAddF(true)}><Plus size={15}/>Add financing facility</Button></div>}>
<div className="mt-5"><Kpis items={[["Total finance cost","AED 8.4M","All facilities · FY2026",<Landmark/>],["Capitalized","AED 6.1M","Added to project cost per policy",<Building2/>],["Expensed","AED 2.3M","Finance cost in P&L",<Receipt/>],["Pending review","AED 620K",`${pendingReview.length} records awaiting Finance`,<ClipboardList/>]]}/></div>
<div className="mt-3"><PolicyNote/></div>
<div className="mt-4"><Tabs value={tab} onValueChange={setTab} items={[{value:"overview",label:"Projects"},{value:"facilities",label:"Facilities"},{value:"costs",label:"Finance costs"},{value:"review",label:"Capitalization review"},{value:"policies",label:"Policies"},{value:"impact",label:"Project cost impact"},{value:"allocation",label:"Unit allocation"},{value:"gl",label:"GL & close"},{value:"reports",label:"Reports"},{value:"audit",label:"Audit"}]}/></div>
{msg&&<p className="mt-3 rounded-md border border-border bg-success-soft p-2 text-xs text-success">{msg}</p>}
<div className="mt-4 space-y-4">
{tab==="overview"&&<Panel flush title="Project financing summary" subtitle="Sample values · Sep 2026"><RecordTable headers={["Project","Financing facility","Finance cost","Capitalized","Expensed","Pending review","Policy","Status"]} right={[2,3,4,5]} rows={projectFinancing.map(p=>[<strong>{p.project}</strong>,flink(p.facility),K(p.cost),K(p.cap),K(p.exp),p.pending?K(p.pending):"—",p.policy,<BcBadge s={p.status}/>])}/></Panel>}
{tab==="facilities"&&<Panel flush title="Financing facilities" subtitle="Project financing cost tracking — not a loan servicing system."><Toolbar placeholder="Search facility, lender or project" filters={[["Status",[...bcStatuses]],["Lender",[...new Set(facilities.map(f=>f.lender))]]]}/><RecordTable headers={["Facility","Name","Lender / provider","Related project","Facility amount","Currency","Start date","Status","Actions"]} right={[4]} rows={facs.map(f=>[flink(f.id),f.name,f.lender,f.projects.length>1?`${f.projects.length} projects`:f.projects[0]?.project,K(f.amount),f.currency,f.start,<BcBadge s={f.status}/>,<Link to="/finance/borrowing/facilities/$facilityId" params={{facilityId:f.id}} className="text-primary">Open</Link>])}/></Panel>}
{tab==="costs"&&<Panel flush title="Finance costs" subtitle="Interest, fees and other financing costs by period" actions={<Button className="m-4 h-8 px-3 text-xs" onClick={()=>setAddC(true)}><Plus size={14}/>Record finance cost</Button>}><Toolbar placeholder="Search reference, facility or source" filters={[["Cost type",costTypes],["Status",[...bcStatuses]]]}/><RecordTable headers={["Reference","Facility","Project","Period","Type","Source","Amount","Capitalized","Expensed","Status"]} right={[6,7,8]} rows={costs.map(c=>[link(c.id),c.facility,c.project,c.period,c.type,`${c.source} · ${c.sourceRef}`,A(c.amount),A(c.capitalized),A(c.expensed),<BcBadge s={c.status}/>])}/></Panel>}
{tab==="review"&&<Panel flush title="Capitalization review · Sep 2026" subtitle="Each record needs a Finance decision and approval before posting. Nothing is capitalized automatically."><RecordTable headers={["Reference","Project","Type","Amount","Policy","Prepared by","Status","Action"]} right={[3]} empty="No finance costs awaiting review." rows={pendingReview.map(c=>[link(c.id),c.project,c.type,A(c.amount),c.policy,c.preparedBy,<BcBadge s={c.status}/>,<Link to="/finance/borrowing/costs/$costId" params={{costId:c.id}} className="text-primary">Review</Link>])}/></Panel>}
{tab==="policies"&&<Panel flush title="Borrowing cost accounting policies" subtitle="Versioned · changes apply from their effective date and never rewrite posted periods. Edit in Settings → Accounting policies."><RecordTable headers={["Policy","Name","Version","Scope","Effective","Eligibility","Capitalization start / end","Allocation basis","Status"]} rows={bcPolicies.map(p=>[p.id,p.name,p.version,p.scope,p.effective,p.eligibility,`${p.start} / ${p.end}`,p.allocation,<BcBadge s={p.status}/>])}/></Panel>}
{tab==="impact"&&<Panel flush title="Capitalized borrowing cost → project cost" subtitle="Capitalized amounts appear once in Project Costing as a separate line; expensed amounts stay in P&L finance cost — never both."><RecordTable headers={["Project","Direct cost","Capitalized borrowing cost","Total project cost","Expensed finance cost (P&L)","Costing"]} right={[1,2,3,4]} rows={projectCosts.map(pc=>{const f=projectFinancing.find(p=>p.project===pc.project);return [pc.project,K(pc.direct),K(f?.cap??0),K(pc.direct+(f?.cap??0)),K(f?.exp??0),<Link to="/finance/costing/$projectId" params={{projectId:pc.id}} className="text-primary">Open costing</Link>]})}/></Panel>}
{tab==="allocation"&&<Panel flush title="Project → unit allocation · Horizon Residences" subtitle={`Capitalized borrowing cost AED 3.1M allocated by: ${basis}. Handover snapshots are preserved; changes create an adjusted version.`} actions={<select className="m-4 h-8 rounded-md border border-input bg-surface px-2 text-xs" value={basis} onChange={e=>{setBasis(e.target.value);setMsg(`Allocation preview recalculated on "${e.target.value}" — submit for approval to apply.`)}}>{allocationBases.map(b=><option key={b}>{b}</option>)}</select>}><RecordTable headers={["Unit","Building","Type","Area","Share","Allocated borrowing cost","Unit status","Handover snapshot"]} right={[4,5]} rows={unitAllocations}/><p className="border-t border-border p-3 text-[11px] text-muted-foreground">Validation: total allocated equals capitalized project cost · no unit allocated twice · unsold units retain allocation in inventory.</p></Panel>}
{tab==="gl"&&<><Panel flush title="General ledger linkage" subtitle="GL remains the accounting source. Each journal references its borrowing cost record; a record can post once — corrections use adjustment, reclassification or reversal."><RecordTable headers={["Record","Journal","Dr","Cr","Amount","GL status"]} right={[4]} rows={costs.map(c=>[link(c.id),c.journal,c.capitalized?"1720 Capitalized borrowing cost":c.expensed?"7110 Finance cost":"—","2210 Accrued interest",A(c.amount),<BcBadge s={c.gl}/>])}/></Panel><Panel flush title="Financial close · Sep 2026" subtitle="Linked to Financial close checklist"><RecordTable headers={["Check","Result","Status"]} badges={[2]} rows={[["Borrowing cost records reviewed",`${pendingReview.length} pending`,pendingReview.length?"Pending review":"Approved"],["Approved borrowing cost journals posted","Aug 2026 complete","Approved"],["Unit allocation approved","Horizon Residences pending","Pending review"]]}/></Panel></>}
{tab==="reports"&&<Panel flush title="Borrowing cost reports" subtitle="Filters: period, project, facility, policy, status, cost type"><RecordTable headers={["Report","Contents","Export"]} rows={bcReports.map(r=>[r[0],r[1],<div className="flex gap-1"><Button variant="secondary" className="h-7 px-2 text-[11px]" onClick={()=>setMsg(`${r[0]} queued as Excel (sample — no file generated).`)}>Excel</Button><Button variant="secondary" className="h-7 px-2 text-[11px]" onClick={()=>setMsg(`${r[0]} queued as PDF (sample — no file generated).`)}>PDF</Button></div>])}/></Panel>}
{tab==="audit"&&<Panel flush title="Borrowing cost audit trail" subtitle="Posted records are protected; history is never overwritten."><RecordTable headers={["When","User","Record","Action","From","To"]} rows={bcAudit}/></Panel>}
</div>
<AddFacilityModal open={addF} onOpenChange={setAddF} onSave={name=>{const id=`FAC-2026-00${facs.length+1}`;setFacs(f=>[...f,{id,name,lender:"—",projects:[{project:"Horizon Residences",share:100}],amount:0,currency:"AED",start:"—",end:"",owner:"You",status:"Draft",reference:"",notes:""}]);setTab("facilities");setMsg(`${id} · ${name} saved as Draft.`)}}/>
<AddCostModal open={addC} onOpenChange={setAddC} onSave={c=>{bcStore.add(c);setCosts(bcStore.costs);setMsg(`${c.id} recorded as Draft — send to Capitalization review when ready.`)}}/>

</FinancePage></AppShell>}
