import {createFileRoute,Link,notFound} from "@tanstack/react-router";
import {useState} from "react";
import {AppShell} from "@/components/app-shell";
import {fmt} from "@/components/finance/accounting-data";
import {AuditPanel,Panel,Placeholder,RecordTable,pageMeta} from "@/components/finance/accounting-ui";
import {ReasonModal} from "@/components/finance/accounting-workflows";
import {FinancePage} from "@/components/finance/finance-ui";
import {budgetLines,budgetRevisions,budgets,expenses} from "@/components/finance/spend-data";
import {InfoGrid} from "@/components/sales/sales-ui";
import {Button,ProgressBar,StatusBadge,Tabs} from "@/components/ui/crm";
export const Route=createFileRoute("/finance/budgets/$budgetId")({loader:({params})=>{const budget=budgets.find(b=>b.id===params.budgetId);if(!budget)throw notFound();return {budget}},head:({loaderData})=>loaderData?pageMeta(`${loaderData.budget.name} · Budget 360`,`Allocation, utilisation, revisions and alerts for ${loaderData.budget.id}.`):{meta:[{title:"Budget not found"},{name:"robots",content:"noindex"}]},notFoundComponent:()=><AppShell><div className="p-8 text-sm">Budget not found. <Link to="/finance/budgets" className="text-primary">Back</Link></div></AppShell>,component:Page});
function Page(){const {budget:b}=Route.useLoaderData();const [tab,setTab]=useState("allocation");const [revise,setRevise]=useState(false);const [status,setStatus]=useState(b.status);const [log,setLog]=useState<string[][]>([]);const avail=b.amount-b.actual-b.committed;const u=b.amount?Math.round((b.actual+b.committed)/b.amount*100):0;
return <AppShell crumbs={["Finance ERP","Budgets",b.id]}><FinancePage eyebrow={`BUDGET 360 · ${b.id} · ${b.version}`} title={b.name} description={`${b.type} · ${b.costCentre} · ${b.project} · Owner: ${b.owner}`} actions={<div className="flex gap-2"><StatusBadge tone={status==="Active"?"success":status==="Over budget"?"danger":"warning"}>{status}</StatusBadge>{status==="Pending approval"?<Button onClick={()=>{setStatus("Active");setLog(l=>[["Just now","Maya Joseph",b.id,"Approved","Pending approval","Active"],...l])}}>Approve budget</Button>:<Button variant="secondary" onClick={()=>setRevise(true)}>Request revision</Button>}</div>}>
<div className="mt-5 grid gap-4 xl:grid-cols-[1fr_340px]"><Panel title="Utilisation"><InfoGrid items={[["Approved budget",fmt(b.amount)],["Actual",fmt(b.actual)],["Committed",fmt(b.committed)],["Available",fmt(avail)],["Utilisation",`${u}%`],["Fiscal year",b.fy]]}/><div className="mt-4"><ProgressBar value={Math.min(u,100)}/></div></Panel>
<Panel title="Alerts">{u>=100?<p className="rounded-md bg-danger-soft p-3 text-xs font-medium text-danger">Budget exceeded by {fmt(-avail)}. New expenses route to Finance Director.</p>:u>=90?<p className="rounded-md bg-warning-soft p-3 text-xs font-medium text-warning">Above 90% threshold. Budget owner notified.</p>:<p className="text-xs text-muted-foreground">No active alerts. Thresholds: 80% notify · 90% warn · 100% block.</p>}</Panel></div>
<div className="mt-4"><Tabs value={tab} onValueChange={setTab} items={[{value:"allocation",label:"Allocation"},{value:"expenses",label:"Linked expenses"},{value:"versions",label:"Revisions & versions"},{value:"audit",label:"Audit"}]}/></div>
<div className="mt-4">{tab==="allocation"&&<Panel flush title="Allocation by GL line"><RecordTable headers={["Line","GL","Budget","Actual","Committed"]} right={[2,3,4]} rows={budgetLines}/></Panel>}
{tab==="expenses"&&<Panel flush title="Linked expenses"><RecordTable headers={["Expense","Date","Vendor","Amount","Status"]} badges={[4]} right={[3]} rows={expenses.filter(e=>e.budgetId===b.id).map(e=>[<Link to="/finance/expenses/$expenseId" params={{expenseId:e.id}} className="text-primary">{e.id}</Link>,e.date,e.vendor,fmt(e.amount),e.status])}/></Panel>}
{tab==="versions"&&<div className="space-y-4"><Placeholder title="Version control">Approved versions are immutable. A revision creates a new version that becomes effective only after approval.</Placeholder><Panel flush title="Revisions"><RecordTable headers={["Version","Date","Requested by","Change","Reason","Status"]} badges={[5]} rows={budgetRevisions}/></Panel></div>}
{tab==="audit"&&<AuditPanel rows={[...log,["12 Aug · 3:10 PM","Ahmed Malik",b.id,"Revision approved","v1","v2"],["02 Jan · 9:00 AM","Maya Joseph",b.id,"Budget created","—","v1"]]}/>}</div>
<ReasonModal open={revise} onOpenChange={setRevise} title="Request budget revision" label="Submit revision" note="Describe the new amount and reason. The current version stays effective until the revision is approved." onConfirm={r=>setLog(l=>[["Just now","Maya Joseph",b.id,`Revision requested — ${r}`,b.version,"Pending"],...l])}/></FinancePage></AppShell>}
