import {createFileRoute,Link} from "@tanstack/react-router";
import {AlertTriangle,CheckCircle2,Clock,GitCompare} from "lucide-react";
import {useState} from "react";
import {AppShell} from "@/components/app-shell";
import {Kpis,Panel,Placeholder,RecordTable,Toolbar,pageMeta} from "@/components/finance/accounting-ui";
import {FinancePage} from "@/components/finance/finance-ui";
import {conflicts,reconRows,scenarios,syncEvents} from "@/components/finance/integration-data";
import {SyncBadge} from "@/components/finance/integration-ui";
import {ProgressBar,Tabs} from "@/components/ui/crm";
export const Route=createFileRoute("/finance/integration/")({head:()=>pageMeta("Integration Monitor","Monitor financial data synchronization between CRM and Finance ERP."),component:Page});
function Page(){const [tab,setTab]=useState("events");const [filter,setFilter]=useState("All");const rows=syncEvents.filter(e=>filter==="All"||e.status===filter);
return <AppShell crumbs={["Workspace","Finance ERP","Integration monitor"]}><FinancePage eyebrow="SYSTEM INTEGRATION" title="CRM ↔ Finance sync" description="Monitor financial data synchronization between CRM and Finance ERP.">
<div className="mt-5"><Kpis items={[["Synced today","1,248","99.2% success rate",<CheckCircle2/>],["Pending","18","Oldest 12 min",<Clock/>],["Failed","6","Retry available",<AlertTriangle/>],["Conflicts","3","Awaiting resolution",<GitCompare/>]]}/></div>
<div className="mt-4 grid gap-4 xl:grid-cols-3">{[["CRM → Finance","Reservations, SPA schedules, EOI, amendments",98],["Finance → CRM","Receipts, allocations, reversals, clearance",100],["Reconciliation","Last run 29 Sep · 6:00 AM · 4 exceptions",94]].map(([t,d,v])=><Panel key={String(t)} title={String(t)} subtitle={String(d)}><div className="flex items-center gap-3"><ProgressBar value={Number(v)}/><strong className="text-xs">{v}%</strong></div></Panel>)}</div>
<div className="mt-4"><Tabs value={tab} onValueChange={setTab} items={[{value:"events",label:"Sync events"},{value:"conflicts",label:`Conflicts (${conflicts.length})`},{value:"recon",label:"Reconciliation"},{value:"qa",label:"Flow validation"}]}/></div>
<div className="mt-4 space-y-4">{tab==="events"&&<Panel flush title="Sync events"><div className="flex flex-wrap gap-2 px-4 pb-3">{["All","Synced","Pending","Processing","Failed","Conflict","Manual Review Required"].map(s=><button key={s} onClick={()=>setFilter(s)} className={`rounded-full border px-3 py-1 text-[11px] ${filter===s?"border-primary bg-primary text-primary-foreground":"border-border text-muted-foreground"}`}>{s}</button>)}</div><Toolbar placeholder="Search customer, CRM or Finance reference"/><RecordTable headers={["Event","Time","Type","Direction","Source ref","Target ref","Customer","Amount","Status"]} rows={rows.map(e=>[<Link to="/finance/integration/events/$eventId" params={{eventId:e.id}} className="font-semibold text-primary">{e.id}</Link>,e.time,e.event,e.direction,e.sourceRef,e.targetRef,e.customer,e.amount,<SyncBadge status={e.status}/>])}/></Panel>}
{tab==="conflicts"&&<Panel flush title="Conflict queue" subtitle="Values differ between CRM and Finance. The authoritative source is suggested for each field."><RecordTable headers={["Conflict","Customer","Field","CRM value","Finance value","Authoritative source","Raised","Status"]} badges={[7]} rows={conflicts.map(c=>[<Link to="/finance/integration/conflicts/$conflictId" params={{conflictId:c.id}} className="font-semibold text-primary">{c.id}</Link>,c.customer,c.field,c.crm,c.finance,c.authority,c.raised,c.status==="Open"?"Pending":c.status])}/></Panel>}
{tab==="recon"&&<><div className="grid gap-2 text-xs sm:grid-cols-4">{[["Matched","3"],["Amount mismatch","1"],["Missing Finance record","1"],["Finance-only record","1"]].map(([l,v])=><div key={l} className="flex justify-between rounded-md border border-border bg-surface px-3 py-2"><span className="text-muted-foreground">{l}</span><strong>{v}</strong></div>)}</div><Panel flush title="CRM ↔ Finance reconciliation" subtitle="Contract value in CRM compared with receivables in Finance"><Toolbar placeholder="Search customer, unit or reference" filters={[["Result",["All","Matched","Amount mismatch","Missing Finance record","Finance-only record"]],["Project",["All projects","Horizon Residences","Green Park","Creek Vista"]]]}/><RecordTable headers={["Customer","Unit","CRM ref","Finance ref","CRM amount","Finance amount","Difference","Result"]} badges={[7]} right={[4,5,6]} rows={reconRows}/></Panel></>}
{tab==="qa"&&<><Placeholder title="End-to-end flow validation">Each scenario traces a CRM event through Finance and back. Customer, unit and amount are compared on both sides; history is retained in the audit trail.</Placeholder><Panel flush title="Test scenarios"><RecordTable headers={["#","Scenario","Trace","Result","Notes"]} badges={[3]} rows={scenarios}/></Panel></>}</div></FinancePage></AppShell>}
