import {createFileRoute,Link,notFound} from "@tanstack/react-router";
import {useState} from "react";
import {AppShell} from "@/components/app-shell";
import {eInvoices} from "@/components/finance/accounting-data";
import {AuditPanel,Panel,Placeholder,pageMeta} from "@/components/finance/accounting-ui";
import {FinancePage} from "@/components/finance/finance-ui";
import {InfoGrid} from "@/components/sales/sales-ui";
import {Button,StatusBadge} from "@/components/ui/crm";
export const Route=createFileRoute("/finance/e-invoicing/$invoiceId")({loader:({params})=>{const inv=eInvoices.find(e=>e[0]===params.invoiceId);if(!inv)throw notFound();return {inv}},head:({loaderData})=>loaderData?pageMeta(`${loaderData.inv[0]} · E-invoice`,`E-invoice for ${loaderData.inv[2]} with source receivable and submission status.`):{meta:[{title:"E-invoice not found"},{name:"robots",content:"noindex"}]},notFoundComponent:()=><AppShell><div className="p-8 text-sm">E-invoice not found. <Link to="/finance/e-invoicing" className="text-primary">Back</Link></div></AppShell>,component:Page});
const steps=["Draft","Validated","Ready for submission","Submitted","Accepted"];
function Page(){const {inv}=Route.useLoaderData();const [status,setStatus]=useState(inv[7]??"Draft");const [log,setLog]=useState<string[][]>([]);const amount=Number((inv[5]??"0").replace(/[^\d]/g,""));const net=Math.round(amount/1.05),vat=amount-net;const tax=inv[6]==="Tax invoice";
const move=(next:string)=>{setLog(l=>[["Just now","Maya Joseph",inv[0]??"","Status change",status,next],...l]);setStatus(next)};const idx=steps.indexOf(status);
return <AppShell crumbs={["Finance ERP","E-Invoicing",inv[0]??""]}><FinancePage eyebrow="E-INVOICE" title={inv[0]??""} description={`${inv[6]} · ${inv[2]}`} actions={<div className="flex gap-2"><StatusBadge tone={status==="Accepted"?"success":status==="Validation failed"?"danger":"warning"}>{status}</StatusBadge>{status==="Draft"&&<Button onClick={()=>move("Ready for submission")}>Validate</Button>}{status==="Validation failed"&&<Button onClick={()=>move("Ready for submission")}>Re-validate</Button>}{status==="Ready for submission"&&<Button onClick={()=>move("Submitted")}>Submit</Button>}</div>}>
<div className="mt-5 flex flex-wrap gap-2">{steps.map((s,i)=><span key={s} className={`rounded-full border px-3 py-1 text-[11px] ${i<=idx?"border-primary bg-primary text-primary-foreground":"border-border text-muted-foreground"}`}>{i+1}. {s}</span>)}</div>
{status==="Validation failed"&&<p className="mt-3 rounded-md bg-danger-soft p-3 text-xs font-medium text-danger">Buyer address line missing (field BT-50). Update the customer record and re-validate.</p>}
<div className="mt-4 grid gap-4 xl:grid-cols-[1fr_380px]"><Panel title="Invoice preview"><div className="rounded-md border border-border p-5 text-xs"><div className="flex justify-between"><div><strong className="text-sm">Green Horizon Developments LLC</strong><p className="text-muted-foreground">TRN 100482910299993 · Dubai, UAE</p></div><div className="text-right"><strong className="text-sm">{tax?"TAX INVOICE":"SIMPLIFIED TAX INVOICE"}</strong><p className="text-muted-foreground">{inv[0]} · {inv[4]}</p></div></div><div className="mt-4 border-t border-border pt-3"><p className="text-muted-foreground">Bill to</p><strong>{inv[2]}</strong>{inv[3]!=="—"&&<p>{inv[3]}</p>}</div><div className="mt-4 space-y-1 border-t border-border pt-3"><div className="flex justify-between"><span>Net amount</span><span>AED {net.toLocaleString()}</span></div><div className="flex justify-between"><span>VAT 5%</span><span>AED {vat.toLocaleString()}</span></div><div className="flex justify-between font-bold"><span>Total</span><span>{inv[5]}</span></div></div></div></Panel>
<div className="space-y-4"><Panel title="Source receivable"><InfoGrid columns="grid-cols-1" items={[["AR reference",inv[1]??""],["Customer",inv[2]??""],["Amount",inv[5]??""]]}/>{inv[1]==="AR-2026-01798"?null:<Link to="/finance/receivables/$receivableId" params={{receivableId:inv[1]??""}} className="mt-3 inline-block text-xs font-medium text-primary">Open receivable</Link>}</Panel><Placeholder title="Submission architecture">Generate → validate (schema & business rules) → submit via accredited provider → acceptance / rejection callback. Accepted e-invoices are immutable; corrections use credit notes.</Placeholder></div></div>
<div className="mt-4"><AuditPanel rows={[...log,[inv[4]??"","System",inv[0]??"","Generated from AR","—","Draft"]]}/></div></FinancePage></AppShell>}
