import {createFileRoute,Link,notFound} from "@tanstack/react-router";
import {useState} from "react";
import {AppShell} from "@/components/app-shell";
import {fmt} from "@/components/finance/accounting-data";
import {AuditPanel,Panel,RecordTable,pageMeta} from "@/components/finance/accounting-ui";
import {ReasonModal} from "@/components/finance/accounting-workflows";
import {FinancePage} from "@/components/finance/finance-ui";
import {expenses,reimbursements} from "@/components/finance/spend-data";
import {PaymentModal} from "@/components/finance/spend-workflows";
import {InfoGrid} from "@/components/sales/sales-ui";
import {Button,ProgressBar,StatusBadge} from "@/components/ui/crm";
export const Route=createFileRoute("/finance/reimbursements/$reimbursementId")({loader:({params})=>{const claim=reimbursements.find(r=>r.id===params.reimbursementId);if(!claim)throw notFound();return {claim}},head:({loaderData})=>loaderData?pageMeta(`${loaderData.claim.id} · Reimbursement`,`Reimbursement claim for ${loaderData.claim.employee} with approval and payment history.`):{meta:[{title:"Claim not found"},{name:"robots",content:"noindex"}]},notFoundComponent:()=><AppShell><div className="p-8 text-sm">Claim not found. <Link to="/finance/reimbursements" className="text-primary">Back</Link></div></AppShell>,component:Page});
function Page(){const {claim:r}=Route.useLoaderData();const [paid,setPaid]=useState(r.paid);const [status,setStatus]=useState(r.status);const [pay,setPay]=useState(false);const [reject,setReject]=useState(false);const [payments,setPayments]=useState<string[][]>(r.paid?[["PAY-RMB-0091","15 Sep 2026",fmt(r.paid),r.method]]:[]);const [log,setLog]=useState<string[][]>([]);const out=r.amount-paid;
const record=(a:number)=>{const np=paid+a;const ns=np>=r.amount?"Paid":"Partially paid";setPayments(p=>[[`PAY-RMB-0${100+p.length}`,"29 Sep 2026",fmt(a),r.method],...p]);setLog(l=>[["Just now","Maya Joseph",r.id,`Payment ${fmt(a)}`,status,ns],...l]);setPaid(np);setStatus(ns)};
return <AppShell crumbs={["Finance ERP","Reimbursements",r.id]}><FinancePage eyebrow="REIMBURSEMENT CLAIM" title={r.id} description={`${r.employee} · ${r.department} · submitted ${r.submitted}`} actions={<div className="flex gap-2"><StatusBadge tone={status==="Paid"?"success":status==="Rejected"?"danger":"warning"}>{status}</StatusBadge>{status==="Pending approval"&&<><Button variant="secondary" onClick={()=>setReject(true)}>Reject</Button><Button onClick={()=>{setLog(l=>[["Just now","Maya Joseph",r.id,"Approved",status,"Approved"],...l]);setStatus("Approved")}}>Approve</Button></>}{(status==="Approved"||status==="Partially paid")&&<Button onClick={()=>setPay(true)}>Record payment</Button>}</div>}>
<div className="mt-5"><Panel title="Payment position"><InfoGrid items={[["Claim amount",fmt(r.amount)],["Paid",fmt(paid)],["Outstanding",fmt(out)],["Method",r.method]]}/><div className="mt-4"><ProgressBar value={paid/r.amount*100}/></div></Panel></div>
<div className="mt-4 grid gap-4 xl:grid-cols-2"><Panel flush title="Included expenses"><RecordTable headers={["Expense","Category","Amount"]} right={[2]} rows={r.expenses.map(id=>{const e=expenses.find(x=>x.id===id);return [e?<Link to="/finance/expenses/$expenseId" params={{expenseId:id}} className="text-primary">{id}</Link>:id,e?.category??"Site expense",e?fmt(e.amount):fmt(r.amount/r.expenses.length)]})}/></Panel><Panel flush title="Payment history"><RecordTable headers={["Payment","Date","Amount","Method"]} right={[2]} rows={payments} empty="No payments yet."/></Panel></div>
<div className="mt-4"><AuditPanel rows={[...log,[r.submitted,r.employee,r.id,"Submitted","Draft","Pending approval"]]}/></div>
<PaymentModal open={pay} onOpenChange={setPay} outstanding={out} onPay={record}/><ReasonModal open={reject} onOpenChange={setReject} title="Reject claim" label="Reject" onConfirm={x=>{setLog(l=>[["Just now","Maya Joseph",r.id,`Rejected — ${x}`,status,"Rejected"],...l]);setStatus("Rejected")}}/></FinancePage></AppShell>}
