import {createFileRoute,Link} from "@tanstack/react-router";
import {ArrowLeftRight,Banknote,Landmark,Scale} from "lucide-react";
import {useState} from "react";
import {AppShell} from "@/components/app-shell";
import {bankAccounts,bankTransactions,cashAccounts,fmt,reconciliations} from "@/components/finance/accounting-data";
import {Kpis,Panel,RecordTable,Toolbar,pageMeta} from "@/components/finance/accounting-ui";
import {TransferModal} from "@/components/finance/accounting-workflows";
import {FinancePage} from "@/components/finance/finance-ui";
import {Button,ProgressBar,StatusBadge,Tabs} from "@/components/ui/crm";
export const Route=createFileRoute("/finance/cash-bank/")({head:()=>pageMeta("Cash & Bank","Bank accounts, cash balances, transactions, internal transfers and bank reconciliation."),component:Page});
function Page(){const [tab,setTab]=useState("overview");const [transfer,setTransfer]=useState(false);const [matched,setMatched]=useState<string[]>([]);const total=bankAccounts.reduce((s,b)=>s+b.book,0);
const txRows=bankTransactions.map(t=>[t[0],t[1],t[2],t[3],t[4],t[5],t[6],t[7]&&t[7]!=="—"?<Link to="/finance/ledger/journals/$journalId" params={{journalId:t[7]}} className="font-medium text-primary">{t[7]}</Link>:"—",matched.includes(t[0]??"")?"Matched":t[8]??""]);
return <AppShell crumbs={["Workspace","Finance ERP","Cash & bank"]}><FinancePage eyebrow="CASH & BANK" title="Cash & bank" description="Bank and cash positions, transactions, transfers and reconciliation linked to the general ledger." actions={<Button onClick={()=>setTransfer(true)}><ArrowLeftRight size={15}/>Internal transfer</Button>}>
<div className="mt-5"><Kpis items={[["Total bank balance",`AED ${(total/1e6).toFixed(1)}M`,`${bankAccounts.length} bank accounts`,<Landmark/>],["Escrow balance","AED 70.0M","2 project escrow accounts",<Landmark/>],["Cash on hand","AED 33,290","3 petty cash floats",<Banknote/>],["Unreconciled items","2","AED 51,850 to review",<Scale/>]]}/></div>
<div className="mt-4"><Tabs value={tab} onValueChange={setTab} items={[{value:"overview",label:"Bank accounts"},{value:"tx",label:"Transactions"},{value:"cash",label:"Cash accounts"},{value:"recon",label:"Reconciliation"}]}/></div>
<div className="mt-4 space-y-4">
{tab==="overview"&&<Panel flush title="Bank accounts" subtitle="Bank numbers are masked · reveal requires Finance permission"><Toolbar placeholder="Search account, bank or GL" filters={[["Type",["All types","Current","Escrow"]],["Project",["All projects","Horizon Residences","Green Park","Corporate"]]]}/><RecordTable headers={["Account","Bank","Number","Type","Currency","Linked GL","Book balance","Statement","Last reconciled","Status"]} badges={[9]} right={[6,7]} rows={bankAccounts.map(b=>[<Link to="/finance/cash-bank/$accountId" params={{accountId:b.id}} className="font-semibold text-primary">{b.name}</Link>,b.bank,b.masked,b.type,b.currency,b.gl,fmt(b.book),fmt(b.statement),b.lastRecon,b.status])}/></Panel>}
{tab==="tx"&&<Panel flush title="Bank transactions" subtitle="Every transaction references its source document and journal"><Toolbar placeholder="Search description, reference or journal" filters={[["Account",["All accounts",...bankAccounts.map(b=>b.id)]],["Status",["All","Matched","Unmatched"]]]}/><RecordTable headers={["Transaction","Date","Account","Description","Credit","Debit","Source","Journal","Status"]} badges={[8]} right={[4,5]} rows={txRows}/></Panel>}
{tab==="cash"&&<Panel flush title="Cash accounts" subtitle="Petty cash and site floats"><RecordTable headers={["ID","Name","Custodian","Float limit","Balance","Linked GL","Status"]} badges={[6]} right={[3,4]} rows={cashAccounts}/></Panel>}
{tab==="recon"&&<><div className="grid gap-4 xl:grid-cols-3">{reconciliations.map(r=><Panel key={r[0]} title={r[1]??""} subtitle={`${r[0]} · ${r[2]}`} actions={<StatusBadge tone={r[6]==="Completed"?"success":"warning"}>{r[6]}</StatusBadge>}><div className="space-y-2 text-xs"><div className="flex justify-between"><span>Statement balance</span><strong>{r[3]}</strong></div><div className="flex justify-between"><span>Book balance</span><strong>{r[4]}</strong></div><div className="flex justify-between"><span>Difference</span><strong className={r[5]==="AED 0"?"text-success":"text-danger"}>{r[5]}</strong></div><ProgressBar value={r[6]==="Completed"?100:r[6]==="Pending review"?90:64}/></div></Panel>)}</div>
<Panel flush title="Match statement lines — Operating account, Sep 2026" subtitle="Select unmatched statement lines to match against book entries"><RecordTable headers={["Transaction","Date","Description","Amount","Status","Action"]} badges={[4]} rows={bankTransactions.filter(t=>t[2]==="BNK-001"||t[8]==="Unmatched").map(t=>{const m=matched.includes(t[0]??"")||t[8]==="Matched";return [t[0],t[1],t[3],t[4]!=="—"?`+${t[4]}`:`-${t[5]}`,m?"Matched":"Unmatched",m?"—":<Button variant="secondary" className="h-7 px-2 text-[11px]" onClick={()=>setMatched(x=>[...x,t[0]??""])}>Match / create entry</Button>]})}/></Panel></>}
</div><TransferModal open={transfer} onOpenChange={setTransfer}/></FinancePage></AppShell>}
