import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { AppShell } from "@/components/app-shell";
import { HandoverNavigation } from "@/components/handover/handover-ui";
import { AcknowledgementModal, GenerateKeyDocumentModal } from "@/components/handover/handover-workflows";
import { InfoGrid } from "@/components/sales/sales-ui";
import { Button, DashboardCard, StatusBadge } from "@/components/ui/crm";
export const Route=createFileRoute("/handover/documents/$documentId")({head:({params})=>({meta:[{title:`${params.documentId} Key Handover Document | Green Horizon CRM`},{name:"description",content:"Key handover document preview and acknowledgement status."},{property:"og:title",content:`${params.documentId} Key Handover Document | Green Horizon CRM`},{property:"og:description",content:"Key handover document preview and acknowledgement status."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Preview});
function Preview(){const {documentId}=Route.useParams();const [generate,setGenerate]=useState(false);const [ack,setAck]=useState(false);return <AppShell crumbs={["Workspace","Handover","Document",documentId]}><div className="mx-auto max-w-[1100px] p-4 md:p-6"><HandoverNavigation/><header className="flex flex-col gap-4 xl:flex-row xl:justify-between"><div><p className="text-xs font-semibold text-muted-foreground">Key handover document preview</p><h1>{documentId}</h1><p className="text-sm text-muted-foreground">Key Handover Standard · Version 1</p></div><div className="flex flex-wrap gap-2"><Button variant="secondary">Back</Button><Button variant="secondary" onClick={()=>setGenerate(true)}>Generate</Button><Button onClick={()=>setAck(true)}>Send for acknowledgement</Button></div></header><DashboardCard className="mx-auto mt-5 max-w-[760px] p-6 md:p-10"><div className="flex justify-between"><div><p className="text-xs font-semibold uppercase text-muted-foreground">Green Horizon Developments</p><h2 className="mt-2 text-xl font-bold">KEY HANDOVER DOCUMENT</h2></div><StatusBadge tone="neutral">Draft</StatusBadge></div><div className="mt-8"><InfoGrid columns="sm:grid-cols-2" items={[["Document ID",documentId],["Template","Key Handover Standard"],["Version","Version 1"],["Customer","Sarah Ahmed · Omar Ahmed"],["Project / Unit","Horizon Residences · A-1204"],["Generated date","04 Oct 2026"],["Handover officer","Layla Noor"],["Checklist","8 configured items"]]}/></div><div className="mt-8 border-t border-border pt-6 text-sm text-muted-foreground">Configured key and access-item quantities, checklist confirmation, and purchaser acknowledgement appear in the generated document.</div></DashboardCard><GenerateKeyDocumentModal open={generate} onOpenChange={setGenerate}/><AcknowledgementModal open={ack} onOpenChange={setAck}/></div></AppShell>}
