import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { AppShell } from "@/components/app-shell";
import { HandoverNavigation } from "@/components/handover/handover-ui";
import { NoticeModal } from "@/components/handover/handover-workflows";
import { InfoGrid } from "@/components/sales/sales-ui";
import { Button, DashboardCard, StatusBadge } from "@/components/ui/crm";
export const Route=createFileRoute("/handover/notices/$noticeId")({head:({params})=>({meta:[{title:`${params.noticeId} Handover Notice | Green Horizon CRM`},{name:"description",content:"Handover notice preview, version and delivery status."},{property:"og:title",content:`${params.noticeId} Handover Notice | Green Horizon CRM`},{property:"og:description",content:"Handover notice preview, version and delivery status."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Preview});
function Preview(){const {noticeId}=Route.useParams();const [share,setShare]=useState(false);return <AppShell crumbs={["Workspace","Handover","Notice",noticeId]}><div className="mx-auto max-w-[1100px] p-4 md:p-6"><HandoverNavigation/><header className="flex flex-col gap-4 xl:flex-row xl:justify-between"><div><p className="text-xs font-semibold text-muted-foreground">Handover notice preview</p><h1>{noticeId}</h1><p className="text-sm text-muted-foreground">Standard Handover Notice · v3.1</p></div><div className="flex gap-2"><Button variant="secondary">Back</Button><Button onClick={()=>setShare(true)}>Send handover notice</Button></div></header><DashboardCard className="mx-auto mt-5 max-w-[760px] p-6 md:p-10"><div className="flex justify-between"><div><p className="text-xs font-semibold uppercase text-muted-foreground">Green Horizon Developments</p><h2 className="mt-2 text-xl font-bold">HANDOVER NOTICE</h2></div><StatusBadge tone="info">Generated</StatusBadge></div><div className="mt-8"><InfoGrid columns="sm:grid-cols-2" items={[["Notice ID",noticeId],["Customer","Sarah Ahmed · Omar Ahmed"],["Project / Unit","Horizon Residences · A-1204"],["Handover reference","HND-2026-00182"],["Generated date","26 Sep 2026"],["Template","Standard Handover Notice"],["Version","v3.1"],["Contact","Handover Team"]]}/></div><p className="mt-8 border-t border-border pt-6 text-sm leading-6 text-muted-foreground">This approved-template notice confirms that the property delivery process is ready to proceed to the configured appointment and snagging stages. Appointment instructions will be shared separately when scheduled.</p></DashboardCard><NoticeModal open={share} onOpenChange={setShare} mode="share"/></div></AppShell>}
