import { createFileRoute } from "@tanstack/react-router";
import { Download, Send, Upload } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { reportVersions, snagIssues } from "@/components/handover/handover-data";
import { HandoverNavigation } from "@/components/handover/handover-ui";
import { InfoGrid, SimpleTable } from "@/components/sales/sales-ui";
import { Button, DashboardCard, StatusBadge } from "@/components/ui/crm";
export const Route=createFileRoute("/handover/inspections/$inspectionId/report")({head:({params})=>({meta:[{title:`${params.inspectionId} Snagging Report | Green Horizon CRM`},{name:"description",content:"Versioned snagging report, issue evidence and sharing status."},{property:"og:title",content:`${params.inspectionId} Snagging Report | Green Horizon CRM`},{property:"og:description",content:"Versioned snagging report, issue evidence and sharing status."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Report});
function Report(){const {inspectionId}=Route.useParams();return <AppShell crumbs={["Workspace","Handover","Snagging report",inspectionId]}><div className="mx-auto max-w-[1300px] p-4 md:p-6"><HandoverNavigation/><header className="flex flex-col gap-4 xl:flex-row xl:justify-between"><div><p className="text-xs font-semibold text-muted-foreground">Snagging report</p><h1>{inspectionId}</h1><p className="text-sm text-muted-foreground">Horizon Residences · A-1204 · Sarah Ahmed</p></div><div className="flex flex-wrap gap-2"><Button variant="secondary"><Upload size={15}/>Upload report</Button><Button variant="secondary"><Download size={15}/>Download</Button><Button><Send size={15}/>Send report</Button></div></header><DashboardCard className="mt-5 p-5"><div className="flex justify-between"><h2 className="text-lg font-bold">Report summary</h2><StatusBadge tone="info">Viewed</StatusBadge></div><div className="mt-4"><InfoGrid items={[["Inspection reference",inspectionId],["Customer","Sarah Ahmed"],["Unit","A-1204"],["Inspection date","28 Sep 2026"],["Inspector","Handover Team"],["Total issues","12"],["Open","3"],["Current version","Version 2"]]}/></div></DashboardCard><DashboardCard className="mt-4 overflow-hidden"><div className="p-4"><h2 className="text-lg font-bold">Issue details and evidence</h2></div><SimpleTable headers={["Issue","Category","Severity","Description","Evidence","Status"]} rows={snagIssues.map(i=>[i.title,i.category,i.severity,i.description,i.evidence,i.status])} badges={[2,5]}/></DashboardCard><DashboardCard className="mt-4 overflow-hidden"><div className="p-4"><h2 className="text-lg font-bold">Report versions</h2><p className="text-xs text-muted-foreground">Updated reports never overwrite prior versions.</p></div><SimpleTable headers={["Version","Purpose","Date","Status","Actions"]} rows={reportVersions} badges={[3]}/></DashboardCard></div></AppShell>}
