import { createFileRoute, Link } from "@tanstack/react-router";
import { Download, Plus, Search } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { handoverCases } from "@/components/handover/handover-data";
import { HandoverNavigation, HandoverStatusBadge } from "@/components/handover/handover-ui";
import { Button, DashboardCard, Input, SelectMenu } from "@/components/ui/crm";
export const Route=createFileRoute("/handover/cases")({head:()=>({meta:[{title:"Handover Cases | Green Horizon CRM"},{name:"description",content:"Track handover readiness and customer delivery progress."},{property:"og:title",content:"Handover Cases | Green Horizon CRM"},{property:"og:description",content:"Track handover readiness and customer delivery progress."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Cases});
const quick=["All","Eligibility pending","Ready","Notice pending","Appointment scheduled","Snagging","Rectification","Ready for final handover","Completed","On hold"];
function Cases(){return <AppShell crumbs={["Workspace","Handover","Cases"]}><div className="mx-auto max-w-[1540px] p-4 md:p-6"><HandoverNavigation/><header className="flex flex-col gap-4 xl:flex-row xl:justify-between"><div><h1>Handover cases</h1><p className="text-sm text-muted-foreground">Track handover readiness and customer delivery progress.</p></div><div className="flex gap-2"><Button variant="secondary"><Download size={15}/>Export</Button><Link to="/handover/create"><Button><Plus size={15}/>Initiate handover</Button></Link></div></header><DashboardCard className="mt-5 p-4"><div className="grid gap-2 xl:grid-cols-[minmax(260px,1fr)_repeat(4,auto)]"><label className="relative"><Search size={15} className="absolute left-3 top-3.5 text-muted-foreground"/><Input className="pl-9" placeholder="Search customer, unit, project, SPA or handover ID"/></label><SelectMenu label="Handover status" items={quick}/><SelectMenu label="Project" items={["All projects","Horizon Residences","Green Park","Creek Vista"]}/><SelectMenu label="Finance clearance" items={["All","Cleared","Pending"]}/><SelectMenu label="More filters" items={["Unit","Customer","Snagging status","Appointment status","Handover owner","Date range"]}/></div><div className="mt-3 flex gap-1 overflow-x-auto">{quick.map((q,i)=><Button key={q} variant={i===0?"primary":"ghost"} className="h-8 shrink-0 px-3 text-xs">{q}</Button>)}</div></DashboardCard><DashboardCard className="mt-4 overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[1120px] text-left text-xs"><thead className="bg-muted text-muted-foreground"><tr>{["Handover","Customer","Project / Unit","Finance","Snagging","Appointment","Status","Owner","Updated","Actions"].map(h=><th key={h} className="p-3 font-medium">{h}</th>)}</tr></thead><tbody>{handoverCases.map(r=><tr key={r.id} className="border-b border-border hover:bg-muted/40"><td className="p-3"><Link to="/handover/$handoverId" params={{handoverId:r.id}} className="font-semibold text-primary">{r.id}</Link></td><td className="p-3 font-medium">{r.customer}</td><td className="p-3">{r.project}<span className="block text-muted-foreground">{r.unit}</span></td><td className="p-3"><HandoverStatusBadge status={r.finance}/></td><td className="p-3"><HandoverStatusBadge status={r.snagging}/></td><td className="p-3">{r.appointment}</td><td className="p-3"><HandoverStatusBadge status={r.status}/></td><td className="p-3">{r.owner}</td><td className="p-3">{r.updated}</td><td className="p-3"><Link to="/handover/$handoverId" params={{handoverId:r.id}} className="font-semibold text-primary">Open</Link></td></tr>)}</tbody></table></div></DashboardCard></div></AppShell>}
