import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { AppShell } from "@/components/app-shell";
import { appointments } from "@/components/handover/handover-data";
import { HandoverNavigation, HandoverStatusBadge } from "@/components/handover/handover-ui";
import { ScheduleAppointmentModal } from "@/components/handover/handover-workflows";
import { InfoGrid, SimpleTable } from "@/components/sales/sales-ui";
import { Button, DashboardCard } from "@/components/ui/crm";
export const Route=createFileRoute("/handover/appointments/$appointmentId")({head:({params})=>({meta:[{title:`${params.appointmentId} Appointment | Green Horizon CRM`},{name:"description",content:"Handover appointment details, attendance and communication."},{property:"og:title",content:`${params.appointmentId} Appointment | Green Horizon CRM`},{property:"og:description",content:"Handover appointment details, attendance and communication."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Detail});
function Detail(){const {appointmentId}=Route.useParams();const a=appointments.find(x=>x.id===appointmentId)??appointments[0];if(!a)return null;const [reschedule,setReschedule]=useState(false);return <AppShell crumbs={["Workspace","Handover","Appointments",a.id]}><div className="mx-auto max-w-[1200px] p-4 md:p-6"><HandoverNavigation/><header><p className="text-xs font-semibold text-muted-foreground">Appointment</p><div className="flex items-center gap-2"><h1>{a.type}</h1><HandoverStatusBadge status={a.status}/></div><p className="text-sm text-muted-foreground">{a.id} · {a.customer} · {a.unit}</p></header><div className="mt-5 grid gap-4 xl:grid-cols-[1.45fr_1fr]"><DashboardCard className="p-5"><h2 className="text-lg font-bold">Appointment details</h2><div className="mt-4"><InfoGrid items={[["Type",a.type],["Customer",a.customer],["Project / Unit",`${a.project} · ${a.unit}`],["Date",a.date],["Time",a.time],["Duration",a.duration],["Assigned team",a.team],["Status",a.status],["Customer confirmation",a.confirmation],["Location",a.location]]}/></div><div className="mt-4 flex gap-2"><Button variant="secondary" onClick={()=>setReschedule(true)}>Reschedule</Button><Button variant="secondary">Cancel appointment</Button><Button>Mark completed</Button></div></DashboardCard><DashboardCard className="p-5"><h2 className="text-lg font-bold">Appointment notes</h2><p className="mt-3 text-sm">Customer requested building access instructions with the reminder.</p><Link to="/handover/$handoverId" params={{handoverId:a.handoverId}} className="mt-4 inline-block text-sm font-semibold text-primary">Open handover case</Link></DashboardCard></div><DashboardCard className="mt-4 overflow-hidden"><SimpleTable headers={["Communication","Channel","Status","Date"]} rows={[["Appointment invitation","Email","Delivered","27 Sep · 9:00 AM"],["Customer confirmation","Email","Confirmed","27 Sep · 10:15 AM"],["Appointment reminder","WhatsApp","Delivered","27 Sep · 5:00 PM"]]} badges={[2]}/></DashboardCard><ScheduleAppointmentModal open={reschedule} onOpenChange={setReschedule} type={a.type}/></div></AppShell>}
