import { createFileRoute } from "@tanstack/react-router";
import { Check, ClipboardCheck, SearchCheck, Wrench } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { completedHandovers, projectHandover } from "@/components/handover/handover-data";
import { HandoverNavigation } from "@/components/handover/handover-ui";
import { CompactMetrics, SimpleTable } from "@/components/sales/sales-ui";
import { Button, DashboardCard, SelectMenu } from "@/components/ui/crm";
export const Route=createFileRoute("/handover/reports")({head:()=>({meta:[{title:"Handover Reports | Green Horizon CRM"},{name:"description",content:"Operational handover, appointment, snagging and completion reports."},{property:"og:title",content:"Handover Reports | Green Horizon CRM"},{property:"og:description",content:"Operational handover, appointment, snagging and completion reports."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Reports});
function Reports(){return <AppShell crumbs={["Workspace","Handover","Reports"]}><div className="mx-auto max-w-[1540px] p-4 md:p-6"><HandoverNavigation/><header className="flex flex-col gap-4 xl:flex-row xl:justify-between"><div><h1>Handover reports</h1><p className="text-sm text-muted-foreground">Operational property delivery and snagging views.</p></div><Button variant="secondary">Export report</Button></header><DashboardCard className="mt-5 p-4"><div className="flex flex-wrap gap-2"><SelectMenu label="Handover status report" items={["Handover status report","Upcoming appointments","Snagging status","Open snag issues","Rectification report","Completed handovers","Project-wise handover report"]}/><SelectMenu label="All projects" items={["Horizon Residences","Green Park","Creek Vista"]}/><SelectMenu label="All statuses" items={["All","Ready","Snagging","Rectification","Completed"]}/><SelectMenu label="Appointment date" items={["All dates","Next 7 days","This month"]}/><SelectMenu label="Assigned officer" items={["All officers","Layla Noor","Ahmed Malik"]}/></div></DashboardCard><div className="mt-4"><CompactMetrics items={[{label:"Inspections completed",value:"24",detail:"This month",icon:<SearchCheck/>},{label:"Open issues",value:"19",detail:"Across active cases",icon:<Wrench/>},{label:"Under rectification",value:"11",detail:"Assigned",icon:<ClipboardCheck/>},{label:"Closed issues",value:"68",detail:"This month",icon:<Check/>}]}/></div><div className="mt-4 grid gap-4"><DashboardCard className="overflow-hidden"><div className="p-4"><h2 className="text-lg font-bold">Project-wise handover</h2></div><SimpleTable headers={["Project","Ready","Snagging","Rectification","Final appointments","Completed"]} rows={projectHandover}/></DashboardCard><DashboardCard className="overflow-hidden"><div className="p-4"><h2 className="text-lg font-bold">Completed handovers</h2></div><SimpleTable headers={["Handover ID","Customer","Project / Unit","Handover date","Finance","Snagging","Acknowledgement","Officer"]} rows={completedHandovers} badges={[4,5,6]}/></DashboardCard></div></div></AppShell>}
