import { createFileRoute, Link } from "@tanstack/react-router";
import { AlertTriangle, CalendarDays, Download, KeyRound, Plus, Wrench } from "lucide-react";
import type { ReactNode } from "react";
import { AppShell } from "@/components/app-shell";
import { handoverCases, projectHandover } from "@/components/handover/handover-data";
import { HandoverNavigation, HandoverStatusBadge, Pipeline } from "@/components/handover/handover-ui";
import { CompactMetrics, SimpleTable } from "@/components/sales/sales-ui";
import { Button, DashboardCard, MetricCard, StatusBadge } from "@/components/ui/crm";
export const Route=createFileRoute("/handover/")({head:()=>({meta:[{title:"Handover Overview | Green Horizon CRM"},{name:"description",content:"Property readiness, snagging, appointments and key handover operations."},{property:"og:title",content:"Handover Overview | Green Horizon CRM"},{property:"og:description",content:"Property readiness, snagging, appointments and key handover operations."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:HandoverOverview});
function HandoverOverview(){return <AppShell crumbs={["Workspace","Handover"]}><div className="mx-auto max-w-[1540px] p-4 md:p-6"><HandoverNavigation/><header className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-semibold uppercase text-muted-foreground">Property delivery</p><h1>Handover</h1><p className="text-sm text-muted-foreground">Manage property readiness, snagging, appointments and key handover.</p></div><div className="flex gap-2"><Button variant="secondary"><Download size={15}/>Export</Button><Link to="/handover/create"><Button><Plus size={15}/>Schedule handover</Button></Link></div></header><DashboardCard className="mt-5 grid overflow-hidden sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Ready for handover" value="38" detail="Eligibility completed" icon={<KeyRound/>}/><Kpi label="Appointments scheduled" value="21" detail="Next 7 days" icon={<CalendarDays/>}/><Kpi label="Snagging in progress" value="14" detail="6 awaiting rectification" icon={<Wrench/>}/><Kpi label="Completed handovers" value="86" detail="This month" icon={<KeyRound/>} last/></DashboardCard><div className="mt-3 flex justify-end"><StatusBadge tone="warning">Finance clearance pending · 9</StatusBadge></div><div className="mt-4 grid gap-4 xl:grid-cols-[1.55fr_1fr]"><Pipeline/><Attention/></div><div className="mt-4 grid gap-4 xl:grid-cols-[1.55fr_1fr]"><DashboardCard className="overflow-hidden"><div className="flex items-center justify-between p-4"><div><h2 className="text-lg font-bold">Recent handover cases</h2><p className="text-xs text-muted-foreground">Current delivery workload</p></div><Link to="/handover/cases" className="text-sm font-semibold text-primary">View all</Link></div><SimpleTable headers={["Handover","Customer","Project / Unit","Finance","Snagging","Status","Owner"]} rows={handoverCases.map(r=>[r.id,r.customer,`${r.project} · ${r.unit}`,r.finance,r.snagging,r.status,r.owner])} badges={[3,4,5]}/></DashboardCard><DashboardCard className="overflow-hidden"><div className="p-4"><h2 className="text-lg font-bold">Project-wise handover</h2></div><SimpleTable headers={["Project","Ready","Snagging","Rectification","Final","Completed"]} rows={projectHandover}/></DashboardCard></div></div></AppShell>}
function Kpi({label,value,detail,icon,last}:{label:string;value:string;detail:string;icon:ReactNode;last?:boolean}){return <MetricCard className={`${last?"":"border-b border-border sm:border-r xl:border-b-0"} py-4`}><div className="flex justify-between"><div><span className="text-xs text-muted-foreground">{label}</span><strong className="mt-1 block text-2xl">{value}</strong><span className="text-[11px] text-muted-foreground">{detail}</span></div><span className="text-muted-foreground [&>svg]:size-5">{icon}</span></div></MetricCard>}
function Attention(){const rows=[{count:"9",text:"cases awaiting finance clearance",id:"HND-2026-00181"},{count:"6",text:"snagging reports awaiting rectification",id:"HND-2026-00182"},{count:"4",text:"appointments tomorrow",id:"HND-2026-00182"},{count:"3",text:"rectification deadlines approaching",id:"HND-2026-00182"},{count:"2",text:"customer acknowledgements pending",id:"HND-2026-00164"}];return <DashboardCard className="p-5"><h2 className="text-lg font-bold">Attention center</h2><div className="mt-3 divide-y divide-border">{rows.map(row=><Link key={row.text} to="/handover/$handoverId" params={{handoverId:row.id}} className="flex items-center gap-3 py-3"><span className="grid size-7 place-items-center rounded-md bg-warning-soft text-xs font-bold text-warning">{row.count}</span><span className="flex-1 text-xs">{row.text}</span><AlertTriangle size={14} className="text-muted-foreground"/></Link>)}</div></DashboardCard>}
