import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { AppShell } from "@/components/app-shell";
import { snagIssues } from "@/components/handover/handover-data";
import { HandoverNavigation, HandoverStatusBadge } from "@/components/handover/handover-ui";
import { ReinspectionModal } from "@/components/handover/handover-workflows";
import { InfoGrid, SimpleTable } from "@/components/sales/sales-ui";
import { Button, DashboardCard, FormField, Input, Textarea } from "@/components/ui/crm";
export const Route=createFileRoute("/handover/issues/$issueId")({head:({params})=>({meta:[{title:`${params.issueId} Snag Issue | Green Horizon CRM`},{name:"description",content:"Snag issue evidence, assignment, rectification and reinspection."},{property:"og:title",content:`${params.issueId} Snag Issue | Green Horizon CRM`},{property:"og:description",content:"Snag issue evidence, assignment, rectification and reinspection."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Issue});
function Issue(){const {issueId}=Route.useParams();const issue=snagIssues.find(x=>x.id===issueId)??snagIssues[0];if(!issue)return null;const [reinspect,setReinspect]=useState(false);return <AppShell crumbs={["Workspace","Handover","Snag issue",issue.id]}><div className="mx-auto max-w-[1200px] p-4 md:p-6"><HandoverNavigation/><header><p className="text-xs font-semibold text-muted-foreground">Snag issue</p><div className="flex items-center gap-2"><h1>{issue.title}</h1><HandoverStatusBadge status={issue.status}/></div><p className="text-sm text-muted-foreground">{issue.id} · SNG-2026-00218 · Unit A-1204</p></header><div className="mt-5 grid gap-4 xl:grid-cols-[1.45fr_1fr]"><DashboardCard className="p-5"><h2 className="text-lg font-bold">Issue detail</h2><div className="mt-4"><InfoGrid items={[["Category",issue.category],["Severity",issue.severity],["Location",issue.location],["Assigned team",issue.team],["Target date",issue.target],["Status",issue.status],["Description",issue.description],["Original evidence",issue.evidence]]}/></div>{issue.overdue&&<div className="mt-4 rounded-md bg-danger-soft p-3 text-xs text-danger">Rectification overdue · {issue.overdue}</div>}</DashboardCard><DashboardCard className="p-5"><h2 className="text-lg font-bold">Rectification update</h2><div className="mt-4 grid gap-3"><FormField label="Assigned team"><Input defaultValue={issue.team}/></FormField><FormField label="Target date"><Input type="date" defaultValue="2026-09-30"/></FormField><FormField label="Status"><select className="h-control rounded-md border border-input bg-surface px-3 text-sm"><option>In Progress</option><option>Ready for Review</option><option>Rectified</option></select></FormField><FormField label="Work notes"><Textarea defaultValue={issue.workNotes}/></FormField><Button>Save update</Button><Button variant="secondary" onClick={()=>setReinspect(true)}>Record reinspection</Button></div></DashboardCard></div><DashboardCard className="mt-4 overflow-hidden"><div className="p-4"><h2 className="text-lg font-bold">Issue history</h2></div><SimpleTable headers={["Date / time","User","Action","Old value","New value","Remarks"]} rows={[["30 Sep · 3:15 PM",issue.team,"Status updated","Assigned","In Progress",issue.workNotes],["28 Sep · 1:30 PM","Handover Team","Issue created","—","Open",issue.description]]}/></DashboardCard><ReinspectionModal open={reinspect} onOpenChange={setReinspect}/></div></AppShell>}
