import { createFileRoute, Link } from "@tanstack/react-router";
import { CalendarDays, Plus } from "lucide-react";
import { useState } from "react";
import { AppShell } from "@/components/app-shell";
import { appointments } from "@/components/handover/handover-data";
import { HandoverNavigation, HandoverStatusBadge } from "@/components/handover/handover-ui";
import { ScheduleAppointmentModal } from "@/components/handover/handover-workflows";
import { SimpleTable } from "@/components/sales/sales-ui";
import { Button, DashboardCard, SelectMenu } from "@/components/ui/crm";
export const Route=createFileRoute("/handover/calendar")({head:()=>({meta:[{title:"Handover Calendar | Green Horizon CRM"},{name:"description",content:"Snagging, reinspection and final handover appointments."},{property:"og:title",content:"Handover Calendar | Green Horizon CRM"},{property:"og:description",content:"Snagging, reinspection and final handover appointments."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Calendar});
function Calendar(){const [view,setView]=useState("Week");const [open,setOpen]=useState(false);return <AppShell crumbs={["Workspace","Handover","Calendar"]}><div className="mx-auto max-w-[1540px] p-4 md:p-6"><HandoverNavigation/><header className="flex flex-col gap-4 xl:flex-row xl:justify-between"><div><h1>Handover calendar</h1><p className="text-sm text-muted-foreground">Snagging, reinspection and final handover appointments.</p></div><Button onClick={()=>setOpen(true)}><Plus size={15}/>Schedule appointment</Button></header><DashboardCard className="mt-5 p-4"><div className="flex flex-wrap gap-2"><div className="flex rounded-md border border-border p-1">{["Day","Week","List"].map(v=><Button key={v} variant={view===v?"primary":"ghost"} className="h-8 px-3 text-xs" onClick={()=>setView(v)}>{v}</Button>)}</div><SelectMenu label="All projects" items={["Horizon Residences","Green Park","Creek Vista"]}/><SelectMenu label="Appointment type" items={["Snagging","Reinspection","Final Handover"]}/><SelectMenu label="Assigned team" items={["Handover Team","Technical Team","Layla Noor"]}/><SelectMenu label="Status" items={["Scheduled","Confirmed","Rescheduled","Completed","Customer No-show","Cancelled"]}/></div></DashboardCard><DashboardCard className="mt-4 overflow-hidden"><div className="flex items-center gap-2 border-b border-border p-4"><CalendarDays size={18} className="text-primary"/><div><h2 className="text-lg font-bold">28 Sep – 04 Oct 2026</h2><p className="text-xs text-muted-foreground">{view} view · 3 appointments</p></div></div><SimpleTable headers={["Date / Time","Customer","Project / Unit","Type","Assigned team","Status","Actions"]} rows={appointments.map(a=>[`${a.date} · ${a.time}`,a.customer,`${a.project} · ${a.unit}`,a.type,a.team,a.status,a.id])} badges={[5]}/><div className="border-t border-border p-3 text-xs text-muted-foreground">Select an appointment reference to open full appointment details.</div></DashboardCard><ScheduleAppointmentModal open={open} onOpenChange={setOpen}/></div></AppShell>}
