import { createFileRoute, Link } from "@tanstack/react-router";
import { Plus } from "lucide-react";
import { useState } from "react";
import { AppShell } from "@/components/app-shell";
import { inspectionSections, snagIssues } from "@/components/handover/handover-data";
import { HandoverNavigation, HandoverStatusBadge, InspectionSummary } from "@/components/handover/handover-ui";
import { AddIssueModal } from "@/components/handover/handover-workflows";
import { InfoGrid, SimpleTable } from "@/components/sales/sales-ui";
import { Button, DashboardCard } from "@/components/ui/crm";
export const Route=createFileRoute("/handover/inspections/$inspectionId")({head:({params})=>({meta:[{title:`${params.inspectionId} Snagging Inspection | Green Horizon CRM`},{name:"description",content:"Unit snagging inspection workspace and issue tracking."},{property:"og:title",content:`${params.inspectionId} Snagging Inspection | Green Horizon CRM`},{property:"og:description",content:"Unit snagging inspection workspace and issue tracking."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Inspection});
function Inspection(){const {inspectionId}=Route.useParams();const [add,setAdd]=useState(false);return <AppShell crumbs={["Workspace","Handover","Snagging",inspectionId]}><div className="mx-auto max-w-[1540px] p-4 md:p-6"><HandoverNavigation/><header className="flex flex-col gap-4 xl:flex-row xl:justify-between"><div><p className="text-xs font-semibold text-muted-foreground">Snagging Inspection</p><div className="flex items-center gap-2"><h1>{inspectionId}</h1><HandoverStatusBadge status="In Progress"/></div><p className="text-sm text-muted-foreground">HND-2026-00182 · Horizon Residences · A-1204</p></div><div className="flex gap-2"><Link to="/handover/inspections/$inspectionId/report" params={{inspectionId}}><Button variant="secondary">Open report</Button></Link><Button onClick={()=>setAdd(true)}><Plus size={15}/>Add issue</Button></div></header><div className="mt-5"><InspectionSummary/></div><div className="mt-4 grid gap-4 xl:grid-cols-[1.5fr_1fr]"><DashboardCard className="overflow-hidden"><SimpleTable headers={["Issue","Category","Severity","Location","Assigned","Target","Status"]} rows={snagIssues.map(i=>[i.title,i.category,i.severity,i.location,i.team,i.target,i.status])} badges={[2,6]}/></DashboardCard><div className="space-y-4"><DashboardCard className="p-5"><h2 className="text-lg font-bold">Inspection details</h2><div className="mt-4"><InfoGrid columns="grid-cols-1" items={[["Handover","HND-2026-00182"],["Unit","A-1204"],["Customer","Sarah Ahmed"],["Inspector","Handover Team"],["Date","28 Sep 2026"],["Status","In Progress"]]}/></div></DashboardCard><DashboardCard className="overflow-hidden"><div className="p-4"><h2 className="text-lg font-bold">Configurable areas</h2></div><SimpleTable headers={["Area","Checks","Result"]} rows={inspectionSections}/></DashboardCard></div></div><AddIssueModal open={add} onOpenChange={setAdd}/></div></AppShell>}
