import { createFileRoute, Link } from "@tanstack/react-router";
import * as DropdownMenu from "@radix-ui/react-dropdown-menu";
import { ArrowUp, Building2, ChevronRight, CircleDollarSign, Ellipsis, ExternalLink, FileCheck2, FileText, Headphones, Plus, Users, WalletCards } from "lucide-react";
import { useState } from "react";
import { AppShell } from "@/components/app-shell";
import { ActionList, ActionListItem, Avatar, Button, ChartCard, DashboardCard, DataTable, FormField, IconButton, Input, MetricCard, ModalShell, ProgressBar, SelectMenu, StatusBadge, TableRow, Tabs } from "@/components/ui/crm";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "Business Overview | Green Horizon CRM" },
    { name: "description", content: "Management overview for Green Horizon Developments sales, collections, inventory, and approvals." },
    { property: "og:title", content: "Business Overview | Green Horizon CRM" },
    { property: "og:description", content: "Management overview for Green Horizon Developments sales, collections, inventory, and approvals." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ]}),
  component: Overview,
});

const months=["Apr 2026","May 2026","Jun 2026","Jul 2026","Aug 2026","Sep 2026"];
const current=[8,11,17,21,24,25], previous=[3,5,7,9,13,14];

function RevenueChart() {
  const [tip,setTip]=useState<number|null>(null);
  return <div className="mt-4"><div className="relative grid h-32 grid-cols-[34px_repeat(6,1fr)] grid-rows-[repeat(4,1fr)] border-b border-border text-[10px] text-muted-foreground">
    {["30M","20M","10M","0"].map((v,i)=><div key={v} className="col-start-1 flex items-start pr-2" style={{gridRow:i+1}}>{v}</div>)}
    {[1,2,3,4].map(row=><div key={row} className="col-start-2 col-end-8 border-t border-dashed border-border" style={{gridRow:row}}/>)}
    {months.map((month,i)=><div key={month} className="relative col-start-auto row-start-1 row-end-5 flex items-end justify-center gap-1" style={{gridColumn:i+2}} onMouseEnter={()=>setTip(i)} onMouseLeave={()=>setTip(null)}><span className="w-5 rounded-t-sm bg-action" style={{height:`${(current[i] ?? 0)*3.2}px`}}/><span className="w-5 rounded-t-sm bg-mint" style={{height:`${(previous[i] ?? 0)*3.2}px`}}/>{tip===i&&<span className="absolute bottom-12 z-10 rounded bg-foreground px-2 py-1 text-[10px] text-primary-foreground">AED {current[i] ?? 0}M</span>}</div>)}
  </div><div className="ml-8 grid grid-cols-6 pt-2 text-center text-[10px] text-muted-foreground">{months.map(m=><span key={m}>{m}</span>)}</div></div>;
}

function Overview() {
  const [tab,setTab]=useState("bookings"); const [modal,setModal]=useState(false);
  return <AppShell><div className="mx-auto max-w-[1500px] p-4 md:p-6">
    <header className="mb-4 flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-muted-foreground">Management dashboard</p><h1 className="mt-1 tracking-normal">Business overview</h1><p className="mt-1 text-[15px] text-muted-foreground">A clear view of your sales and customer operations.</p></div><div className="flex flex-wrap gap-2"><SelectMenu label="All projects" items={["All projects","Horizon Residences","Green Park","Marina Vista"]}/><SelectMenu label="Sep 2026" items={["Sep 2026","Aug 2026","Jul 2026"]}/><Button onClick={()=>setModal(true)}><Plus size={17}/>New lead</Button></div></header>

    <DashboardCard className="grid overflow-hidden sm:grid-cols-2 xl:grid-cols-4">
      <MetricCard className="border-b border-border sm:border-r xl:border-b-0"><Kpi icon={<Users/>} label="Active leads" value="1,248"><span className="font-semibold text-success">↗ +12.8%</span> vs last month</Kpi></MetricCard>
      <MetricCard className="border-b border-border xl:border-b-0 xl:border-r"><Kpi icon={<FileText/>} label="Sales booked" value="AED 24.8M">32 units this month</Kpi></MetricCard>
      <MetricCard className="border-b border-border sm:border-r sm:border-b-0 xl:border-r"><Kpi icon={<CircleDollarSign/>} label="Collections received" value="AED 8.6M"><div className="mt-2 flex items-center gap-3"><div className="w-24"><ProgressBar value={86}/></div><span>86% of target</span></div></Kpi></MetricCard>
      <MetricCard className="bg-primary text-primary-foreground"><div className="flex justify-between text-primary-foreground/75"><span>Outstanding</span><ExternalLink size={15}/></div><p className="mt-1 text-metric font-bold">AED 2.4M</p><p className="mt-3 text-xs text-primary-foreground/80"><span className="mr-2 inline-block size-2 rounded-full bg-warning-soft"/>18 overdue installments</p></MetricCard>
    </DashboardCard>

    <div className="mt-4 grid gap-4 xl:grid-cols-[2fr_1.15fr]">
      <ChartCard className="p-5"><div className="flex items-start justify-between"><div><h2 className="text-lg font-bold">Revenue overview</h2><p className="mt-1 text-xs text-muted-foreground">Booked sales across all projects</p></div><SelectMenu label="Last 6 months" items={["Last 6 months","This year","Last year"]}/></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><strong className="text-[28px]">AED 124.6M</strong><StatusBadge tone="success">↗ +18.6%</StatusBadge></div><div className="flex gap-5 text-xs text-muted-foreground"><span><i className="mr-2 inline-block size-2 rounded-full bg-action"/>This period</span><span><i className="mr-2 inline-block size-2 rounded-full bg-mint"/>Previous period</span></div></div><RevenueChart/></ChartCard>
      <DashboardCard className="flex flex-col p-5"><div className="flex justify-between"><h2 className="text-lg font-bold">Inventory snapshot</h2><button className="text-xs font-semibold text-success hover:underline">View inventory ↗</button></div><div className="mt-4 flex items-end gap-3"><strong className="text-[36px] leading-none">480</strong><span className="pb-1 text-xs text-muted-foreground">Total units</span></div><div className="mt-5 flex h-5 overflow-hidden rounded-full"><span className="bg-mint" style={{width:"37.5%"}}/><span className="bg-info" style={{width:"13.33%"}}/><span className="bg-action" style={{width:"44.17%"}}/><span className="bg-warning-soft" style={{width:"5%"}}/></div><div className="mt-4 grid grid-cols-2 gap-x-6 gap-y-3 text-xs"><Legend color="bg-mint" label="Available" value="180"/><Legend color="bg-info" label="Reserved" value="64"/><Legend color="bg-action" label="Sold" value="212"/><Legend color="bg-warning-soft" label="On hold" value="24"/></div><button className="mt-auto flex h-10 items-center rounded-md bg-muted px-3 text-xs font-medium"><Building2 size={16} className="mr-2 text-muted-foreground"/>Across 4 active projects<ChevronRight size={16} className="ml-auto text-muted-foreground"/></button></DashboardCard>
    </div>

    <div className="mt-4 grid gap-4 xl:grid-cols-[2fr_1.15fr]">
      <DashboardCard className="overflow-hidden p-4"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><h2 className="text-lg font-bold">Latest transactions</h2><StatusBadge>32 this month</StatusBadge></div><button className="text-xs font-semibold text-success hover:underline">View all ↗</button></div><div className="mt-3"><Tabs value={tab} onValueChange={setTab} items={[{value:"bookings",label:"Bookings"},{value:"agreements",label:"Agreements"}]}/></div>{tab==="bookings" ? <DataTable><thead className="bg-muted text-[11px] text-muted-foreground"><tr><th className="rounded-l-md px-3 py-2 font-medium">Customer</th><th className="px-3 py-2 font-medium">Project / Unit</th><th className="px-3 py-2 font-medium">Status</th><th className="px-3 py-2 font-medium">Amount</th><th className="rounded-r-md px-3 py-2 font-medium">Actions</th></tr></thead><tbody><Transaction initials="SA" name="Sarah Ahmed" project="Horizon Residences" unit="A-1204" status="Reserved" tone="info" amount="AED 1.25M"/><Transaction initials="OK" name="Omar Khalid" project="Green Park" unit="B-0806" status="SPA signed" tone="success" amount="AED 980K"/></tbody></DataTable> : <div className="grid h-[112px] place-items-center text-sm text-muted-foreground">No recent agreements</div>}</DashboardCard>
      <DashboardCard className="overflow-hidden"><div className="flex items-center gap-3 p-4"><h2 className="text-lg font-bold">Action center</h2><StatusBadge tone="danger">15 pending</StatusBadge></div><ActionList><Action icon={<CircleDollarSign size={17}/>} tone="warning" title="Discount approval" detail="Unit A-1402 · 5% requested"/><Action icon={<FileCheck2 size={17}/>} tone="info" title="Legal review" detail="SPA · Sarah Ahmed"/><Action icon={<WalletCards size={17}/>} tone="danger" title="Payment follow-up" detail="Unit B-0901 · AED 45,000"/><Link to="/customer-care/cases/$caseId" params={{caseId:"CC-2026-00841"}}><Action icon={<Headphones size={17}/>} tone="warning" title="Customer Care escalation" detail="CC-2026-00841 · SLA at risk"/></Link></ActionList></DashboardCard>
    </div>
  </div><NewLeadModal open={modal} onOpenChange={setModal}/></AppShell>;
}

function Kpi({icon,label,value,children}:{icon:React.ReactNode;label:string;value:string;children:React.ReactNode}) { return <div><div className="flex items-center gap-3"><span className="text-muted-foreground [&>svg]:size-5">{icon}</span><div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-metric font-bold">{value}</p></div></div><div className="ml-8 mt-3 text-xs text-muted-foreground">{children}</div></div>; }
function Legend({color,label,value}:{color:string;label:string;value:string}) { return <div className="flex items-center"><i className={`mr-2 size-2 rounded-full ${color}`}/><span className="text-muted-foreground">{label}</span><strong className="ml-auto">{value}</strong></div>; }
function Transaction({initials,name,project,unit,status,tone,amount}:{initials:string;name:string;project:string;unit:string;status:string;tone:"info"|"success";amount:string}) { return <TableRow><td className="px-3 py-3"><div className="flex items-center gap-3"><Avatar initials={initials} tone={tone==="info"?"blue":"mint"}/><span className="font-medium">{name}</span></div></td><td className="px-3 py-3"><span className="block">{project}</span><span className="text-[11px] text-muted-foreground">{unit}</span></td><td className="px-3 py-3"><StatusBadge tone={tone}>{status}</StatusBadge></td><td className="px-3 py-3 font-medium">{amount}</td><td className="px-3 py-3"><DropdownMenu.Root><DropdownMenu.Trigger asChild><IconButton label={`Actions for ${name}`}><Ellipsis size={17}/></IconButton></DropdownMenu.Trigger><DropdownMenu.Portal><DropdownMenu.Content align="end" className="z-50 rounded-md border border-border bg-surface p-1 shadow-menu"><DropdownMenu.Item className="cursor-pointer rounded px-3 py-2 text-xs outline-none hover:bg-muted">Open booking</DropdownMenu.Item><DropdownMenu.Item className="cursor-pointer rounded px-3 py-2 text-xs outline-none hover:bg-muted">View customer</DropdownMenu.Item></DropdownMenu.Content></DropdownMenu.Portal></DropdownMenu.Root></td></TableRow>; }
function Action({icon,tone,title,detail}:{icon:React.ReactNode;tone:"warning"|"info"|"danger";title:string;detail:string}) { const styles={warning:"bg-warning-soft text-warning",info:"bg-info-soft text-info",danger:"bg-danger-soft text-danger"}; return <ActionListItem><span className={`grid size-9 place-items-center rounded-md ${styles[tone]}`}>{icon}</span><span className="min-w-0 flex-1"><strong className="block text-sm">{title}</strong><span className="block truncate text-[11px] text-muted-foreground">{detail}</span></span><ChevronRight size={16} className="text-muted-foreground"/></ActionListItem>; }
function NewLeadModal({open,onOpenChange}:{open:boolean;onOpenChange:(open:boolean)=>void}) { return <ModalShell open={open} onOpenChange={onOpenChange} title="New lead"><form onSubmit={e=>{e.preventDefault();onOpenChange(false)}} className="grid gap-4"><div className="grid gap-4 sm:grid-cols-2"><FormField label="First name"><Input required placeholder="First name"/></FormField><FormField label="Last name"><Input required placeholder="Last name"/></FormField><FormField label="Phone"><Input type="tel" placeholder="+971 50 000 0000"/></FormField><FormField label="Email"><Input type="email" placeholder="name@example.com"/></FormField><FormField label="Lead source"><Input placeholder="Referral"/></FormField><FormField label="Interested project"><Input placeholder="Select project"/></FormField></div><div className="mt-2 flex justify-end gap-2"><Button type="button" variant="secondary" onClick={()=>onOpenChange(false)}>Cancel</Button><Button type="submit">Create lead</Button></div></form></ModalShell>; }