import { createFileRoute } from "@tanstack/react-router";
import { Download, WalletCards } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { projectCollections } from "@/components/payments/payment-data";
import { AgingBars } from "@/components/payments/payment-ui";
import { CompactMetrics, SimpleTable } from "@/components/sales/sales-ui";
import { Button, DashboardCard, ProgressBar, SelectMenu } from "@/components/ui/crm";
export const Route=createFileRoute("/payments/projects")({head:()=>({meta:[{title:"Project Collections | Green Horizon CRM"},{name:"description",content:"Compare project receivables, collections, overdue balances and collection rates."},{property:"og:title",content:"Project Collections | Green Horizon CRM"},{property:"og:description",content:"Compare project receivables, collections, overdue balances and collection rates."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Projects});
function Projects(){return <AppShell crumbs={["Workspace","Payments","Project collections"]}><div className="mx-auto max-w-[1580px] p-4 md:p-6"><header className="flex flex-col gap-3 sm:flex-row sm:justify-between"><div><p className="text-xs font-semibold text-muted-foreground">Finance reporting</p><h1>Project collections</h1><p className="text-sm text-muted-foreground">Compare receivables, collections, overdue balances, and collection performance.</p></div><div className="flex gap-2"><SelectMenu label="Sep 2026" items={["Sep 2026","Aug 2026","Q3 2026","YTD 2026"]}/><Button variant="secondary"><Download size={15}/>Export</Button></div></header><div className="mt-5"><CompactMetrics items={[{label:"Portfolio sale value",value:"AED 317.3M",detail:"Active sales",icon:<WalletCards/>},{label:"Total due",value:"AED 194.3M",detail:"Through selected period",icon:<WalletCards/>},{label:"Received",value:"AED 161.2M",detail:"82.9% collection rate",icon:<WalletCards/>},{label:"Overdue",value:"AED 6.4M",detail:"3.3% of due",icon:<WalletCards/>}]}/></div><DashboardCard className="mt-4 overflow-hidden"><div className="p-4"><h2 className="text-lg font-bold">Project-wise collections</h2></div><SimpleTable headers={["Project","Sale value","Amount due","Amount received","Outstanding","Overdue","Collection rate"]} rows={projectCollections}/></DashboardCard><div className="mt-4 grid gap-4 xl:grid-cols-2"><DashboardCard className="p-5"><h2 className="text-lg font-bold">Collection rate by project</h2><div className="mt-5 space-y-5">{projectCollections.map(row=><div key={row[0]}><div className="mb-1 flex justify-between text-xs"><span>{row[0]}</span><strong>{row[6]}</strong></div><ProgressBar value={Number(row[6]?.replace("%","") ?? 0)}/></div>)}</div></DashboardCard><DashboardCard className="p-5"><h2 className="text-lg font-bold">Portfolio overdue aging</h2><div className="mt-5"><AgingBars/></div></DashboardCard></div><DashboardCard className="mt-4 overflow-hidden"><div className="p-4"><h2 className="text-lg font-bold">Monthly collections by project</h2></div><SimpleTable headers={["Project","Apr","May","Jun","Jul","Aug","Sep","YTD"]} rows={[["Horizon Residences","AED 8.4M","AED 9.1M","AED 10.2M","AED 11.7M","AED 12.3M","AED 14.1M","AED 78.1M"],["Green Park","AED 5.9M","AED 6.4M","AED 6.8M","AED 7.1M","AED 7.8M","AED 8.6M","AED 49.4M"],["Creek Vista","AED 3.8M","AED 4.1M","AED 4.5M","AED 4.9M","AED 5.2M","AED 6.1M","AED 33.7M"]]}/></DashboardCard></div></AppShell>}
