import { createFileRoute, Link } from "@tanstack/react-router";
import { Activity, AlertTriangle, Building2, CircleDollarSign, FileText, Grid3X3, Plus, Tag } from "lucide-react";
import { useState } from "react";
import { AppShell } from "@/components/app-shell";
import { buildings, projects, getInventoryUnits } from "@/components/projects/inventory-data";
import { ActivityPanel, CompactMetrics, InfoGrid, InventoryDistributionBar, InventoryStatusBadge, PaymentPlanSummary, SimpleTable, toneFor } from "@/components/projects/projects-ui";
import { Button, DashboardCard, StatusBadge, Tabs } from "@/components/ui/crm";
export const Route=createFileRoute("/projects/$projectId")({head:({params})=>({meta:[{title:`${params.projectId} Project | Green Horizon CRM`},{name:"description",content:"Project inventory, buildings, availability, pricing and history."},{property:"og:title",content:`${params.projectId} Project | Green Horizon CRM`},{property:"og:description",content:"Project inventory, buildings, availability, pricing and history."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:ProjectDetail});
const tabItems=["Overview","Buildings","Units","Availability","Pricing","Payment plans","Sales activity","Documents","History"].map(label=>({value:label.toLowerCase().replace(" ","-"),label}));
import {BorrowingStrip} from "@/components/finance/borrowing-ui";
import {M,projectSales} from "@/components/finance/revenue-data";
function ProjectRevenueStrip({projectId}:{projectId:string}){const p=projectSales.find(x=>x.id===projectId);if(!p)return null;return <DashboardCard className="mt-4 flex flex-wrap items-center gap-x-6 gap-y-2 p-4 text-xs"><strong className="text-sm">Finance revenue</strong><span>Contract value <strong>{M(p.contract)}</strong></span><span>Recognized <strong>{M(p.recognized)}</strong></span><span>Unrecognized <strong>{M(p.contract-p.recognized)}</strong></span><span>Collected <strong>{M(p.collected)}</strong></span><Link to="/finance/revenue/projects/$projectId" params={{projectId}} className="ml-auto text-primary">Open revenue & sales →</Link></DashboardCard>}
function ProjectDetail(){const {projectId}=Route.useParams();const project=projects.find(item=>item.id===projectId)??projects[0];if(!project)return null;const [tab,setTab]=useState("overview");return <AppShell crumbs={["Workspace","Projects & units",project.name]}><div className="mx-auto max-w-[1580px] p-4 md:p-6"><header className="flex flex-col gap-4 xl:flex-row xl:justify-between"><div><p className="text-xs font-semibold text-muted-foreground">Project 360 · {project.id}</p><div className="flex flex-wrap items-center gap-2"><h1>{project.name}</h1><StatusBadge tone={toneFor(project.status)}>{project.status}</StatusBadge></div><p className="text-sm text-muted-foreground">{project.location} · {project.code} · Green Horizon Developments</p></div><div className="flex gap-2"><Link to="/projects/$projectId/edit" params={{projectId}}><Button variant="secondary">Edit project</Button></Link><Link to="/projects/units/create"><Button><Plus size={16}/>Add unit</Button></Link></div></header><div className="mt-5"><CompactMetrics items={[{label:"Total units",value:String(project.units),detail:`${project.buildings} buildings · ${project.floors} floors`,icon:<Building2/>},{label:"Available",value:String(project.available),detail:"34.4% of inventory",icon:<Grid3X3/>},{label:"Reserved / Sold",value:`${project.reserved} / ${project.sold}`,detail:`${project.onHold} units on hold`,icon:<Tag/>},{label:"Inventory value",value:project.inventoryValue,detail:"Approved unit pricing",icon:<CircleDollarSign/>}]}/></div><ProjectRevenueStrip projectId={projectId}/><BorrowingStrip project={projectSales.find(x=>x.id===projectId)?.project??""}/><div className="mt-5"><Tabs value={tab} onValueChange={setTab} items={tabItems}/></div><div className="mt-4">{tab==="overview"&&<Overview project={project}/>} {tab==="buildings"&&<Buildings projectId={projectId}/>} {tab==="units"&&<Units projectId={projectId}/>} {tab==="availability"&&<Availability/>} {tab==="pricing"&&<Pricing/>} {tab==="payment-plans"&&<PaymentPlanSummary/>} {tab==="sales-activity"&&<SalesActivity/>} {tab==="documents"&&<Documents/>} {tab==="history"&&<History/>}</div></div></AppShell>}
function Overview({project}:{project:(typeof projects)[number]}){return <div className="grid gap-4 xl:grid-cols-[1.6fr_1fr]"><div className="space-y-4"><DashboardCard className="p-5"><h2 className="text-lg font-bold">Inventory summary</h2><div className="mt-5"><InventoryDistributionBar/></div></DashboardCard><DashboardCard className="p-5"><h2 className="text-lg font-bold">Recent unit activity</h2><div className="mt-4"><ActivityPanel/></div></DashboardCard></div><div className="space-y-4"><DashboardCard className="p-5"><h2 className="text-lg font-bold">Project information</h2><div className="mt-4"><InfoGrid columns="grid-cols-2" items={[["Project code",project.code],["Location",project.location],["Developer",project.developer],["Launch date",project.launchDate],["Expected completion",project.completion],["Status",project.status],["Buildings",String(project.buildings)],["Floors",String(project.floors)]]}/></div></DashboardCard><DashboardCard className="p-5"><h2 className="text-lg font-bold">Availability alerts</h2><div className="mt-3 space-y-2"><Alert>4 holds expire within 24 hours.</Alert><Alert>2 units are under pricing review.</Alert></div></DashboardCard></div></div>}
function Alert({children}:{children:string}){return <div className="flex gap-2 rounded-md bg-warning-soft p-3 text-xs text-warning"><AlertTriangle size={14}/>{children}</div>}
function Buildings({projectId}:{projectId:string}){return <div className="grid gap-4 lg:grid-cols-2">{buildings.filter(item=>item.projectId===projectId).map(building=><DashboardCard key={building.id} className="p-5"><div className="flex items-start justify-between"><div><h2 className="text-lg font-bold">{building.name}</h2><p className="text-xs text-muted-foreground">{building.code} · {building.floors} floors</p></div><Link to="/projects/$projectId/buildings/$buildingId" params={{projectId,buildingId:building.id}} className="text-xs font-semibold text-primary">Open building</Link></div><div className="mt-5"><InfoGrid columns="grid-cols-3" items={[["Total units",String(building.units)],["Available",String(building.available)],["Reserved",String(building.reserved)],["Sold",String(building.sold)],["On hold",String(building.onHold)]]}/></div></DashboardCard>)}</div>}
function Units({projectId}:{projectId:string}){const rows=getInventoryUnits().filter(unit=>unit.projectId===projectId).map(unit=>[unit.number,unit.building,`Floor ${unit.floor}`,unit.subtype,`AED ${unit.approvedPrice.toLocaleString()}`,unit.status]);return <DashboardCard className="overflow-hidden"><SimpleTable headers={["Unit","Building","Floor","Type","Approved price","Status"]} rows={rows} badges={[5]}/></DashboardCard>}
function Availability(){return <DashboardCard className="p-5"><h2 className="text-lg font-bold">Availability breakdown</h2><div className="mt-5"><InventoryDistributionBar/></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-md bg-muted p-3 text-xs"><strong>Fast-moving inventory</strong><p className="mt-1 text-muted-foreground">2 Bedroom · Tower A · Floors 10–16</p></div><div className="rounded-md bg-muted p-3 text-xs"><strong>Recently released</strong><p className="mt-1 text-muted-foreground">3 units returned to Available this week</p></div></div></DashboardCard>}
function Pricing(){return <DashboardCard className="overflow-hidden"><SimpleTable headers={["Unit type","Units","Base range","Approved range","Available value"]} rows={[["Studio","18","AED 650K–720K","AED 640K–710K","AED 4.1M"],["1 Bedroom","54","AED 850K–1.05M","AED 835K–1.03M","AED 14.8M"],["2 Bedroom","72","AED 1.18M–1.55M","AED 1.16M–1.52M","AED 23.6M"],["3 Bedroom","36","AED 1.72M–2.24M","AED 1.69M–2.20M","AED 8.9M"]]}/></DashboardCard>}
function SalesActivity(){return <DashboardCard className="overflow-hidden"><SimpleTable headers={["Date","Unit","Event","Customer","Reference","Status"]} rows={[["24 Sep 2026","A-1204","Sales offer accepted","Sarah Ahmed","SO-2026-00482","Active"],["24 Sep 2026","A-1203","Reservation created","Sarah Ahmed","RSV-2026-00181","Reserved"],["23 Sep 2026","A-1402","EOI created","Aisha Rahman","EOI-2026-00179","Active"]]} badges={[5]}/></DashboardCard>}
function Documents(){return <DashboardCard className="overflow-hidden"><SimpleTable headers={["Document","Type","Version","Uploaded by","Updated","Status"]} rows={[["Horizon Residences brochure","Project brochure","v3","Mira Joseph","18 Sep 2026","Current"],["Tower A floor plans","Floor plans","v5","Ahmed Malik","12 Sep 2026","Current"],["Approved pricing sheet","Pricing","Sep 2026","Nadia Rahman","01 Sep 2026","Approved"],["Standard payment plans","Payment plan","v2","Mira Joseph","22 Aug 2026","Current"]]} badges={[5]}/></DashboardCard>}
function History(){return <DashboardCard className="overflow-hidden"><SimpleTable headers={["Date / time","User","Action","Old value","New value","Reason"]} rows={[["24 Sep · 2:30 PM","Ahmed Malik","Pricing updated","Aug price sheet","Sep price sheet","Campaign pricing approved"],["18 Sep · 10:15 AM","Mira Joseph","Project document updated","Brochure v2","Brochure v3","Launch revision"],["01 Sep · 9:00 AM","Nadia Rahman","Status changed","Construction","Active sales","Sales release approved"]]}/></DashboardCard>}