import {createFileRoute} from "@tanstack/react-router";
import {Plus} from "lucide-react";
import {useState} from "react";
import {AppShell} from "@/components/app-shell";
import {RecordTable,pageMeta} from "@/components/finance/accounting-ui";
import {policies as seed,policyOptions,type Policy} from "@/components/finance/revenue-data";
import {RevBadge} from "@/components/finance/revenue-ui";
import {SettingsLayout,SettingsSection} from "@/components/settings/settings-ui";
import {Button,FormField,Input} from "@/components/ui/crm";

export const Route=createFileRoute("/settings/accounting-policies")({head:()=>pageMeta("Finance accounting policies","Configure versioned revenue recognition policies, triggers, timing, review and GL accounts."),component:Page});

const sel="h-10 w-full rounded-md border border-input bg-surface px-3 text-sm";
function Page(){const [rows,setRows]=useState<Policy[]>(seed);const [open,setOpen]=useState<Policy|null>(null);const [draft,setDraft]=useState<Policy|null>(null);const [msg,setMsg]=useState("");
const newVersion=(p:Policy)=>{const v=`v${rows.filter(x=>x.id===p.id).length+1}`;setDraft({...p,version:v,status:"Draft",usedBy:0,effective:""});setOpen(null)};
const save=(activate:boolean)=>{if(!draft)return;if(!draft.effective.trim())return setMsg("Effective date is required.");setRows(r=>[...r.map(x=>activate&&x.id===draft.id&&x.status==="Active"?{...x,status:"Archived" as const}:x),{...draft,status:activate?"Active":"Draft"}]);setMsg(`${draft.id} ${draft.version} saved as ${activate?"Active — previous version archived; historical records keep their original version":"Draft"}.`);setDraft(null)};
const f=(k:keyof Policy,v:string)=>draft&&setDraft({...draft,[k]:v});
return <AppShell crumbs={["Workspace","Settings","Finance accounting policies"]}><SettingsLayout title="Finance accounting policies" description="Versioned policies that drive the IFRS 15-ready revenue recognition workflow. Configuration is not automatically IFRS-compliant — it reflects the company's approved policy." actions={<Button onClick={()=>setDraft({id:`POL-REV-00${rows.length}`,name:"",type:"Revenue Recognition",scope:"",effective:"",version:"v1",status:"Draft",trigger:policyOptions[0]!,timing:"",review:"Finance Manager approval",gl:"Dr 2410 / Cr 4110",projects:"",txTypes:"",usedBy:0})}><Plus size={15}/>New policy</Button>}>
{msg&&<p className="rounded-md bg-success-soft p-2 text-xs text-success">{msg}</p>}
<SettingsSection title="Policies"><div className="-mx-1 rounded-md border border-border"><RecordTable headers={["Policy","Type","Scope","Effective","Version","Status","Used by","Actions"]} rows={rows.map(p=>[`${p.id} · ${p.name}`,p.type,p.scope,p.effective||"—",p.version,<RevBadge s={p.status}/>,`${p.usedBy} records`,<div className="flex gap-1"><Button variant="secondary" className="h-7 px-2 text-[11px]" onClick={()=>setOpen(p)}>View</Button>{p.status!=="Archived"&&<Button variant="secondary" className="h-7 px-2 text-[11px]" onClick={()=>newVersion(p)}>New version</Button>}</div>])}/></div></SettingsSection>
{open&&<SettingsSection title={`${open.name} · ${open.version}`}><div className="rounded-md border border-border"><RecordTable headers={["Rule","Configuration"]} rows={[["Applicable projects",open.projects],["Transaction types",open.txTypes],["Recognition trigger",open.trigger],["Recognition timing",open.timing],["Review requirement",open.review],["GL accounts",open.gl],["Effective date",open.effective],["Status",open.status==="Archived"?"Archived — read-only, preserved for historical records":open.status]]}/></div></SettingsSection>}
{draft&&<SettingsSection title={`Edit ${draft.id} ${draft.version} (draft)`}><div className="grid gap-4 sm:grid-cols-2"><FormField label="Policy name"><Input value={draft.name} onChange={e=>f("name",e.target.value)}/></FormField><FormField label="Scope"><Input value={draft.scope} onChange={e=>f("scope",e.target.value)}/></FormField><FormField label="Applicable projects"><Input value={draft.projects} onChange={e=>f("projects",e.target.value)}/></FormField><FormField label="Transaction types"><Input value={draft.txTypes} onChange={e=>f("txTypes",e.target.value)}/></FormField><FormField label="Recognition trigger"><select className={sel} value={draft.trigger} onChange={e=>f("trigger",e.target.value)}>{policyOptions.map(o=><option key={o}>{o}</option>)}</select></FormField><FormField label="Recognition timing / schedule"><Input value={draft.timing} onChange={e=>f("timing",e.target.value)} placeholder="e.g. Monthly per certified progress"/></FormField><FormField label="Review requirement"><Input value={draft.review} onChange={e=>f("review",e.target.value)}/></FormField><FormField label="GL accounts"><Input value={draft.gl} onChange={e=>f("gl",e.target.value)}/></FormField><FormField label="Effective date"><Input value={draft.effective} onChange={e=>f("effective",e.target.value)} placeholder="01 Jan 2027"/></FormField></div><div className="mt-4 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setDraft(null)}>Cancel</Button><Button variant="secondary" onClick={()=>save(false)}>Save draft</Button><Button onClick={()=>save(true)}>Activate version</Button></div></SettingsSection>}
</SettingsLayout></AppShell>}
