import type {ReactNode} from "react";
import {Download,Search} from "lucide-react";
import {toneFor} from "@/components/sales/sales-ui";
import {Button,DashboardCard,Input,MetricCard,SelectMenu,StatusBadge} from "@/components/ui/crm";
import {accountingAudit,fmt,type JournalLine} from "./accounting-data";

export const pageMeta=(title:string,description:string)=>({meta:[{title:`${title} | Green Horizon CRM`},{name:"description",content:description},{property:"og:title",content:`${title} | Green Horizon CRM`},{property:"og:description",content:description},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]});

export function Kpis({items}:{items:[string,string,string,ReactNode][]}){return <DashboardCard className="grid overflow-hidden sm:grid-cols-2 xl:grid-cols-4">{items.map(([label,value,detail,icon],i)=><MetricCard key={label} className={i<items.length-1?"border-b border-border sm:border-r xl:border-b-0":""}><div className="flex gap-3"><span className="mt-1 text-muted-foreground [&>svg]:size-4">{icon}</span><div><span className="text-[11px] text-muted-foreground">{label}</span><strong className="block text-2xl leading-tight">{value}</strong><span className="text-[11px] text-muted-foreground">{detail}</span></div></div></MetricCard>)}</DashboardCard>}

export function Panel({title,subtitle,actions,children,flush}:{title:string;subtitle?:string;actions?:ReactNode;children:ReactNode;flush?:boolean}){return <DashboardCard className={flush?"overflow-hidden":"p-5"}><div className={`flex flex-wrap items-start justify-between gap-3 ${flush?"p-4":""}`}><div><h2 className="text-lg font-bold">{title}</h2>{subtitle&&<p className="text-xs text-muted-foreground">{subtitle}</p>}</div>{actions}</div><div className={flush?"":"mt-4"}>{children}</div></DashboardCard>}

export function Toolbar({placeholder,filters=[]}:{placeholder:string;filters?:[string,string[]][]}){return <div className="grid gap-3 border-b border-border p-4 xl:grid-cols-[minmax(260px,1fr)_repeat(4,auto)]"><label className="relative"><Search size={15} className="absolute left-3 top-3 text-muted-foreground"/><Input className="pl-9" placeholder={placeholder}/></label>{filters.map(([label,items])=><SelectMenu key={label} label={label} items={items}/>)}<Button variant="secondary"><Download size={15}/>Export</Button></div>}

/** Generic record table: cells may be strings or nodes (links). Badge columns are rendered as status badges. */
export function RecordTable({headers,rows,badges=[],right=[],empty="No records match these filters."}:{headers:string[];rows:ReactNode[][];badges?:number[];right?:number[];empty?:string}){if(!rows.length)return <p className="p-8 text-center text-xs text-muted-foreground">{empty}</p>;return <div className="overflow-x-auto"><table className="w-full min-w-[760px] border-collapse text-left text-xs"><thead className="bg-muted text-muted-foreground"><tr>{headers.map((h,i)=><th key={h} className={`whitespace-nowrap p-3 font-medium ${right.includes(i)?"text-right":""}`}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i} className="border-b border-border hover:bg-muted/40">{row.map((cell,j)=><td key={j} className={`whitespace-nowrap p-3 ${right.includes(j)?"text-right tabular-nums":""}`}>{badges.includes(j)&&typeof cell==="string"?<StatusBadge tone={toneFor(cell==="Posted"||cell==="Matched"||cell==="Reviewed"||cell==="Accepted"||cell==="Closed"||cell==="Allocated"||cell==="In use"||cell==="Passed"?"Approved":cell==="Unmatched"||cell==="Exception"||cell==="Validation failed"||cell==="Blocked"||cell==="Over budget"||cell==="Missing documents"||cell==="At risk"||cell==="Amount mismatch"||cell==="Missing Finance record"||cell==="Conflict"?"Failed":cell)}>{cell}</StatusBadge>:j===0&&typeof cell==="string"?<strong>{cell}</strong>:cell}</td>)}</tr>)}</tbody></table></div>}

export function JournalLines({lines}:{lines:JournalLine[]}){const d=lines.reduce((s,l)=>s+l.debit,0),c=lines.reduce((s,l)=>s+l.credit,0);return <><RecordTable headers={["Account","Description","Cost centre","Project","Debit","Credit"]} right={[4,5]} rows={lines.map(l=>[l.account,l.description,l.costCentre,l.project,l.debit?fmt(l.debit):"—",l.credit?fmt(l.credit):"—"])}/><div className="flex justify-end gap-8 border-t border-border p-3 text-xs"><span>Total debit <strong className="ml-2">{fmt(d)}</strong></span><span>Total credit <strong className="ml-2">{fmt(c)}</strong></span><StatusBadge tone={d===c?"success":"danger"}>{d===c?"Balanced":"Out of balance"}</StatusBadge></div></>}

export function AuditPanel({rows=accountingAudit}:{rows?:string[][]}){return <Panel flush title="Audit history" subtitle="Immutable · posted records change only through reversal"><RecordTable headers={["Time","User","Record","Action","Before","After"]} rows={rows}/></Panel>}

export function Placeholder({title,children}:{title:string;children:ReactNode}){return <div className="rounded-md border border-dashed border-border bg-muted/40 p-4 text-xs"><strong className="block text-sm">{title}</strong><p className="mt-1 text-muted-foreground">{children}</p></div>}
