import {useState,type FormEvent,type ReactNode} from "react";
import {Plus,Trash2} from "lucide-react";
import {z} from "zod";
import {Button,FieldError,FormField,Input,ModalShell,Textarea} from "@/components/ui/crm";
import {bankAccounts,costCentres,fmt,glAccounts} from "./accounting-data";
import {Placeholder} from "./accounting-ui";

type Props={open:boolean;onOpenChange:(open:boolean)=>void};
const sel="h-control w-full rounded-md border border-input bg-surface px-3 text-sm outline-none focus:border-primary";
function Select({name,items,defaultValue}:{name:string;items:string[];defaultValue?:string|undefined}){return <select name={name} defaultValue={defaultValue} className={sel}>{items.map(i=><option key={i}>{i}</option>)}</select>}
function Actions({close,label}:{close:()=>void;label:string}){return <div className="mt-5 flex justify-end gap-2"><Button type="button" variant="secondary" onClick={close}>Cancel</Button><Button type="submit">{label}</Button></div>}
function useForm(schema:z.ZodTypeAny,msg:string,done:(d:Record<string,unknown>)=>void){const [error,setError]=useState("");const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const r=schema.safeParse(Object.fromEntries(new FormData(e.currentTarget)));if(!r.success){setError(msg);return}setError("");done(r.data as Record<string,unknown>)};return {error,submit}}
function Shell({open,onOpenChange,title,children}:Props&{title:string;children:ReactNode}){return <ModalShell open={open} onOpenChange={onOpenChange} title={title}>{children}</ModalShell>}
const posting=glAccounts.filter(a=>a.posting&&a.status==="Active").map(a=>`${a.code} ${a.name}`);
const centres=costCentres.map(c=>`${c.id} · ${c.name}`);

export function TransferModal({open,onOpenChange}:Props){const accts=bankAccounts.map(b=>`${b.id} · ${b.name}`);const {error,submit}=useForm(z.object({from:z.string(),to:z.string(),amount:z.coerce.number().positive().max(500000000),date:z.string().min(1),reference:z.string().trim().min(3).max(80)}).refine(d=>d.from!==d.to),"Choose two different accounts and enter a valid amount, date and reference",()=>onOpenChange(false));return <Shell open={open} onOpenChange={onOpenChange} title="Internal bank transfer"><form onSubmit={submit} className="grid gap-3 sm:grid-cols-2"><FormField label="From account"><Select name="from" items={accts}/></FormField><FormField label="To account"><Select name="to" items={accts} defaultValue={accts[2]}/></FormField><FormField label="Amount (AED)"><Input name="amount" type="number" min="0" step="0.01"/></FormField><FormField label="Transfer date"><Input name="date" type="date"/></FormField><div className="sm:col-span-2"><FormField label="Reference"><Input name="reference" maxLength={80} placeholder="TRF reference"/></FormField></div><div className="sm:col-span-2"><Placeholder title="Accounting impact">Debit destination bank GL · Credit source bank GL. The journal is generated after Finance Manager approval.</Placeholder></div><div className="sm:col-span-2"><FieldError>{error}</FieldError><Actions close={()=>onOpenChange(false)} label="Submit for approval"/></div></form></Shell>}

export function GlAccountModal({open,onOpenChange}:Props){const {error,submit}=useForm(z.object({code:z.string().regex(/^\d{4}$/),name:z.string().trim().min(3).max(80),type:z.string(),parent:z.string()}).refine(d=>!glAccounts.some(a=>a.code===d.code)),"Enter a unique 4-digit code and an account name (3–80 characters)",()=>onOpenChange(false));return <Shell open={open} onOpenChange={onOpenChange} title="Create GL account"><form onSubmit={submit} className="grid gap-3 sm:grid-cols-2"><FormField label="Account code"><Input name="code" maxLength={4} placeholder="e.g. 6220"/></FormField><FormField label="Account name"><Input name="name" maxLength={80}/></FormField><FormField label="Account type"><Select name="type" items={["Asset","Liability","Equity","Revenue","Expense"]}/></FormField><FormField label="Parent account"><Select name="parent" items={["1100 Cash & bank","1200 Receivables","2100 Payables","2200 Accruals","5100 Cost of sales","6100 Overheads"]}/></FormField><FormField label="Posting allowed"><Select name="posting" items={["Yes — posting account","No — header account"]}/></FormField><FormField label="Required dimension"><Select name="dim" items={["None","Cost centre","Project","Cost centre + project"]}/></FormField><div className="sm:col-span-2"><FieldError>{error}</FieldError><Actions close={()=>onOpenChange(false)} label="Create account"/></div></form></Shell>}

type Line={account:string;debit:string;credit:string;centre:string};
export function JournalModal({open,onOpenChange}:Props){const blank=():Line=>({account:posting[0]??"",debit:"",credit:"",centre:centres[0]??""});const [lines,setLines]=useState<Line[]>([{...blank(),debit:"0"},{...blank(),account:posting[1]??"",credit:"0"}]);const [desc,setDesc]=useState("");const [error,setError]=useState("");const d=lines.reduce((s,l)=>s+(Number(l.debit)||0),0),c=lines.reduce((s,l)=>s+(Number(l.credit)||0),0);const set=(i:number,k:keyof Line,v:string)=>setLines(ls=>ls.map((l,j)=>j===i?{...l,[k]:v}:l));
function submit(e:FormEvent){e.preventDefault();if(desc.trim().length<3)return setError("Enter a journal description");if(lines.some(l=>(Number(l.debit)||0)<0||(Number(l.credit)||0)<0||((Number(l.debit)||0)>0&&(Number(l.credit)||0)>0)))return setError("Each line must be either a positive debit or a positive credit");if(d<=0)return setError("Journal total must be greater than zero");if(Math.abs(d-c)>0.005)return setError(`Journal is out of balance by ${fmt(Math.abs(d-c))}`);setError("");onOpenChange(false)}
return <Shell open={open} onOpenChange={onOpenChange} title="Create journal entry"><form onSubmit={submit}><div className="grid gap-3 sm:grid-cols-3"><FormField label="Journal date"><Input type="date" defaultValue="2026-09-25"/></FormField><FormField label="Period"><Input value="Sep 2026 · Open" readOnly/></FormField><FormField label="Type"><select className={sel}><option>Manual</option><option>Adjustment</option><option>Reclassification</option></select></FormField></div><div className="mt-3"><FormField label="Description"><Input value={desc} onChange={e=>setDesc(e.target.value)} maxLength={140}/></FormField></div><div className="mt-4 space-y-2">{lines.map((l,i)=><div key={i} className="grid grid-cols-[1fr_1fr_90px_90px_32px] gap-2"><select aria-label="Account" value={l.account} onChange={e=>set(i,"account",e.target.value)} className={sel}>{posting.map(p=><option key={p}>{p}</option>)}</select><select aria-label="Cost centre" value={l.centre} onChange={e=>set(i,"centre",e.target.value)} className={sel}>{centres.map(p=><option key={p}>{p}</option>)}</select><Input aria-label="Debit" type="number" min="0" placeholder="Debit" value={l.debit} onChange={e=>set(i,"debit",e.target.value)}/><Input aria-label="Credit" type="number" min="0" placeholder="Credit" value={l.credit} onChange={e=>set(i,"credit",e.target.value)}/><button type="button" aria-label="Remove line" disabled={lines.length<=2} onClick={()=>setLines(ls=>ls.filter((_,j)=>j!==i))} className="grid place-items-center text-muted-foreground disabled:opacity-30"><Trash2 size={14}/></button></div>)}</div><div className="mt-3 flex flex-wrap items-center justify-between gap-2 text-xs"><Button type="button" variant="ghost" onClick={()=>setLines(ls=>[...ls,blank()])}><Plus size={14}/>Add line</Button><span>Debit <strong>{fmt(d)}</strong> · Credit <strong>{fmt(c)}</strong> · Difference <strong className={d===c?"text-success":"text-danger"}>{fmt(Math.abs(d-c))}</strong></span></div><FieldError>{error}</FieldError><Actions close={()=>onOpenChange(false)} label="Save & submit for approval"/></form></Shell>}

export function AccrualModal({open,onOpenChange,prepaid=false}:Props&{prepaid?:boolean}){const {error,submit}=useForm(z.object({description:z.string().trim().min(3).max(120),amount:z.coerce.number().positive().max(100000000),start:z.string().min(1),months:z.coerce.number().int().min(1).max(60).optional()}),"Enter a description, positive amount and valid date",()=>onOpenChange(false));return <Shell open={open} onOpenChange={onOpenChange} title={prepaid?"Create prepaid":"Create accrual"}><form onSubmit={submit} className="grid gap-3 sm:grid-cols-2"><div className="sm:col-span-2"><FormField label="Description"><Input name="description" maxLength={120}/></FormField></div><FormField label={prepaid?"Supplier / AP invoice":"Supplier / counterparty"}><Input name="party" maxLength={80}/></FormField><FormField label="Amount (AED)"><Input name="amount" type="number" min="0"/></FormField><FormField label={prepaid?"Recognition start":"Accrual date"}><Input name="start" type="date"/></FormField>{prepaid?<FormField label="Recognition months"><Input name="months" type="number" min="1" max="60" defaultValue="12"/></FormField>:<FormField label="Reversal"><Select name="reversal" items={["Auto-reverse first day of next period","Manual reversal"]}/></FormField>}<FormField label={prepaid?"Prepaid asset account":"Expense account"}><Select name="dr" items={posting}/></FormField><FormField label="Cost centre"><Select name="cc" items={centres}/></FormField><div className="sm:col-span-2"><FieldError>{error}</FieldError><Actions close={()=>onOpenChange(false)} label="Submit for approval"/></div></form></Shell>}

export function ReasonModal({open,onOpenChange,title,label,note,onConfirm}:Props&{title:string;label:string;note?:string;onConfirm:(reason:string)=>void}){const [reason,setReason]=useState("");const [error,setError]=useState("");return <Shell open={open} onOpenChange={onOpenChange} title={title}><form onSubmit={e=>{e.preventDefault();if(reason.trim().length<10)return setError("Enter a reason of at least 10 characters for the audit trail");setError("");onConfirm(reason.trim());setReason("");onOpenChange(false)}}>{note&&<div className="mb-3"><Placeholder title="Control">{note}</Placeholder></div>}<FormField label="Reason"><Textarea value={reason} maxLength={500} onChange={e=>setReason(e.target.value)}/></FormField><FieldError>{error}</FieldError><Actions close={()=>onOpenChange(false)} label={label}/></form></Shell>}

export function DisposalModal({open,onOpenChange,nbv,onConfirm}:Props&{nbv:number;onConfirm:()=>void}){const [proceeds,setProceeds]=useState("0");const [error,setError]=useState("");const p=Number(proceeds)||0;return <Shell open={open} onOpenChange={onOpenChange} title="Dispose asset"><form onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));if(!z.object({date:z.string().min(1),method:z.string(),reason:z.string().trim().min(10)}).safeParse(f).success||p<0)return setError("Enter disposal date, non-negative proceeds and a reason (10+ characters)");setError("");onConfirm();onOpenChange(false)}} className="grid gap-3 sm:grid-cols-2"><FormField label="Disposal date"><Input name="date" type="date"/></FormField><FormField label="Method"><Select name="method" items={["Sale","Scrap","Write-off","Donation"]}/></FormField><FormField label="Proceeds (AED)"><Input type="number" min="0" value={proceeds} onChange={e=>setProceeds(e.target.value)}/></FormField><FormField label="Net book value"><Input value={fmt(nbv)} readOnly/></FormField><div className="sm:col-span-2"><FormField label="Reason"><Textarea name="reason" maxLength={500}/></FormField></div><div className="sm:col-span-2"><Placeholder title={`Estimated ${p-nbv>=0?"gain":"loss"} on disposal: ${fmt(p-nbv)}`}>Requires Finance Manager approval before the disposal journal is posted.</Placeholder></div><div className="sm:col-span-2"><FieldError>{error}</FieldError><Actions close={()=>onOpenChange(false)} label="Submit disposal"/></div></form></Shell>}
