import {Link,useRouterState} from "@tanstack/react-router";
import {ArrowDownLeft,ArrowUpRight,Building2,CircleDollarSign,Clock,FileText,ReceiptText,WalletCards} from "lucide-react";
import type {ReactNode} from "react";
import {aed,type PayableStatus,type Receivable,type ReceivableStatus} from "./finance-data";
import {InfoGrid,SimpleTable,Timeline,toneFor} from "@/components/sales/sales-ui";
import {Button,DashboardCard,MetricCard,ProgressBar,StatusBadge} from "@/components/ui/crm";
const links=[{label:"Overview",to:"/finance" as const},{label:"Receivables",to:"/finance/receivables" as const},{label:"Payables",to:"/finance/payables" as const},{label:"Reports",to:"/finance/reports" as const}];
export function FinanceNavigation(){const path=useRouterState({select:s=>s.location.pathname});return <div className="mb-5 flex gap-6 overflow-x-auto border-b border-border">{links.map(item=><Link key={item.to} to={item.to} activeOptions={{exact:item.to==="/finance"}} className={`-mb-px shrink-0 border-b-2 pb-2 text-xs font-medium ${path===item.to||(item.to!=="/finance"&&path.startsWith(`${item.to}/`))?"border-primary text-primary":"border-transparent text-muted-foreground"}`}>{item.label}</Link>)}</div>}
export function FinancePage({title,eyebrow,description,actions,children}:{title:string;eyebrow:string;description:string;actions?:ReactNode;children:ReactNode}){return <div className="mx-auto max-w-[1580px] p-4 md:p-6"><FinanceNavigation/><header className="flex flex-col gap-3 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-muted-foreground">{eyebrow}</p><h1 className="mt-1">{title}</h1><p className="text-sm text-muted-foreground">{description}</p></div>{actions}</header>{children}</div>}
export function ReceivableStatusBadge({status}:{status:ReceivableStatus|string}){return <StatusBadge tone={status==="Cleared"||status==="Paid"?"success":status==="Overdue"?"danger":status==="Pending Verification"||status==="Partially Paid"?"warning":status==="Open"?"info":"neutral"}>{status}</StatusBadge>}
export function PayableStatusBadge({status}:{status:PayableStatus|string}){return <StatusBadge tone={status==="Approved"||status==="Paid"?"success":status==="Overdue"||status==="Rejected"?"danger":status==="Pending Approval"||status==="Due"||status==="Partially Paid"?"warning":"neutral"}>{status}</StatusBadge>}
export function FinanceKpis({kind="overview"}:{kind?:"overview"|"ar"|"ap"}){const items=kind==="overview"?[["Accounts receivable","AED 42.2M","Outstanding customer balance",<CircleDollarSign/>],["Receipts this month","AED 8.6M","1,248 customer receipts",<ArrowDownLeft/>],["Accounts payable","AED 12.8M","Open supplier liabilities",<WalletCards/>],["Overdue","AED 6.4M","92 overdue items",<Clock/>]]:kind==="ar"?[["Total receivable","AED 42.2M","340 open records",<CircleDollarSign/>],["Due this month","AED 12.4M","Current obligations",<FileText/>],["Overdue","AED 6.4M","92 overdue items",<Clock/>],["Received this month","AED 8.6M","1,248 receipts",<ReceiptText/>]]:[["Open payables","AED 12.8M","186 supplier invoices",<WalletCards/>],["Due this month","AED 4.1M","Current obligations",<FileText/>],["Overdue","AED 1.2M","28 supplier invoices",<Clock/>],["Paid this month","AED 6.8M","Approved disbursements",<ArrowUpRight/>]];return <DashboardCard className="grid overflow-hidden sm:grid-cols-2 xl:grid-cols-4">{items.map(([label,value,detail,icon],i)=><MetricCard key={String(label)} className={`${i<3?"border-b border-border sm:border-r xl:border-b-0":""} ${kind==="overview"&&i===3?"bg-primary text-primary-foreground":""}`}><div className="flex gap-3"><span className={`mt-1 [&>svg]:size-4 ${kind==="overview"&&i===3?"text-primary-foreground":"text-muted-foreground"}`}>{icon}</span><div><span className={`text-[11px] ${kind==="overview"&&i===3?"text-primary-foreground":"text-muted-foreground"}`}>{label}</span><strong className="block text-2xl leading-tight">{value}</strong><span className={`text-[11px] ${kind==="overview"&&i===3?"text-primary-foreground":"text-muted-foreground"}`}>{detail}</span></div></div></MetricCard>)}</DashboardCard>}
export function CRMSourceReference({receivable}:{receivable:Receivable}){return <DashboardCard className="p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-bold">CRM source reference</h2><p className="text-xs text-muted-foreground">Linked source data; no duplicate CRM transaction.</p></div><StatusBadge tone="info">CRM</StatusBadge></div><div className="mt-4"><InfoGrid columns="grid-cols-1" items={[["CRM transaction",receivable.crmReference],["Transaction type",receivable.source],["Customer",`${receivable.customer} · ${receivable.customerId}`],["Project / unit",`${receivable.project} · ${receivable.unit}`]]}/></div><div className="mt-4 grid gap-2 sm:grid-cols-2"><Link to="/sales/reservations/$reservationId" params={{reservationId:"RSV-2026-00182"}}><Button variant="secondary" className="w-full">View CRM transaction</Button></Link><Link to="/payments/accounts/$accountId" params={{accountId:"ACC-2026-00482"}}><Button variant="secondary" className="w-full">Open Payment 360</Button></Link></div></DashboardCard>}
export function AgingSummary(){const rows=[["Current",85],["1–30 days",48],["31–60 days",29],["61–90 days",18],["90+ days",12]];return <DashboardCard className="p-5"><h2 className="text-lg font-bold">Receivable aging</h2><p className="text-xs text-muted-foreground">Outstanding balance by aging bucket</p><div className="mt-5 space-y-4">{rows.map(([label,value])=><div key={label}><div className="mb-1 flex justify-between text-xs"><span>{label}</span><strong>{value} items</strong></div><ProgressBar value={Number(value)}/></div>)}</div></DashboardCard>}
export function ApprovalPanel(){const steps=[["Finance Manager","Approved","Maya Joseph · 24 Sep, 10:15 AM"],["Management","Approved","Ahmed Malik · 24 Sep, 11:02 AM"]];return <DashboardCard className="p-5"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold">Finance approval</h2><p className="text-xs text-muted-foreground">Configured workflow · sequential</p></div><StatusBadge tone="success">Approved</StatusBadge></div><div className="mt-4 space-y-3">{steps.map(([role,status,detail],i)=><div key={role} className="flex items-center gap-3 rounded-md border border-border p-3"><span className="grid size-7 place-items-center rounded-full bg-success-soft text-xs font-bold text-success">{i+1}</span><div className="min-w-0 flex-1"><strong className="text-sm">{role}</strong><p className="text-[11px] text-muted-foreground">{detail}</p></div><StatusBadge tone={toneFor(status??"")}>{status}</StatusBadge></div>)}</div></DashboardCard>}
export function SupplierBankDetails({revealed,onReveal}:{revealed:boolean;onReveal:()=>void}){return <DashboardCard className="p-5"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold">Supplier bank details</h2><p className="text-xs text-muted-foreground">Sensitive information · permission controlled</p></div><StatusBadge tone="warning">Restricted</StatusBadge></div><div className="mt-4"><InfoGrid columns="grid-cols-1" items={[["IBAN",revealed?"AE07 0331 2345 6789 4821":"•••• •••• •••• 4821"],["Bank",revealed?"Emirates NBD":"Hidden"],["Account holder","BuildTech LLC"]]}/></div><Button variant="secondary" className="mt-4 w-full" onClick={onReveal}>{revealed?"Hide bank details":"Reveal if authorized"}</Button></DashboardCard>}
export function FinanceTimeline({items}:{items:string[][]}){return <DashboardCard className="p-5"><h2 className="text-lg font-bold">Activity timeline</h2><div className="mt-4"><Timeline items={items.map((x,i)=>({icon:i%2?ReceiptText:Building2,title:x[0]??"Activity",detail:x[1]??"",time:x[2]??""}))}/></div></DashboardCard>}
export function FinanceReportTable({rows}:{rows:string[][]}){return <DashboardCard className="overflow-hidden"><SimpleTable headers={["Report","Position","Records","Updated"]} rows={rows}/></DashboardCard>}
export function OutstandingSummary({total,paid}:{total:number;paid:number}){const outstanding=total-paid;return <DashboardCard className="p-5"><h2 className="text-lg font-bold">Payment position</h2><div className="mt-4"><InfoGrid items={[["Gross amount",aed(total)],["Paid",aed(paid)],["Outstanding",aed(outstanding)],["Completion",`${Math.round((paid/total)*100)}%`]]}/></div><div className="mt-4"><ProgressBar value={(paid/total)*100}/></div></DashboardCard>}
