import {Link} from "@tanstack/react-router";
import {RefreshCw} from "lucide-react";
import {InfoGrid} from "@/components/sales/sales-ui";
import {DashboardCard,StatusBadge} from "@/components/ui/crm";
import type {SyncStatus} from "./integration-data";

export function SyncBadge({status}:{status:SyncStatus|string}){return <StatusBadge tone={status==="Synced"?"success":status==="Failed"?"danger":status==="Conflict"||status==="Manual Review Required"?"warning":"info"}>{status}</StatusBadge>}

/** Compact Finance reference card shown on CRM records. Read-only: Finance ERP is the source of financial truth. */
export function FinanceSyncCard({title="Finance ERP",items,status="Synced",lastSync="Today · 10:42 AM",arId="AR-2026-01842"}:{title?:string;items:[string,string][];status?:SyncStatus;lastSync?:string;arId?:string}){return <DashboardCard className="mt-4 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><RefreshCw size={14} className="text-muted-foreground"/><h2 className="text-sm font-bold">{title}</h2><SyncBadge status={status}/></div><span className="text-[11px] text-muted-foreground">Last synced {lastSync} · Data source: Finance ERP</span></div><div className="mt-3"><InfoGrid columns="lg:grid-cols-6" items={items}/></div><div className="mt-3 flex gap-4 text-xs font-medium"><Link to="/finance/receivables/$receivableId" params={{receivableId:arId}} className="text-primary">View Finance account</Link><Link to="/finance/integration" className="text-muted-foreground hover:text-primary">Sync history</Link></div></DashboardCard>}

export function ClearanceCard({cleared}:{cleared:boolean}){return <DashboardCard className="mt-4 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><h2 className="text-sm font-bold">Finance clearance</h2><StatusBadge tone={cleared?"success":"danger"}>{cleared?"Cleared":"Not cleared"}</StatusBadge></div><span className="text-[11px] text-muted-foreground">Issued by Finance ERP · cannot be set manually in CRM</span></div><div className="mt-3"><InfoGrid columns="lg:grid-cols-4" items={cleared?[["Outstanding","AED 0"],["Overdue","AED 0"],["Reference","FC-2026-00412"],["Cleared","26 Sep 2026"]]:[["Outstanding","AED 185,000"],["Overdue","AED 98,000"],["Reference","—"],["Action","Collect balance before handover"]]}/></div><Link to="/finance/receivables/$receivableId" params={{receivableId:cleared?"AR-2026-01842":"AR-2026-01843"}} className="mt-3 inline-block text-xs font-medium text-primary">View Finance account</Link></DashboardCard>}
