import {useState,type FormEvent} from "react";
import {z} from "zod";
import {Button,FieldError,FormField,Input,ModalShell,Textarea} from "@/components/ui/crm";
import {fmt} from "./accounting-data";
import {Placeholder} from "./accounting-ui";
import {budgets,expenses} from "./spend-data";
type Props={open:boolean;onOpenChange:(o:boolean)=>void};
const sel="h-control w-full rounded-md border border-input bg-surface px-3 text-sm outline-none focus:border-primary";
const active=budgets.filter(b=>b.fy==="FY2026");
function Actions({close,label}:{close:()=>void;label:string}){return <div className="mt-5 flex justify-end gap-2"><Button type="button" variant="secondary" onClick={close}>Cancel</Button><Button type="submit">{label}</Button></div>}

export function BudgetModal({open,onOpenChange}:Props){const [error,setError]=useState("");function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!z.object({name:z.string().trim().min(3).max(100),amount:z.coerce.number().positive().max(10000000000),owner:z.string().trim().min(2).max(80)}).safeParse(Object.fromEntries(new FormData(e.currentTarget))).success)return setError("Enter a budget name, owner and positive amount");setError("");onOpenChange(false)}
return <ModalShell open={open} onOpenChange={onOpenChange} title="Create budget"><form onSubmit={submit} className="grid gap-3 sm:grid-cols-2"><div className="sm:col-span-2"><FormField label="Budget name"><Input name="name" maxLength={100}/></FormField></div><FormField label="Type"><select name="type" className={sel}><option>Operating</option><option>Project</option><option>Capital</option></select></FormField><FormField label="Fiscal year"><select name="fy" className={sel}><option>FY2026</option><option>FY2027</option></select></FormField><FormField label="Cost centre"><select name="cc" className={sel}>{["CC-CON-01","CC-CON-02","CC-MKT-01","CC-SAL-01","CC-FIN-01","CC-ADM-01"].map(c=><option key={c}>{c}</option>)}</select></FormField><FormField label="Project"><select name="project" className={sel}>{["All","Horizon Residences","Green Park","Creek Vista","Corporate"].map(c=><option key={c}>{c}</option>)}</select></FormField><FormField label="Amount (AED)"><Input name="amount" type="number" min="0"/></FormField><FormField label="Budget owner"><Input name="owner" maxLength={80}/></FormField><div className="sm:col-span-2"><FieldError>{error}</FieldError><Actions close={()=>onOpenChange(false)} label="Submit for approval"/></div></form></ModalShell>}

export function BudgetTransferModal({open,onOpenChange}:Props){const [from,setFrom]=useState(active[4]?.id??"");const [to,setTo]=useState(active[2]?.id??"");const [amount,setAmount]=useState("");const [error,setError]=useState("");const src=active.find(b=>b.id===from);const avail=src?src.amount-src.actual-src.committed:0;
function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const a=Number(amount);const reason=String(new FormData(e.currentTarget).get("reason")??"").trim();if(from===to)return setError("Source and destination budgets must differ");if(!(a>0))return setError("Enter a positive amount");if(a>avail)return setError(`Amount exceeds available balance of ${fmt(avail)}`);if(reason.length<10)return setError("Enter a justification (10+ characters)");setError("");onOpenChange(false)}
return <ModalShell open={open} onOpenChange={onOpenChange} title="Budget transfer"><form onSubmit={submit} className="grid gap-3 sm:grid-cols-2"><FormField label="From budget"><select value={from} onChange={e=>setFrom(e.target.value)} className={sel}>{active.map(b=><option key={b.id} value={b.id}>{b.id} · {b.name}</option>)}</select></FormField><FormField label="To budget"><select value={to} onChange={e=>setTo(e.target.value)} className={sel}>{active.map(b=><option key={b.id} value={b.id}>{b.id} · {b.name}</option>)}</select></FormField><FormField label="Amount (AED)"><Input type="number" min="0" value={amount} onChange={e=>setAmount(e.target.value)}/></FormField><FormField label="Available in source"><Input readOnly value={fmt(avail)}/></FormField><div className="sm:col-span-2"><FormField label="Justification"><Textarea name="reason" maxLength={500}/></FormField></div><div className="sm:col-span-2"><FieldError>{error}</FieldError><Actions close={()=>onOpenChange(false)} label="Submit transfer"/></div></form></ModalShell>}

export function ExpenseModal({open,onOpenChange}:Props){const [budgetId,setBudgetId]=useState(active[3]?.id??"");const [amount,setAmount]=useState("");const [error,setError]=useState("");const b=active.find(x=>x.id===budgetId);const avail=b?b.amount-b.actual-b.committed:0;const a=Number(amount)||0;const over=a>avail;
function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));if(!z.object({vendor:z.string().trim().min(2).max(100),date:z.string().min(1),description:z.string().trim().min(3).max(300)}).safeParse(f).success||!(a>0))return setError("Enter vendor, date, description and a positive amount");const dup=expenses.some(x=>x.vendor.toLowerCase()===String(f['vendor']).trim().toLowerCase()&&x.amount===a);if(dup&&!f['confirmDup'])return setError("Possible duplicate: an expense with this vendor and amount already exists. Tick the confirmation to continue.");if(over&&String(f['justification']??"").trim().length<10)return setError("Over-budget expenses need a justification (10+ characters)");setError("");onOpenChange(false)}
return <ModalShell open={open} onOpenChange={onOpenChange} title="New expense"><form onSubmit={submit} className="grid gap-3 sm:grid-cols-2"><FormField label="Expense type"><select name="type" className={sel}><option>Employee expense</option><option>Company expense</option><option>Project expense</option></select></FormField><FormField label="Category"><select name="category" className={sel}>{["Travel","Client entertainment","Events & launches","Digital campaigns","Site utilities","Office supplies"].map(c=><option key={c}>{c}</option>)}</select></FormField><FormField label="Vendor"><Input name="vendor" maxLength={100}/></FormField><FormField label="Expense date"><Input name="date" type="date"/></FormField><FormField label="Budget"><select value={budgetId} onChange={e=>setBudgetId(e.target.value)} className={sel}>{active.map(x=><option key={x.id} value={x.id}>{x.id} · {x.name}</option>)}</select></FormField><FormField label="Amount incl. VAT (AED)"><Input type="number" min="0" value={amount} onChange={e=>setAmount(e.target.value)}/></FormField><div className="sm:col-span-2"><FormField label="Description"><Input name="description" maxLength={300}/></FormField></div><FormField label="Receipt"><Input name="receipt" type="file" accept=".pdf,.jpg,.png"/></FormField><FormField label="Payment method"><select name="payment" className={sel}><option>Reimbursement</option><option>Corporate card</option><option>Supplier invoice</option></select></FormField>
<div className="sm:col-span-2"><Placeholder title={`Budget check · ${b?.costCentre??""} · available ${fmt(avail)}`}>{a===0?"Enter an amount to check against the budget.":over?`Exceeds available budget by ${fmt(a-avail)}. Routed to Finance Director as a budget exception.`:`Within budget. Remaining after this expense: ${fmt(avail-a)}.`}</Placeholder></div>
{over&&<div className="sm:col-span-2"><FormField label="Over-budget justification"><Textarea name="justification" maxLength={500}/></FormField></div>}
<label className="flex items-center gap-2 text-xs sm:col-span-2"><input type="checkbox" name="confirmDup"/>I confirm this is not a duplicate if flagged</label>
<div className="sm:col-span-2"><FieldError>{error}</FieldError><Actions close={()=>onOpenChange(false)} label="Submit expense"/></div></form></ModalShell>}

export function PaymentModal({open,onOpenChange,outstanding,onPay}:Props&{outstanding:number;onPay:(n:number)=>void}){const [amount,setAmount]=useState(String(outstanding));const [error,setError]=useState("");return <ModalShell open={open} onOpenChange={onOpenChange} title="Record reimbursement payment"><form onSubmit={e=>{e.preventDefault();const a=Number(amount);if(!(a>0)||a>outstanding)return setError(`Enter an amount between AED 1 and ${fmt(outstanding)}`);setError("");onPay(a);onOpenChange(false)}} className="grid gap-3 sm:grid-cols-2"><FormField label="Amount (AED)"><Input type="number" min="0" value={amount} onChange={e=>setAmount(e.target.value)}/></FormField><FormField label="Outstanding"><Input readOnly value={fmt(outstanding)}/></FormField><FormField label="Paid from"><select className={sel}><option>BNK-001 · Operating Account</option><option>Payroll run Sep 2026</option></select></FormField><FormField label="Payment date"><Input type="date" defaultValue="2026-09-29"/></FormField><div className="sm:col-span-2"><FieldError>{error}</FieldError><Actions close={()=>onOpenChange(false)} label="Record payment"/></div></form></ModalShell>}
