import { Link,useRouterState } from "@tanstack/react-router";
import { BarChart3,CalendarDays,Columns3,Download,FileSpreadsheet,Filter,Save,Search } from "lucide-react";
import { useState } from "react";
import { reportCategories } from "./reports-data";
import { Button,DashboardCard,FormField,Input,ModalShell,SelectMenu } from "@/components/ui/crm";
const slug=(x:string)=>x.toLowerCase().replace("crm / leads","crm").replace("finance & collections","finance").replace("resale / noc","resale").replace("customer care","customer-care").replaceAll(" ","-");
export function ReportsNavigation(){const path=useRouterState({select:s=>s.location.pathname});return <div className="mb-5 flex gap-5 overflow-x-auto border-b border-border">{reportCategories.map((label,i)=>{const to=i===0?"/reports":`/reports/${slug(label)}`;return <Link key={label} to={to as "/reports"} className={`-mb-px shrink-0 border-b-2 pb-2 text-xs font-medium ${path===to?"border-primary text-primary":"border-transparent text-muted-foreground"}`}>{label}</Link>})}</div>}
export function AdvancedFilters({context=true}:{context?:boolean}){return <DashboardCard className="p-4"><div className="flex flex-wrap gap-2"><Button variant="secondary"><CalendarDays size={14}/>01–24 Sep 2026</Button><SelectMenu label="All projects" items={["All projects","Horizon Residences","Green Park","Creek Vista"]}/>{context&&<><SelectMenu label="All customers" items={["All customers","Sarah Ahmed","Mohammed Al Farsi"]}/><SelectMenu label="All units" items={["All units","A-1204","B-0806"]}/><SelectMenu label="All statuses" items={["All statuses","Active","Pending","Completed"]}/></>}<Button variant="secondary"><Filter size={14}/>More filters</Button></div></DashboardCard>}
export function ReportActions(){const [save,setSave]=useState(false);const [exp,setExp]=useState(false);return <><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={()=>setSave(true)}><Save size={15}/>Save view</Button><Button variant="secondary" onClick={()=>setExp(true)}><Download size={15}/>Export</Button></div><ModalShell open={save} onOpenChange={setSave} title="Save report view"><form onSubmit={e=>{e.preventDefault();setSave(false)}}><FormField label="View name"><Input required defaultValue="Monthly Collections — Horizon Residences"/></FormField><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-md border border-border p-3"><Filter size={15}/><strong className="mt-2 block text-sm">Current filters</strong><span className="text-xs text-muted-foreground">Date, project and status</span></div><div className="rounded-md border border-border p-3"><Columns3 size={15}/><strong className="mt-2 block text-sm">Visible columns</strong><span className="text-xs text-muted-foreground">Save current selection</span></div></div><div className="mt-5 flex justify-end gap-2"><Button type="button" variant="secondary" onClick={()=>setSave(false)}>Cancel</Button><Button type="submit">Save view</Button></div></form></ModalShell><ModalShell open={exp} onOpenChange={setExp} title="Export report"><div className="grid gap-3 sm:grid-cols-2"><button onClick={()=>setExp(false)} className="rounded-md border border-border p-4 text-left hover:bg-muted"><FileSpreadsheet size={18}/><strong className="mt-2 block">Export Excel</strong><span className="text-xs text-muted-foreground">Current view or full report</span></button><button onClick={()=>setExp(false)} className="rounded-md border border-border p-4 text-left hover:bg-muted"><Download size={18}/><strong className="mt-2 block">Export PDF</strong><span className="text-xs text-muted-foreground">Formatted management report</span></button></div></ModalShell></>}
export function ReportTableTools(){return <div className="flex flex-wrap items-center gap-2 p-4"><label className="relative min-w-56 flex-1"><Search size={14} className="absolute left-3 top-3 text-muted-foreground"/><Input className="pl-9" placeholder="Search report"/></label><Button variant="secondary"><Columns3 size={14}/>Columns</Button><SelectMenu label="Sort by" items={["Newest first","Highest value","Status","Project"]}/></div>}
export function MiniBars({values}:{values:number[]}){return <div className="mt-5 flex h-28 items-end gap-3 border-b border-border px-2">{values.map((v,i)=><div key={i} className="flex-1 rounded-t-sm bg-action" style={{height:`${v}%`}}/>)}</div>}
