import { useState, type FormEvent } from "react";
import { FileUp } from "lucide-react";
import { z } from "zod";
import { Button, FieldError, FormField, Input, ModalShell, SelectMenu, Textarea } from "@/components/ui/crm";
type OpenProps={open:boolean;onOpenChange:(v:boolean)=>void};
const remarkSchema=z.string().trim().min(5,"Add at least 5 characters").max(500,"Keep remarks under 500 characters");
export function DocumentRequestModal({open,onOpenChange,company=false}:OpenProps&{company?:boolean}){const [sent,setSent]=useState(false);return <ModalShell open={open} onOpenChange={onOpenChange} title="Request KYC documents">{sent?<div className="py-6 text-center"><strong>Document request sent</strong><p className="mt-1 text-sm text-muted-foreground">The request was added to communication history.</p><Button className="mt-5" onClick={()=>onOpenChange(false)}>Done</Button></div>:<><div className="grid gap-4 sm:grid-cols-2"><Read label="Customer" value={company?"Blue Crest Holdings LLC":"Sarah Ahmed"}/><FormField label="Channel"><SelectMenu label="Email" items={["Email","WhatsApp"]}/></FormField><fieldset className="sm:col-span-2"><legend className="mb-2 text-[13px] font-medium">Requested documents</legend><div className="space-y-2 rounded-md border border-border p-3">{(company?["Authorized signatory document","Emirates ID of signatory","MOA / AOA"]:["Emirates ID","Proof of address"]).map((x,i)=><label key={x} className="flex items-center gap-2 text-sm"><input type="checkbox" defaultChecked={i<2}/>{x}</label>)}</div></fieldset><FormField label="Message template"><SelectMenu label="KYC Document Request" items={["KYC Document Request","Expiry Replacement Request"]}/></FormField><div className="sm:col-span-2"><FormField label="Optional message"><Textarea maxLength={500}/></FormField></div></div><Actions close={()=>onOpenChange(false)} action="Send request" submit={()=>setSent(true)}/></>}</ModalShell>}
export function KycUploadModal({open,onOpenChange}:OpenProps){return <ModalShell open={open} onOpenChange={onOpenChange} title="Upload KYC document"><div className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2 flex h-24 cursor-pointer flex-col items-center justify-center rounded-card border border-dashed border-border bg-muted text-sm"><FileUp size={20}/><strong className="mt-2">Choose PDF, JPG or PNG</strong><input className="sr-only" type="file" accept=".pdf,.jpg,.jpeg,.png"/></label><FormField label="Document type *"><SelectMenu label="Emirates ID" items={["Passport","Emirates ID","Proof of address","Trade License","MOA / AOA","Authorized signatory document"]}/></FormField><FormField label="Document number"><Input maxLength={80}/></FormField><FormField label="Issue date"><Input type="date"/></FormField><FormField label="Expiry date"><Input type="date"/></FormField><div className="sm:col-span-2"><FormField label="Notes"><Textarea maxLength={500}/></FormField></div></div><Actions close={()=>onOpenChange(false)} action="Upload"/></ModalShell>}
export function KycDecisionModal({open,onOpenChange,decision}:{open:boolean;onOpenChange:(v:boolean)=>void;decision:string}){const [error,setError]=useState("");function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const remarks=String(new FormData(e.currentTarget).get("remarks")??"");if(decision!=="Approve"){const parsed=remarkSchema.safeParse(remarks);if(!parsed.success){setError(parsed.error.issues[0]?.message??"Remarks required");return}}onOpenChange(false)}return <ModalShell open={open} onOpenChange={onOpenChange} title={`${decision} KYC`}><form onSubmit={submit}><p className="text-sm text-muted-foreground">Customer: <strong className="text-foreground">Sarah Ahmed</strong> · KYC-2026-00482</p><div className="mt-4"><FormField label={decision==="Approve"?"Remarks":"Remarks *"}><Textarea name="remarks" maxLength={500} placeholder={decision==="Return"?"Describe the correction required":decision==="Reject"?"Provide the rejection reason":"Optional approval remarks"}/><FieldError>{error}</FieldError></FormField></div><div className="mt-5 flex justify-end gap-2"><Button type="button" variant="secondary" onClick={()=>onOpenChange(false)}>Cancel</Button><Button type="submit">Confirm {decision.toLowerCase()}</Button></div></form></ModalShell>}
function Actions({close,action,submit}:{close:()=>void;action:string;submit?:()=>void}){return <div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={close}>Cancel</Button><Button onClick={submit??close}>{action}</Button></div>}
function Read({label,value}:{label:string;value:string}){return <div><span className="text-[11px] text-muted-foreground">{label}</span><strong className="block text-sm">{value}</strong></div>}
