import { AlertTriangle, Check, Clock, Eye, FileCheck2, FileX2, ShieldCheck, type LucideIcon } from "lucide-react";
import type { ReactNode } from "react";
import { Link, useRouterState } from "@tanstack/react-router";
import { Button, DashboardCard, StatusBadge } from "@/components/ui/crm";
import { SimpleTable, Timeline } from "@/components/sales/sales-ui";
import type { DocumentStatus, KycStatus } from "./kyc-data";
export function KycStatusBadge({status}:{status:KycStatus}){const tone=status==="Approved"||status==="Verified"?"success":status==="Rejected"?"danger":status.includes("Missing")||status.includes("Returned")?"warning":status==="Not started"?"neutral":"info";return <StatusBadge tone={tone}>{status}</StatusBadge>}
export function DocumentStatusBadge({status}:{status:DocumentStatus}){const tone=status==="Verified"?"success":status==="Rejected"||status==="Expired"?"danger":status==="Missing"||status==="Expiring soon"?"warning":"info";return <StatusBadge tone={tone}>{status}</StatusBadge>}
export function ComplianceNavigation(){const path=useRouterState({select:s=>s.location.pathname});return <div className="mt-5 flex gap-6 overflow-x-auto border-b border-border"><Link to="/sales/kyc" className={`-mb-px shrink-0 border-b-2 pb-2 text-xs font-medium ${path.startsWith('/sales/kyc')?'border-primary text-primary':'border-transparent text-muted-foreground'}`}>KYC queue</Link><Link to="/sales/reservations" className={`-mb-px shrink-0 border-b-2 pb-2 text-xs font-medium ${path.startsWith('/sales/reservations')?'border-primary text-primary':'border-transparent text-muted-foreground'}`}>Reservations</Link></div>}
export function KycChecklist({company=false,onUpload}:{company?:boolean;onUpload?:()=>void}){const docs=company?[['Trade License','Required','Verified'],['MOA / AOA','Required','Pending review'],['Authorized signatory document','Required','Missing'],['Passport of authorized signatory','Required','Verified'],['Emirates ID of signatory','Required','Missing']]:[['Passport','Required','Verified'],['Emirates ID','Required','Pending review'],['Proof of address','Optional','Uploaded']];return <div className="divide-y divide-border rounded-card border border-border">{docs.map(([name,required,status])=><div key={name} className="flex items-center gap-3 p-3"><span className={`grid size-7 place-items-center rounded-full ${status==='Verified'?'bg-success-soft text-success':status==='Missing'?'bg-warning-soft text-warning':'bg-info-soft text-info'}`}>{status==='Verified'?<Check size={14}/>:status==='Missing'?<FileX2 size={14}/>:<Clock size={14}/>}</span><div className="min-w-0 flex-1"><strong className="text-sm">{name}</strong><p className="text-[11px] text-muted-foreground">{required}</p></div><DocumentStatusBadge status={status as DocumentStatus}/>{status==='Missing'&&onUpload&&<Button variant="ghost" className="h-8" onClick={onUpload}>Upload</Button>}</div>)}</div>}
export function MissingDocumentAlert({items,onRequest,onUpload}:{items:string[];onRequest:()=>void;onUpload:()=>void}){return <div className="rounded-card border border-warning/20 bg-warning-soft p-4 text-warning"><div className="flex gap-3"><AlertTriangle size={17}/><div className="flex-1"><strong className="text-sm">{items.length} required documents are missing</strong><p className="mt-1 text-xs">{items.join(' · ')}</p><div className="mt-3 flex gap-2"><Button variant="secondary" className="h-8" onClick={onRequest}>Request documents</Button><Button className="h-8" onClick={onUpload}>Upload now</Button></div></div></div></div>}
export function VerificationPanel({blocked=false,onVerify,onReturn}:{blocked?:boolean;onVerify:()=>void;onReturn:()=>void}){return <DashboardCard className="p-5"><div className="flex items-center gap-3"><ShieldCheck className="text-success"/><div><h2 className="text-lg font-bold">Verification review</h2><p className="text-xs text-muted-foreground">Identity fields and documents require an explicit decision.</p></div></div><div className="mt-4"><SimpleTable headers={["Item","Result","Remark"]} rows={[["Passport","Verified","Details and image match"],["Emirates ID",blocked?"Issue found":"Pending","Uploaded copy requires review"],["Customer identity fields","Verified","Matches customer profile"]]} badges={[1]}/></div>{blocked&&<div className="mt-3 rounded-md bg-warning-soft p-3 text-xs text-warning">Verification cannot complete while mandatory items have issues.</div>}<div className="mt-4 flex justify-end gap-2"><Button variant="secondary" onClick={onReturn}>Return for correction</Button><Button disabled={blocked} onClick={onVerify}>Verify KYC</Button></div></DashboardCard>}
export function KycApprovalPanel({onDecision}:{onDecision:(decision:string)=>void}){return <DashboardCard className="p-5"><h2 className="text-lg font-bold">Approval decision</h2><p className="mt-1 text-xs text-muted-foreground">Visible to the authorized compliance approver.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><CheckItem label="Verification result" value="Verified"/><CheckItem label="Required documents" value="Complete"/><CheckItem label="Expiry issues" value="None blocking"/><CheckItem label="Project / unit" value="Horizon Residences · A-1204"/></div><div className="mt-5 flex flex-wrap justify-end gap-2"><Button variant="secondary" onClick={()=>onDecision('Return')}>Return</Button><Button variant="secondary" onClick={()=>onDecision('Reject')}>Reject</Button><Button onClick={()=>onDecision('Approve')}>Approve</Button></div></DashboardCard>}
function CheckItem({label,value}:{label:string;value:string}){return <div className="rounded-md bg-muted p-3"><span className="text-[11px] text-muted-foreground">{label}</span><strong className="mt-1 flex items-center gap-2 text-sm"><Check size={14} className="text-success"/>{value}</strong></div>}
export function MaskedValue({label,value}:{label:string;value:string}){return <div><span className="text-[11px] text-muted-foreground">{label}</span><div className="mt-1 flex items-center gap-2"><strong className="text-sm">{value}</strong><button aria-label={`Reveal ${label}`} title={`Reveal ${label}`} className="text-muted-foreground"><Eye size={14}/></button></div></div>}
export function KycActivity(){const items:{icon:LucideIcon;title:string;detail:string;time:string}[]=[{icon:ShieldCheck,title:"Verification review started",detail:"Assigned to Compliance Team",time:"Today · 11:20 AM"},{icon:FileCheck2,title:"Emirates ID uploaded",detail:"Customer secure upload",time:"23 Sep · 4:10 PM"},{icon:FileCheck2,title:"Passport verified",detail:"Identity details matched",time:"23 Sep · 11:35 AM"},{icon:Clock,title:"KYC created",detail:"From customer CU-2026-00482",time:"22 Sep · 2:45 PM"}];return <Timeline items={items}/>} 
export function PanelTitle({title,children}:{title:string;children?:ReactNode}){return <div className="flex flex-wrap items-center gap-3 p-4"><h2 className="text-lg font-bold">{title}</h2>{children}</div>}
