import { useState, type FormEvent } from "react";
import { AlertTriangle, FileUp } from "lucide-react";
import { z } from "zod";
import { updateUnitStatus } from "@/components/projects/inventory-data";
import { InfoGrid } from "@/components/sales/sales-ui";
import { Button, FieldError, FormField, Input, ModalShell, SelectMenu, Textarea } from "@/components/ui/crm";
type OpenProps={open:boolean;onOpenChange:(v:boolean)=>void};
const remarks=z.string().trim().min(5,"Add at least 5 characters").max(500,"Keep remarks under 500 characters");
export function ReservationApprovalModal({open,onOpenChange}:OpenProps){const [decision,setDecision]=useState('Approve');const [error,setError]=useState('');function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const value=String(new FormData(e.currentTarget).get('remarks')??'');if(decision!=="Approve"&&!remarks.safeParse(value).success){setError('Remarks are required for return or rejection');return}onOpenChange(false)}return <ModalShell open={open} onOpenChange={onOpenChange} title="Reservation approval"><form onSubmit={submit}><InfoGrid columns="sm:grid-cols-2" items={[["Customer","Sarah Ahmed"],["Unit","Horizon Residences · A-1204"],["Final price","AED 1,225,000"],["Reservation amount","AED 122,500"],["KYC","Approved"],["Sales Offer","Approved and accepted"],["Unit status","Available"],["Payment plan","Approved"]]}/><div className="mt-4 flex gap-2">{['Approve','Return','Reject'].map(x=><Button type="button" key={x} variant={decision===x?'primary':'secondary'} className="flex-1" onClick={()=>setDecision(x)}>{x}</Button>)}</div>{decision!=="Approve"&&<div className="mt-4"><FormField label="Remarks *"><Textarea name="remarks" maxLength={500}/><FieldError>{error}</FieldError></FormField></div>}<Actions close={()=>onOpenChange(false)} action={decision}/></form></ModalShell>}
export function ShareReservationModal({open,onOpenChange}:OpenProps){return <ModalShell open={open} onOpenChange={onOpenChange} title="Send Reservation Form"><div className="grid gap-4 sm:grid-cols-2"><Read label="Recipient" value="Sarah Ahmed"/><Read label="Email" value="sarah.ahmed@email.com"/><FormField label="Channel"><SelectMenu label="Electronic signature platform" items={["Email","Electronic signature platform"]}/></FormField><div className="sm:col-span-2"><FormField label="Subject"><Input maxLength={180} defaultValue="Reservation Form — Horizon Residences A-1204"/></FormField></div><div className="sm:col-span-2"><FormField label="Optional message"><Textarea maxLength={500}/></FormField></div></div><div className="mt-4 flex items-center gap-2 rounded-md bg-muted p-3 text-xs"><FileUp size={15}/>Reservation-RSV-2026-00182.pdf</div><Actions close={()=>onOpenChange(false)} action="Send"/></ModalShell>}
export function ReservationPaymentModal({open,onOpenChange}:OpenProps){return <ModalShell open={open} onOpenChange={onOpenChange} title="Record reservation payment"><div className="grid gap-4 sm:grid-cols-2"><FormField label="Amount *"><Input required type="number" min="1" max="122500" defaultValue="122500"/></FormField><FormField label="Payment date *"><Input required type="date" defaultValue="2026-09-24"/></FormField><FormField label="Payment method *"><SelectMenu label="Bank transfer" items={["Bank transfer","Card","Cheque","Other"]}/></FormField><FormField label="Reference number"><Input maxLength={80} defaultValue="PAY-2026-01894"/></FormField><label className="sm:col-span-2 flex h-16 cursor-pointer items-center justify-center gap-2 rounded-md border border-dashed border-border text-xs"><FileUp size={15}/>Proof of payment<input className="sr-only" type="file"/></label><div className="sm:col-span-2"><FormField label="Notes"><Textarea maxLength={500}/></FormField></div></div><p className="mt-3 text-xs text-muted-foreground">Partial payments keep the reservation in Partially paid status until the required amount is satisfied.</p><Actions close={()=>onOpenChange(false)} action="Record payment"/></ModalShell>}
export function CancelReservationModal({open,onOpenChange,onReleased}:{open:boolean;onOpenChange:(v:boolean)=>void;onReleased?:()=>void}){const [cancelled,setCancelled]=useState(false);return <ModalShell open={open} onOpenChange={onOpenChange} title={cancelled?'Release reserved unit':'Cancel reservation'}>{cancelled?<><div className="rounded-md bg-warning-soft p-3 text-xs text-warning">Reservation remains in history. Unit A-1204 is still Reserved until an authorized release.</div><InfoGrid columns="sm:grid-cols-2" items={[["Current unit","A-1204"],["Inventory status","Reserved"]]}/><div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={()=>onOpenChange(false)}>Keep reserved</Button><Button onClick={()=>{updateUnitStatus('UNT-HR-A-1204','Available');onReleased?.();onOpenChange(false)}}>Release unit to inventory</Button></div></>:<><div className="flex gap-2 rounded-md bg-warning-soft p-3 text-xs text-warning"><AlertTriangle size={15}/>Cancellation is permanent, audited, and never deletes the reservation.</div><div className="mt-4"><FormField label="Reason *"><SelectMenu label="Customer withdrew" items={["Customer withdrew","Payment not received","Customer requested unit change","KYC issue","Pricing issue","Management decision","Duplicate booking","Other"]}/></FormField></div><div className="mt-4"><FormField label="Remarks"><Textarea maxLength={500}/></FormField></div><div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={()=>onOpenChange(false)}>Keep reservation</Button><Button onClick={()=>setCancelled(true)}>Confirm cancellation</Button></div></>}</ModalShell>}
export function SpaPlaceholderModal({open,onOpenChange}:OpenProps){return <ModalShell open={open} onOpenChange={onOpenChange} title="Start SPA"><InfoGrid columns="sm:grid-cols-2" items={[["Customer","Sarah Ahmed"],["Unit","A-1204"],["Final price","AED 1,225,000"],["Payment plan","20 / 40 / 40"],["Reservation","RSV-2026-00182"],["KYC","Approved"]]}/><div className="mt-4 rounded-md bg-info-soft p-3 text-xs text-info">SPA workflow will be built in the next module.</div><Actions close={()=>onOpenChange(false)} action="Confirm readiness"/></ModalShell>}
export function DuplicateReservationModal({open,onOpenChange}:OpenProps){return <ModalShell open={open} onOpenChange={onOpenChange} title="Unit already reserved"><div className="rounded-card border border-danger/20 bg-danger-soft p-4 text-danger"><strong>UNIT ALREADY RESERVED</strong><div className="mt-3"><InfoGrid columns="sm:grid-cols-2" items={[["Unit","A-1204"],["Reservation","RSV-2026-00179"],["Customer","Another customer"],["Status","Active"]]}/></div></div><div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={()=>onOpenChange(false)}>Select another unit</Button><Button onClick={()=>onOpenChange(false)}>View reservation</Button></div></ModalShell>}
function Actions({close,action}:{close:()=>void;action:string}){return <div className="mt-5 flex justify-end gap-2"><Button type="button" variant="secondary" onClick={close}>Cancel</Button><Button type="submit" onClick={action==='Send'||action.includes('payment')||action.includes('readiness')?close:undefined}>{action}</Button></div>}
function Read({label,value}:{label:string;value:string}){return <div><span className="text-[11px] text-muted-foreground">{label}</span><strong className="block text-sm">{value}</strong></div>}
