import { AlertTriangle, Check, CircleDollarSign, Clock, FileSignature, ShieldCheck, WalletCards, type LucideIcon } from "lucide-react";
import type { ReactNode } from "react";
import { CompactMetrics, InfoGrid, SimpleTable, Timeline } from "@/components/sales/sales-ui";
import { Button, DashboardCard, StatusBadge } from "@/components/ui/crm";
import { aed, type Reservation, type ReservationStatus } from "./reservation-data";
export function ReservationStatusBadge({status}:{status:ReservationStatus}){const tone=status==="Active"||status==="Ready for SPA"||status==="Signed"?"success":status==="Cancelled"||status==="Terminated"||status==="Expired"?"danger":status.includes("Pending")||status==="Returned"||status==="Partially paid"?"warning":"info";return <StatusBadge tone={tone}>{status}</StatusBadge>}
export function ReservationSummary({reservation:r}:{reservation:Reservation}){return <CompactMetrics items={[{label:"Final price",value:"AED 1.225M",detail:"Approved Version 2",icon:<CircleDollarSign/>},{label:"Reservation amount",value:"AED 122.5K",detail:"10% from payment plan",icon:<WalletCards/>},{label:"Paid",value:`AED ${(r.paid/1000).toFixed(1)}K`,detail:r.payment,icon:<Check/>},{label:"Signature",value:r.signature,detail:"24 Sep · 3:02 PM",icon:<FileSignature/>},{label:"KYC",value:r.kyc,detail:"All purchasers",icon:<ShieldCheck/>},{label:"Expiry",value:r.expiry,detail:"Expires in 6 days",icon:<Clock/>}]}/>} 
export function ReservationValidationPanel({blocked=false,onRefresh}:{blocked?:boolean;onRefresh?:()=>void}){const checks=[['Customer','Sarah Ahmed · exists'],['KYC',blocked?'Missing documents':'Approved'],['Sales Offer','Approved and accepted'],['Unit',blocked?'Reserved elsewhere':'Available · checked just now'],['Final price','Approved · AED 1,225,000'],['Payment plan','Approved · 20 / 40 / 40'],['Broker attribution','Direct · preserved']];return <DashboardCard className="p-5"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold">Pre-reservation validation</h2><p className="text-xs text-muted-foreground">Live compliance, commercial and inventory checks</p></div><Button variant="secondary" className="h-8" onClick={onRefresh}>Refresh checks</Button></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{checks.map(([label,value])=><div key={label} className={`flex items-center gap-2 rounded-md p-3 text-xs ${(value??'').includes('Missing')||(value??'').includes('elsewhere')?'bg-danger-soft text-danger':'bg-success-soft text-success'}`}>{(value??'').includes('Missing')||(value??'').includes('elsewhere')?<AlertTriangle size={14}/>:<Check size={14}/>}<span><strong>{label}:</strong> {value}</span></div>)}</div>{blocked&&<div className="mt-3 rounded-md border border-danger/20 bg-danger-soft p-3 text-sm text-danger"><strong>Reservation cannot proceed.</strong> Complete KYC or select an available unit.</div>}</DashboardCard>}
export function ReservationFormPreview(){return <DashboardCard className="overflow-hidden"><div className="border-b border-border p-4"><h2 className="text-lg font-bold">Reservation Form preview</h2><p className="text-xs text-muted-foreground">Standard Reservation Form · v2.1</p></div><div className="mx-auto my-6 min-h-[540px] max-w-[760px] border border-border bg-surface p-6 md:p-10"><p className="text-center text-[10px] font-semibold uppercase text-muted-foreground">Green Horizon Developments</p><h3 className="mt-2 text-center text-xl font-bold">RESERVATION / BOOKING FORM</h3><p className="text-center text-xs text-muted-foreground">RSV-2026-00182 · Version 1</p><div className="mt-8"><InfoGrid columns="sm:grid-cols-2" items={[["Customer","Sarah Ahmed · CU-2026-00482"],["Joint purchaser","Omar Ahmed · 50%"],["Project / unit","Horizon Residences · A-1204"],["Property","2 Bedroom Apartment"],["Final price","AED 1,225,000"],["Reservation amount","AED 122,500 · 10%"],["Payment plan","Standard 20 / 40 / 40"],["Sales Offer","SO-2026-00482 · v2"],["EOI","EOI-2026-00184"],["KYC","Approved"],["Salesperson","Omar Khan"],["Broker","Direct"],["Reservation date","24 Sep 2026"],["Expiry date","30 Sep 2026"]]}/></div><div className="mt-8 border-t border-border pt-5 text-xs leading-6 text-muted-foreground">Commercial terms and purchaser data are populated from approved CRM records. Signature confirms the reservation subject to the stated terms.</div><div className="mt-16 grid gap-8 border-t border-border pt-6 sm:grid-cols-2"><span className="border-b border-border pb-2 text-xs">Purchaser signature</span><span className="border-b border-border pb-2 text-xs">Authorized signatory</span></div></div></DashboardCard>}
export function SignatureStatus(){return <DashboardCard className="p-5"><h2 className="text-lg font-bold">Electronic signature</h2><div className="mt-4"><Timeline items={[{icon:Check,title:"Signed",detail:"Sarah Ahmed · electronic signature",time:"24 Sep · 3:02 PM"},{icon:Clock,title:"Viewed",detail:"Customer opened document",time:"24 Sep · 2:41 PM"},{icon:FileSignature,title:"Sent and delivered",detail:"sarah.ahmed@email.com",time:"24 Sep · 2:25 PM"}]}/></div></DashboardCard>}
export function ReservationPaymentCard({reservation:r,onRecord}:{reservation:Reservation;onRecord:()=>void}){return <DashboardCard className="p-5"><div className="flex items-start justify-between"><div><h2 className="text-lg font-bold">Reservation payment</h2><p className="text-xs text-muted-foreground">Collections beyond this booking payment remain a future module.</p></div><StatusBadge tone={r.paid>=r.reservationAmount?'success':r.paid?'warning':'neutral'}>{r.payment}</StatusBadge></div><div className="mt-5"><InfoGrid columns="sm:grid-cols-3" items={[["Required",aed(r.reservationAmount)],["Received",aed(r.paid)],["Outstanding",aed(r.reservationAmount-r.paid)],["Reference","PAY-2026-01894"],["Date","24 Sep 2026"],["Method","Bank transfer"]]}/></div><Button className="mt-5" onClick={onRecord}>Record payment</Button></DashboardCard>}
export function ReadyForSpaStatus({onStart}:{onStart:()=>void}){return <DashboardCard className="p-5"><h2 className="text-lg font-bold">Ready for SPA</h2><p className="mt-1 text-xs text-muted-foreground">All required booking conditions are complete.</p><div className="mt-4 space-y-2">{['KYC · Approved','Reservation form · Signed','Reservation payment · Satisfied','Unit · Reserved','Internal approval · Approved','Commercial terms · Final'].map(x=><div key={x} className="flex gap-2 text-sm"><Check size={15} className="text-success"/>{x}</div>)}</div><Button className="mt-5 w-full" onClick={onStart}>Start SPA</Button></DashboardCard>}
export function ReservationActivity(){const items:{icon:LucideIcon;title:string;detail:string;time:string}[]=[{icon:Check,title:'Payment received',detail:'AED 122,500 · PAY-2026-01894',time:'24 Sep · 3:18 PM'},{icon:FileSignature,title:'Reservation signed',detail:'Sarah Ahmed',time:'24 Sep · 3:02 PM'},{icon:Clock,title:'Form viewed',detail:'Electronic signature platform',time:'24 Sep · 2:41 PM'},{icon:FileSignature,title:'Form sent',detail:'Email delivered',time:'24 Sep · 2:25 PM'},{icon:Check,title:'Reservation approved',detail:'Ahmed Malik',time:'24 Sep · 2:10 PM'}];return <Timeline items={items}/>} 
export function PaymentPlanTable(){return <SimpleTable headers={["Installment","Percentage","Amount","Due trigger"]} rows={[["Booking","10%","AED 122,500","Reservation"],["Construction 1","20%","AED 245,000","30% construction"],["Construction 2","20%","AED 245,000","60% construction"],["Handover","50%","AED 612,500","Handover notice"]]}/>} 
export function Notice({children}:{children:ReactNode}){return <div className="rounded-md bg-info-soft p-3 text-xs text-info">{children}</div>}
