import { Link, useRouterState } from "@tanstack/react-router";
import { CalendarDays, Check, CircleDollarSign, ClipboardCheck, FileCheck2, KeyRound, SearchCheck, Wrench } from "lucide-react";
import { CompactMetrics, InfoGrid, SimpleTable, Timeline } from "@/components/sales/sales-ui";
import { DashboardCard, ProgressBar, StatusBadge } from "@/components/ui/crm";
import { accessItems, activity, checklist, eligibilityChecks, type HandoverCase, type HandoverStatus } from "./handover-data";
export function HandoverNavigation(){const path=useRouterState({select:s=>s.location.pathname});const items=[{label:"Overview",to:"/handover" as const,active:path==="/handover"||path==="/handover/"},{label:"Cases",to:"/handover/cases" as const,active:path.startsWith("/handover/cases")||/^\/handover\/HND-/.test(path)||path.startsWith("/handover/create")},{label:"Calendar",to:"/handover/calendar" as const,active:path.startsWith("/handover/calendar")||path.startsWith("/handover/appointments")},{label:"Reports",to:"/handover/reports" as const,active:path.startsWith("/handover/reports")}];return <nav aria-label="Handover areas" className="mb-5 flex gap-1 overflow-x-auto border-b border-border">{items.map(i=><Link key={i.label} to={i.to} className={`shrink-0 border-b-2 px-3 pb-2 text-[13px] font-semibold ${i.active?"border-primary text-primary":"border-transparent text-muted-foreground hover:text-foreground"}`}>{i.label}</Link>)}</nav>}
export function HandoverStatusBadge({status}:{status:HandoverStatus|string}){const value=status.toLowerCase();const tone=value.includes("complete")||value.includes("cleared")||value.includes("acknowledged")||value==="pass"?"success":value.includes("cancel")||value.includes("not eligible")||value.includes("issue")||value.includes("rejected")||value.includes("overdue")?"danger":value.includes("pending")||value.includes("hold")||value.includes("rectification")?"warning":"info";return <StatusBadge tone={tone}>{status}</StatusBadge>}
export function HandoverSummary({record:r}:{record:HandoverCase}){return <CompactMetrics items={[{label:"Finance",value:r.finance,detail:r.financeCertificate,icon:<CircleDollarSign/>},{label:"Payment",value:r.payment,detail:r.paymentAccount,icon:<FileCheck2/>},{label:"Snagging",value:`${r.issues} issues`,detail:`${r.openIssues} open`,icon:<Wrench/>},{label:"Appointment",value:r.appointment,detail:"Next scheduled",icon:<CalendarDays/>},{label:"Handover",value:r.status,detail:r.updated,icon:<KeyRound/>}]}/>}
export function HandoverProcess({status}:{status:HandoverStatus}){const stages=["Eligibility","Notice","Snagging","Rectification","Final Appointment","Complete"];const map:Record<string,number>={"Not Started":0,"Eligibility Review":0,"Not Eligible":0,"Ready for Handover":1,"Notice Pending":1,"Notice Sent":2,"Appointment Scheduled":2,"Snagging Scheduled":2,"Snagging In Progress":2,"Rectification Required":3,"Reinspection Required":3,"Ready for Final Handover":4,"Handover Scheduled":4,"Handover In Progress":4,"Completed":6,"On Hold":2,"Cancelled":0};const current=map[status]??0;return <DashboardCard className="overflow-x-auto p-4"><div className="flex min-w-[690px] items-center">{stages.map((s,i)=><div key={s} className="contents"><div className="flex shrink-0 flex-col items-center gap-1"><span className={`grid size-7 place-items-center rounded-full border text-[10px] ${i<current?"border-success bg-success-soft text-success":i===current?"border-primary bg-primary text-primary-foreground":"border-border bg-surface text-muted-foreground"}`}>{i<current?<Check size={13}/>:i+1}</span><span className="text-[10px] text-muted-foreground">{s}</span></div>{i<stages.length-1&&<span className={`mx-2 mb-4 h-px min-w-8 flex-1 ${i<current?"bg-success":"bg-border"}`}/>}</div>)}</div></DashboardCard>}
export function EligibilityChecklist(){return <DashboardCard className="overflow-hidden"><div className="p-4"><h2 className="text-lg font-bold">Eligibility checklist</h2><p className="text-xs text-muted-foreground">Configurable checks use the latest linked CRM records.</p></div><SimpleTable headers={["Check","Result","Evidence"]} rows={eligibilityChecks} badges={[1]}/></DashboardCard>}
export function FinanceClearance({record:r}:{record:HandoverCase}){return <DashboardCard className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-bold">Finance clearance</h2><p className="text-xs text-muted-foreground">Balances are maintained in Payment 360.</p></div><HandoverStatusBadge status={r.finance}/></div><div className="mt-4"><InfoGrid items={[ ["Sale value","AED 1,225,000"],["Received","AED 1,225,000"],["Outstanding","AED 0"],["Overdue","AED 0"],["Reference",r.financeCertificate],["Cleared by","Finance Manager"],["Date","26 Sep 2026"],["Certificate","Finance-Clearance-A1204.pdf"] ]}/></div><div className="mt-4 flex flex-wrap gap-2"><Link to="/payments/accounts/$accountId" params={{accountId:r.paymentAccount}} className="text-sm font-semibold text-primary">View payment account</Link><span className="text-border">·</span><button className="text-sm font-semibold text-primary">Preview certificate</button><span className="text-border">·</span><button className="text-sm font-semibold text-primary">Download</button></div></DashboardCard>}
export function InspectionSummary(){return <CompactMetrics items={[{label:"Total issues",value:"12",detail:"SNG-2026-00218",icon:<SearchCheck/>},{label:"Open",value:"3",detail:"Requires action",icon:<Wrench/>},{label:"In progress",value:"4",detail:"Assigned teams",icon:<ClipboardCheck/>},{label:"Ready for review",value:"2",detail:"Awaiting inspector",icon:<FileCheck2/>},{label:"Closed",value:"3",detail:"Verified",icon:<Check/>}]}/>}
export function ChecklistSummary(){return <div className="grid gap-4 xl:grid-cols-[1.45fr_1fr]"><DashboardCard className="overflow-hidden"><div className="p-4"><h2 className="text-lg font-bold">Handover checklist</h2><p className="text-xs text-muted-foreground">Items and applicability are configurable per project.</p></div><SimpleTable headers={["Item","Status","Completed by","Notes"]} rows={checklist} badges={[1]} /></DashboardCard><DashboardCard className="overflow-hidden"><div className="p-4"><h2 className="text-lg font-bold">Keys and access items</h2><p className="text-xs text-muted-foreground">Quantities are configurable.</p></div><SimpleTable headers={["Item","Quantity","Status","Prepared by"]} rows={accessItems} badges={[2]}/></DashboardCard></div>}
export function HandoverActivity(){return <DashboardCard className="p-5"><h2 className="text-lg font-bold">Handover activity</h2><div className="mt-4"><Timeline items={activity.slice(0,8).map(row=>({icon:Check,time:row[0]??"—",title:row[1]??"Activity",detail:row[2]??"—"}))}/></div></DashboardCard>}
export function Pipeline(){const rows=[["Eligibility",38,44],["Notice",31,36],["Snagging",14,16],["Rectification",6,7],["Final Appointment",18,21],["Handover Complete",86,100]] as const;return <DashboardCard className="p-5"><h2 className="text-lg font-bold">Handover pipeline</h2><div className="mt-4 space-y-3">{rows.map(([label,count,pct])=><div key={label}><div className="mb-1 flex justify-between text-xs"><span>{label}</span><strong>{count}</strong></div><ProgressBar value={pct}/></div>)}</div></DashboardCard>}
