export type HandoverStatus="Not Started"|"Eligibility Review"|"Not Eligible"|"Ready for Handover"|"Notice Pending"|"Notice Sent"|"Appointment Scheduled"|"Snagging Scheduled"|"Snagging In Progress"|"Rectification Required"|"Reinspection Required"|"Ready for Final Handover"|"Handover Scheduled"|"Handover In Progress"|"Completed"|"On Hold"|"Cancelled";
export type HandoverCase={id:string;customer:string;customerId:string;jointPurchasers:string;project:string;building:string;unit:string;unitId:string;spa:string;oqood:string;paymentAccount:string;financeCertificate:string;finance:"Cleared"|"Pending";payment:"Cleared"|"Pending";snagging:string;issues:number;openIssues:number;appointment:string;status:HandoverStatus;owner:string;updated:string;notice:string;resale:string};
export const handoverCases:HandoverCase[]=[
{id:"HND-2026-00182",customer:"Sarah Ahmed",customerId:"CU-2026-00482",jointPurchasers:"Omar Ahmed · 50%",project:"Horizon Residences",building:"Tower A",unit:"A-1204",unitId:"UNT-HR-A-1204",spa:"SPA-2026-00142",oqood:"OQD-2026-00108",paymentAccount:"ACC-2026-00482",financeCertificate:"FC-2026-00412",finance:"Cleared",payment:"Cleared",snagging:"Rectification",issues:12,openIssues:3,appointment:"30 Sep · 10:00 AM",status:"Rectification Required",owner:"Layla Noor",updated:"Today",notice:"Viewed",resale:"RSL-2026-00042 · NOC Approval"},
{id:"HND-2026-00181",customer:"Mohammed Al Farsi",customerId:"CU-2026-00465",jointPurchasers:"None",project:"Green Park",building:"Building B",unit:"B-0806",unitId:"UNT-GP-B-0806",spa:"SPA-2026-00141",oqood:"OQD-2026-00107",paymentAccount:"ACC-2026-00465",financeCertificate:"—",finance:"Pending",payment:"Pending",snagging:"Not started",issues:0,openIssues:0,appointment:"—",status:"Eligibility Review",owner:"Ahmed Malik",updated:"Yesterday",notice:"Not Generated",resale:"None"},
{id:"HND-2026-00179",customer:"Aisha Rahman",customerId:"CU-2026-00479",jointPurchasers:"None",project:"Horizon Residences",building:"Tower A",unit:"A-1402",unitId:"UNT-HR-A-1402",spa:"SPA-2026-00139",oqood:"OQD-2026-00102",paymentAccount:"ACC-2026-00479",financeCertificate:"FC-2026-00408",finance:"Cleared",payment:"Cleared",snagging:"Complete",issues:7,openIssues:0,appointment:"04 Oct · 2:00 PM",status:"Ready for Final Handover",owner:"Layla Noor",updated:"23 Sep",notice:"Acknowledged",resale:"None"},
{id:"HND-2026-00164",customer:"Blue Crest Holdings LLC",customerId:"CU-2026-00472",jointPurchasers:"Daniel Thomas · Authorized representative",project:"Green Park",building:"Building B",unit:"B-0806",unitId:"UNT-GP-B-0806",spa:"SPA-2026-00136",oqood:"OQD-2026-00096",paymentAccount:"ACC-2026-00472",financeCertificate:"FC-2026-00394",finance:"Cleared",payment:"Cleared",snagging:"Complete",issues:4,openIssues:0,appointment:"04 Oct · 11:00 AM",status:"Completed",owner:"Layla Noor",updated:"04 Oct",notice:"Acknowledged",resale:"RSL-2026-00022 · Completed"}
];
export const eligibilityChecks=[["Customer record","Pass","CU-2026-00482 · Active purchaser"],["Unit record","Pass","UNT-HR-A-1204 · Sold"],["SPA executed","Pass","SPA-2026-00142 · 24 Sep 2026"],["Payment clearance","Pass","ACC-2026-00482 · Cleared snapshot"],["Finance clearance","Pass","FC-2026-00412"],["Required documents","Complete","Current configured set"],["Registration context","Pass","OQD-2026-00108 · Submitted"],["Snagging readiness","Pending","3 issues remain open"]];
export const eligibilityHistory=[["26 Sep · 10:20 AM","Layla Noor","Conditionally eligible","Snagging readiness pending"],["25 Sep · 3:40 PM","Finance Team","Pending","Finance certificate awaited"],["25 Sep · 9:10 AM","System","Pending","Initial linked-record check"]];
export const appointments=[
{id:"APT-2026-00421",handoverId:"HND-2026-00182",type:"Snagging",customer:"Sarah Ahmed",project:"Horizon Residences",unit:"A-1204",date:"28 Sep 2026",time:"10:00 AM",duration:"90 min",team:"Handover Team",status:"Completed",confirmation:"Confirmed",location:"Horizon Residences · Unit A-1204"},
{id:"APT-2026-00428",handoverId:"HND-2026-00182",type:"Reinspection",customer:"Sarah Ahmed",project:"Horizon Residences",unit:"A-1204",date:"30 Sep 2026",time:"10:00 AM",duration:"60 min",team:"Technical Team",status:"Confirmed",confirmation:"Confirmed",location:"Horizon Residences · Unit A-1204"},
{id:"APT-2026-00436",handoverId:"HND-2026-00179",type:"Final Handover",customer:"Aisha Rahman",project:"Horizon Residences",unit:"A-1402",date:"04 Oct 2026",time:"2:00 PM",duration:"60 min",team:"Layla Noor",status:"Scheduled",confirmation:"Invitation delivered",location:"Horizon Residences · Handover Suite"}
];
export const snagIssues=[
{id:"SNG-I-001",inspectionId:"SNG-2026-00218",title:"Bedroom door alignment",category:"Doors / Windows",severity:"Medium",status:"In Progress",team:"Contractor Team A",target:"30 Sep 2026",location:"Primary bedroom",description:"Door edge catches against frame when closing.",evidence:"door-alignment-01.jpg",workNotes:"Hinge adjustment underway",overdue:""},
{id:"SNG-I-002",inspectionId:"SNG-2026-00218",title:"Kitchen cabinet finish",category:"Kitchen",severity:"Low",status:"Ready for Review",team:"Fit-out Team",target:"29 Sep 2026",location:"Kitchen island",description:"Minor surface mark on lower cabinet panel.",evidence:"cabinet-finish-02.jpg",workNotes:"Panel replaced; awaiting inspection",overdue:"1 day overdue"},
{id:"SNG-I-003",inspectionId:"SNG-2026-00218",title:"Bathroom mixer pressure",category:"Plumbing",severity:"High",status:"Open",team:"MEP Team",target:"28 Sep 2026",location:"Guest bathroom",description:"Water pressure below expected operational level.",evidence:"pressure-reading.pdf",workNotes:"Diagnostic visit scheduled",overdue:"2 days overdue"},
{id:"SNG-I-004",inspectionId:"SNG-2026-00218",title:"Living room paint touch-up",category:"Finishes",severity:"Low",status:"Closed",team:"Contractor Team A",target:"28 Sep 2026",location:"Living room east wall",description:"Small paint inconsistency near window reveal.",evidence:"paint-before-after.jpg",workNotes:"Accepted on reinspection",overdue:""}
];
export const inspectionSections=[["General","2","1 open"],["Living Area","2","Complete"],["Bedrooms","2","1 in progress"],["Bathrooms","2","1 open"],["Kitchen","1","Ready for review"],["Doors / Windows","1","In progress"],["Electrical","1","Complete"],["Plumbing","1","Open"],["Finishes","2","1 closed"],["Other","0","No issues"]];
export const reportVersions=[["Version 2","Post-rectification reinspection","02 Oct 2026","Current","Preview · Download"],["Version 1","Initial inspection","28 Sep 2026","Superseded","Preview · Download"]];
export const checklist=[["Customer identity verified","Complete","Layla Noor · 04 Oct, 10:05 AM","Identity matched"],["Finance clearance confirmed","Complete","Finance Team · 26 Sep, 2:30 PM","FC-2026-00412"],["Required documents available","Complete","Layla Noor · 04 Oct, 10:08 AM","Configured set complete"],["Snagging completed","Complete","Technical Team · 03 Oct, 4:20 PM","12 / 12 closed"],["Keys prepared","Complete","Layla Noor · 04 Oct, 10:12 AM","Quantity confirmed"],["Access items prepared","Complete","Layla Noor · 04 Oct, 10:12 AM","Configured quantities"],["Customer acknowledgement ready","Pending","—","Awaiting purchaser"],["Final appointment completed","Pending","—","04 Oct · 2:00 PM"]];
export const accessItems=[["Main keys","2","Prepared","Layla Noor"],["Additional keys","1","Prepared","Layla Noor"],["Access cards","2","Prepared","Security Team"],["Parking access","1","Prepared","Security Team"]];
export const handoverDocuments=[["Handover-Notice-A1204-v1.pdf","Handover Notice","v1","Viewed","26 Sep 2026","Preview · Download"],["Finance-Clearance-A1204.pdf","Finance Clearance","v1","Approved","26 Sep 2026","Preview · Download"],["Snagging-Report-SNG-2026-00218-v2.pdf","Snagging Report","v2","Current","02 Oct 2026","Preview · Download"],["Rectification-Evidence-A1204.zip","Rectification evidence","v1","Complete","02 Oct 2026","Preview"],["Key-Handover-A1204.pdf","Key Handover Document","v1","Draft","04 Oct 2026","Preview · Send"],["Customer-Acknowledgement-A1204.pdf","Acknowledgement","v1","Pending","—","View status"]];
export const acknowledgements=[["Sarah Ahmed","Primary purchaser","Acknowledged","04 Oct · 2:48 PM","Electronic signature"],["Omar Ahmed","Joint purchaser","Pending","Reminder sent","Digital acknowledgement"]];
export const communications=[["Handover notice sent","Email","Viewed","Sarah Ahmed · Omar Ahmed","26 Sep · 3:05 PM"],["Snagging invitation","Email","Confirmed","Sarah Ahmed","27 Sep · 9:00 AM"],["Appointment reminder","WhatsApp","Delivered","Sarah Ahmed","27 Sep · 5:00 PM"],["Snag report shared","Email","Viewed","Sarah Ahmed","28 Sep · 4:30 PM"],["Rectification update","Email","Delivered","Sarah Ahmed","30 Sep · 3:15 PM"],["Reinspection schedule","SMS","Queued · integration required","Sarah Ahmed","30 Sep · 9:00 AM"],["Acknowledgement request","Signature platform","Sent","Omar Ahmed","04 Oct · 2:50 PM"]];
export const activity=[
["04 Oct · 2:48 PM","Customer acknowledged","Sarah Ahmed · electronic signature"],["04 Oct · 2:35 PM","Key handover document generated","Version 1"],["04 Oct · 2:20 PM","Checklist completed","6 of 8 items"],["03 Oct · 4:20 PM","Snagging completed","Technical Team · 12 issues verified"],["02 Oct · 11:10 AM","Reinspection completed","2 accepted · 1 returned"],["30 Sep · 3:15 PM","Rectification update shared","Email delivered"],["28 Sep · 1:30 PM","12 snag issues recorded","SNG-2026-00218"],["28 Sep · 10:00 AM","Inspection started","Handover Team"],["27 Sep · 9:00 AM","Snagging appointment scheduled","APT-2026-00421"],["26 Sep · 3:05 PM","Handover notice sent","Email delivered"],["26 Sep · 2:30 PM","Finance clearance verified","FC-2026-00412"],["25 Sep · 9:00 AM","Handover case created","Layla Noor"]
];
export const auditRows=[["04 Oct · 2:48 PM","Sarah Ahmed","Acknowledgement status","Viewed","Acknowledged","Electronic signature"],["04 Oct · 2:20 PM","Layla Noor","Checklist progress","5 / 8","6 / 8","Keys prepared"],["03 Oct · 4:20 PM","Technical Team","Snagging status","Reinspection Required","Complete","All required issues verified"],["02 Oct · 11:10 AM","Handover Team","Issue SNG-I-002","Ready for Review","Closed","Accepted on reinspection"],["30 Sep · 3:15 PM","Contractor Team A","Target date","29 Sep","30 Sep","Access coordinated"],["28 Sep · 1:30 PM","Handover Team","Inspection status","In Progress","Completed","12 issues recorded"],["26 Sep · 2:30 PM","Finance Team","Finance clearance","Pending","Cleared","FC-2026-00412"]];
export const projectHandover=[["Horizon Residences","18","7","3","9","42"],["Green Park","12","5","2","6","31"],["Creek Vista","8","2","1","3","13"]];
export const completedHandovers=[["HND-2026-00164","Blue Crest Holdings LLC","Green Park · B-0806","04 Oct 2026","Cleared","Complete","Received","Layla Noor"],["HND-2026-00158","Aisha Rahman","Creek Vista · C-0603","02 Oct 2026","Cleared","Complete","Received","Ahmed Malik"]];
