export type SpaStatus="Draft"|"Pending Legal Review"|"Pending Management Approval"|"Returned"|"Approved"|"Sent to Customer"|"Awaiting Signature"|"Partially Signed"|"Executed"|"Amendment Pending"|"Cancelled"|"Terminated";
export type SpaRecord={id:string;customer:string;customerId:string;type:"Individual"|"Company";project:string;unit:string;unitId:string;reservation:string;offer:string;eoi:string;price:number;approval:string;signature:string;status:SpaStatus;updated:string;executed?:string;salesperson:string;broker:string;template:string;version:number};
export const spas:SpaRecord[]=[
  {id:"SPA-2026-00142",customer:"Sarah Ahmed",customerId:"CU-2026-00482",type:"Individual",project:"Horizon Residences",unit:"A-1204",unitId:"UNT-HR-A-1204",reservation:"RSV-2026-00182",offer:"SO-2026-00482",eoi:"EOI-2026-00184",price:1225000,approval:"Approved",signature:"Signed",status:"Executed",updated:"24 Sep 2026",executed:"24 Sep 2026",salesperson:"Omar Khan",broker:"Direct",template:"Standard Residential SPA",version:2},
  {id:"SPA-2026-00141",customer:"Mohammed Al Farsi",customerId:"CU-2026-00465",type:"Individual",project:"Green Park",unit:"B-0806",unitId:"UNT-GP-B-0806",reservation:"RSV-2026-00180",offer:"SO-2026-00466",eoi:"EOI-2026-00168",price:980000,approval:"Pending Legal",signature:"Not sent",status:"Pending Legal Review",updated:"Today",salesperson:"Omar Khan",broker:"Hassan Ali · Elite Properties",template:"Standard Residential SPA",version:1},
  {id:"SPA-2026-00139",customer:"Aisha Rahman",customerId:"CU-2026-00479",type:"Individual",project:"Horizon Residences",unit:"A-1402",unitId:"UNT-HR-A-1402",reservation:"RSV-2026-00181",offer:"SO-2026-00479",eoi:"EOI-2026-00179",price:1420000,approval:"Approved",signature:"Partially signed",status:"Partially Signed",updated:"Yesterday",salesperson:"Layla Noor",broker:"Direct",template:"Investor SPA",version:1},
  {id:"SPA-2026-00136",customer:"Blue Crest Holdings LLC",customerId:"CU-2026-00472",type:"Company",project:"Green Park",unit:"B-0806",unitId:"UNT-GP-B-0806",reservation:"RSV-2026-00174",offer:"SO-2026-00461",eoi:"EOI-2026-00159",price:980000,approval:"Returned",signature:"Not sent",status:"Returned",updated:"22 Sep 2026",salesperson:"Ahmed Malik",broker:"Daniel Thomas · Prime Gate Realty",template:"Corporate Purchaser SPA",version:2},
];
export const spaVersions=[["Version 2","25 Sep · 11:30 AM","Omar Khan","Purchaser address corrected","Current","Preview · Compare · Download"],["Version 1","24 Sep · 10:00 AM","Omar Khan","Initial SPA","Superseded","Preview · Compare · Download"]];
export const spaAudit=[["24 Sep · 4:27 PM","System","SPA status","Awaiting Signature","Executed","All purchasers signed"],["24 Sep · 4:26 PM","Omar Ahmed","Signature status","Pending","Signed","Electronic signature"],["24 Sep · 4:10 PM","Sarah Ahmed","Signature status","Pending","Signed","Electronic signature"],["24 Sep · 2:05 PM","Ahmed Malik","Management approval","Pending","Approved","Commercial terms confirmed"],["24 Sep · 12:40 PM","Legal Team","Legal review","Pending","Approved","No legal exceptions"],["24 Sep · 10:15 AM","Omar Khan","SPA submitted","Draft","Pending Legal Review","Version 1"]];
export const amendments=[["ADD-2026-00018","Purchaser detail update","25 Sep 2026","Pending approval","Version 1","View"]];
export function formatAed(value:number){return `AED ${value.toLocaleString("en-AE")}`}