import { AlertTriangle, Check, Clock, FileText, LockKeyhole, type LucideIcon } from "lucide-react";
import type { ReactNode } from "react";
import { Button, DashboardCard, MetricCard, StatusBadge } from "@/components/ui/crm";

export type Tone="success"|"warning"|"danger"|"info"|"neutral";
export function toneFor(value:string):Tone { if(/Active|Approved|Valid|Verified|Paid|Complete|Eligible|Ready/.test(value))return "success"; if(/Expir|Pending|hold|Due/.test(value))return "warning"; if(/Reject|Suspend|Failed|Missing/.test(value))return "danger"; if(/Draft|Inactive|Not ready/.test(value))return "neutral"; return "info"; }
export function CompactMetrics({items}:{items:{label:string;value:string;detail:string;icon:ReactNode}[]}){return <DashboardCard className="grid overflow-hidden sm:grid-cols-2 xl:grid-cols-4">{items.map((item,i)=><MetricCard key={item.label} className={`${i<items.length-1?"border-b border-border sm:border-r xl:border-b-0":""} py-4`}><div className="flex gap-3"><span className="mt-1 text-muted-foreground [&>svg]:size-5">{item.icon}</span><div><p className="text-xs text-muted-foreground">{item.label}</p><strong className="block text-[27px] leading-tight">{item.value}</strong><span className="text-xs text-muted-foreground">{item.detail}</span></div></div></MetricCard>)}</DashboardCard>}
export function InfoGrid({items,columns="lg:grid-cols-3"}:{items:[string,string][];columns?:string}){return <div className={`grid gap-5 sm:grid-cols-2 ${columns}`}>{items.map(([label,value])=><div key={label}><span className="block text-[11px] text-muted-foreground">{label}</span><strong className="mt-1 block text-sm font-medium">{value}</strong></div>)}</div>}
export function PanelHeader({title,subtitle,action,onAction}:{title:string;subtitle?:string;action?:string;onAction?:()=>void}){return <div className="flex flex-wrap items-start justify-between gap-3 p-4"><div><h2 className="text-lg font-bold">{title}</h2>{subtitle&&<p className="mt-1 text-xs text-muted-foreground">{subtitle}</p>}</div>{action&&<Button variant="secondary" className="h-9" onClick={onAction}>{action}</Button>}</div>}
export function SimpleTable({headers,rows,badges=[],empty="No records yet"}:{headers:string[];rows:string[][];badges?:number[];empty?:string}){return rows.length?<div className="overflow-x-auto"><table className="w-full min-w-[760px] border-collapse text-left text-xs"><thead className="bg-muted text-muted-foreground"><tr>{headers.map(h=><th key={h} className="p-3 font-medium">{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={`${row[0]}-${i}`} className="border-b border-border hover:bg-muted/40">{row.map((cell,j)=><td key={`${cell}-${j}`} className="p-3">{badges.includes(j)?<StatusBadge tone={toneFor(cell)}>{cell}</StatusBadge>:j===0?<strong>{cell}</strong>:cell}</td>)}</tr>)}</tbody></table></div>:<div className="grid min-h-44 place-items-center text-center"><div><strong>{empty}</strong><p className="mt-1 text-xs text-muted-foreground">Records will appear here when available.</p></div></div>}
export function ComplianceCard({kind="agency"}:{kind?:"agency"|"broker"}){const rows:string[][]=kind==="agency"?[["Documents","6 / 6 complete","Verified"],["Trade license","14 Feb 2027","Valid"],["Agreement","31 Dec 2026","Valid"],["Verification","Approved","Approved"]]:[["Documents","4 / 4 complete","Verified"],["Registration","18 Jan 2027","Valid"],["Authorization","Agency confirmed","Valid"],["Verification","Approved","Approved"]];return <DashboardCard className="p-4"><div className="flex items-center gap-2"><Check className="text-success" size={17}/><h2 className="text-sm font-bold">Compliance summary</h2></div><div className="mt-3 divide-y divide-border">{rows.map(([label="",value="",status=""]) =><div key={label} className="flex items-center gap-3 py-2.5 text-xs"><span className="text-muted-foreground">{label}</span><strong className="ml-auto">{value}</strong><StatusBadge tone={toneFor(status)}>{status}</StatusBadge></div>)}</div><p className="mt-3 border-t border-border pt-3 text-xs text-muted-foreground">Next expiry: <strong className="text-foreground">{kind==="agency"?"Trade License · 14 Feb 2027":"Broker Registration · 18 Jan 2027"}</strong></p></DashboardCard>}
export function AlertItem({text,tone="warning"}:{text:string;tone?:Tone}){const Icon=tone==="warning"||tone==="danger"?AlertTriangle:Clock;return <div className={`flex items-center gap-2 rounded-md p-2.5 text-xs ${tone==="danger"?"bg-danger-soft text-danger":tone==="warning"?"bg-warning-soft text-warning":"bg-info-soft text-info"}`}><Icon size={14}/>{text}</div>}
export function RestrictedBank(){return <DashboardCard className="p-5"><div className="flex items-center gap-2"><LockKeyhole size={16} className="text-muted-foreground"/><h2 className="text-lg font-bold">Bank details</h2><StatusBadge tone="neutral">Restricted</StatusBadge></div><p className="mt-1 text-xs text-muted-foreground">Visible to authorized Finance and Administrator roles.</p><div className="mt-5"><InfoGrid columns="lg:grid-cols-2" items={[["Bank name","Emirates NBD"],["Account name","Elite Properties LLC"],["Account number","•••• •••• 2914"],["IBAN","AE•• •••• •••• •••• 4821"],["SWIFT","EBILAEAD"],["Currency","AED"]]}/></div></DashboardCard>}
export function Timeline({items}:{items:{icon:LucideIcon;title:string;detail:string;time:string}[]}){return <div className="space-y-0">{items.map(({icon:Icon,title,detail,time},i)=><div key={title} className="relative flex gap-3 pb-5 last:pb-0"><span className="relative z-10 grid size-8 shrink-0 place-items-center rounded-full bg-muted text-muted-foreground"><Icon size={14}/></span>{i<items.length-1&&<span className="absolute left-[15px] top-8 h-full w-px bg-border"/>}<div className="min-w-0 flex-1"><div className="flex flex-wrap justify-between gap-2"><strong className="text-sm">{title}</strong><span className="text-[11px] text-muted-foreground">{time}</span></div><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div></div>)}</div>}
export function AttributionChain(){const nodes=[["Agency","Elite Properties","AG-0084"],["Broker","Hassan Ali","BR-0184"],["Lead","Sarah Ahmed","LD-2026-01248"],["Customer","Sarah Ahmed","CU-2026-00482"],["Property","Horizon Residences","Unit A-1204"],["Reservation","Future module","Not yet available"]];return <div className="overflow-x-auto"><div className="flex min-w-[920px] items-center gap-2 py-3">{nodes.map(([type,name,id],i)=><div key={type} className="contents"><div className={`min-w-36 rounded-card border p-3 ${i===nodes.length-1?"border-dashed border-border bg-muted":"border-border bg-surface"}`}><span className="text-[10px] uppercase text-muted-foreground">{type}</span><strong className="mt-1 block text-sm">{name}</strong><span className="text-[11px] text-muted-foreground">{id}</span></div>{i<nodes.length-1&&<span className="text-muted-foreground">→</span>}</div>)}</div></div>}
export function CommissionCalculation(){return <DashboardCard className="p-5"><h2 className="text-lg font-bold">Commission calculation</h2><div className="mt-5 grid items-center gap-4 md:grid-cols-[1fr_auto_1fr_auto_1fr]"><Calc label="Sale value" value="AED 1,250,000"/><strong className="text-muted-foreground">×</strong><Calc label="Commission rate" value="3.00%"/><strong className="text-muted-foreground">=</strong><Calc label="Gross commission" value="AED 37,500" emphasis/></div><div className="mt-5 grid gap-3 border-t border-border pt-4 sm:grid-cols-3"><Calc label="Adjustments" value="AED 0"/><Calc label="Agency share" value="AED 30,000"/><Calc label="Broker share" value="AED 7,500"/></div><p className="mt-4 text-xs text-muted-foreground">Applied structure: <strong className="text-foreground">Horizon Residences Standard Broker Commission</strong> · Effective 01 Jan 2026</p></DashboardCard>}
function Calc({label,value,emphasis=false}:{label:string;value:string;emphasis?:boolean}){return <div className={emphasis?"rounded-md bg-success-soft p-3":""}><span className="text-[11px] text-muted-foreground">{label}</span><strong className={`block ${emphasis?"text-xl text-success":"text-lg"}`}>{value}</strong></div>}
export function DocumentIcon(){return <span className="grid size-8 place-items-center rounded-md bg-muted text-muted-foreground"><FileText size={15}/></span>}
