import { useState, type FormEvent, type ReactNode } from "react";
import { AlertTriangle, FileUp, Search } from "lucide-react";
import { z } from "zod";
import { Button, FieldError, FormField, Input, ModalShell, SelectMenu, StatusBadge, Textarea } from "@/components/ui/crm";

type OpenProps={open:boolean;onOpenChange:(open:boolean)=>void}; type Errors=Record<string,string>;
const phone=/^(?:\+971|00971|0)?[\s-]*5(?:[\s-]*\d){8}$/;
const brokerSchema=z.object({agency:z.string().trim().min(1,"Agency is required").max(120),firstName:z.string().trim().min(1,"First name is required").max(60),lastName:z.string().trim().min(1,"Last name is required").max(60),mobile:z.string().trim().regex(phone,"Enter a valid UAE mobile number"),email:z.string().trim().email("Enter a valid email address").max(255),registration:z.string().trim().min(1,"Registration number is required").max(80),expiry:z.string().min(1,"Registration expiry is required")});
export function BrokerRegistrationModal({open,onOpenChange}:OpenProps){const [errors,setErrors]=useState<Errors>({});const [duplicate,setDuplicate]=useState(false);function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));const parsed=brokerSchema.safeParse(values);if(!parsed.success){setErrors(Object.fromEntries(parsed.error.issues.map(x=>[String(x.path[0]),x.message])));return}setErrors({});const mobile=String(values['mobile']??"").replace(/\D/g,"");if(mobile.endsWith("502489912")||String(values['registration']).toUpperCase()==="RERA-BR-18424"){setDuplicate(true);return}onOpenChange(false)}return <ModalShell open={open} onOpenChange={onOpenChange} title="Register individual broker"><form onSubmit={submit}><div className="grid max-h-[65vh] gap-4 overflow-y-auto pr-1 sm:grid-cols-2"><Field name="agency" label="Agency *" error={errors['agency']} placeholder="Elite Properties"/><Field name="firstName" label="First name *" error={errors['firstName']}/><Field name="lastName" label="Last name *" error={errors['lastName']}/><Field name="mobile" label="Mobile *" error={errors['mobile']} placeholder="+971 50 000 0000"/><Field name="email" label="Email *" type="email" error={errors['email']}/><Field name="nationality" label="Nationality"/><Field name="registration" label="Broker registration number *" error={errors['registration']}/><Field name="expiry" label="Registration expiry *" type="date" error={errors['expiry']}/><Field name="eid" label="Emirates ID"/><Field name="passport" label="Passport number"/><Field name="authorization" label="Authorization details"/><Field name="relationship" label="Relationship start date" type="date"/><div className="sm:col-span-2"><UploadChecklist items={["Passport","Emirates ID","Broker Registration","Authorization"]}/></div>{duplicate&&<div className="sm:col-span-2 rounded-card border border-danger bg-danger-soft p-4"><div className="flex gap-3"><AlertTriangle size={18} className="text-danger"/><div><strong>Possible broker already exists</strong><p className="mt-1 text-xs text-muted-foreground">Hassan Ali · BR-0184 · Elite Properties</p><div className="mt-3 flex gap-2"><Button type="button" variant="secondary" className="h-9">View existing</Button><Button type="button" className="h-9" onClick={()=>onOpenChange(false)}>Continue if authorized</Button></div></div></div></div>}</div><Actions close={()=>onOpenChange(false)} secondary="Save draft" primary="Register broker"/></form></ModalShell>}
export function TransferBrokerModal({open,onOpenChange}:OpenProps){return <ModalShell open={open} onOpenChange={onOpenChange} title="Transfer broker"><p className="text-sm text-muted-foreground">Current agency: <strong className="text-foreground">Elite Properties</strong></p><div className="mt-4 grid gap-4 sm:grid-cols-2"><FormField label="New agency"><SelectMenu label="Search agency" items={["Prime Gate Realty","Urban Key Real Estate","Crestline Brokers LLC"]}/></FormField><FormField label="Effective date"><Input type="date"/></FormField><div className="sm:col-span-2"><FormField label="Reason *"><Textarea required maxLength={500}/></FormField></div></div><Warning>Historical sales and commissions remain linked to their original agency attribution.</Warning><Actions close={()=>onOpenChange(false)} primary="Transfer"/></ModalShell>}
export function ChangeAttributionModal({open,onOpenChange}:OpenProps){return <ModalShell open={open} onOpenChange={onOpenChange} title="Change broker attribution"><div className="grid gap-4 sm:grid-cols-2"><Read label="Current agency" value="Elite Properties"/><Read label="Current broker" value="Hassan Ali"/><FormField label="New agency"><SelectMenu label="Select agency" items={["Prime Gate Realty","Urban Key Real Estate"]}/></FormField><FormField label="New broker"><SelectMenu label="Select broker" items={["Ahmed Raza","Daniel Thomas"]}/></FormField><FormField label="Effective date"><Input type="date"/></FormField><div className="sm:col-span-2"><FormField label="Reason *"><Textarea required maxLength={500}/></FormField></div></div><Warning>Changing broker attribution may affect future commission calculations.</Warning><Actions close={()=>onOpenChange(false)} primary="Update attribution"/></ModalShell>}
export function CommissionAdjustmentModal({open,onOpenChange}:OpenProps){return <ModalShell open={open} onOpenChange={onOpenChange} title="Commission adjustment"><div className="grid gap-4 sm:grid-cols-2"><FormField label="Adjustment type"><SelectMenu label="Increase" items={["Increase","Decrease"]}/></FormField><FormField label="Value method"><SelectMenu label="Amount" items={["Amount","Percentage"]}/></FormField><Field name="amount" label="Amount / percentage" type="number" min="0"/><div className="sm:col-span-2"><FormField label="Reason *"><Textarea required maxLength={500}/></FormField></div><label className="sm:col-span-2 flex h-20 cursor-pointer items-center justify-center gap-2 rounded-card border border-dashed border-border bg-muted text-xs"><FileUp size={16}/>Supporting document<input type="file" className="sr-only"/></label></div><Actions close={()=>onOpenChange(false)} primary="Apply adjustment"/></ModalShell>}
export function ApprovalDecisionModal({open,onOpenChange,decision}:{open:boolean;onOpenChange:(o:boolean)=>void;decision:"Approve"|"Put on hold"|"Reject"}){const reason=decision!=="Approve";return <ModalShell open={open} onOpenChange={onOpenChange} title={`${decision} commission`}><p className="text-sm text-muted-foreground">Commission <strong className="text-foreground">CM-2026-00842 · AED 37,500</strong></p>{reason&&<div className="mt-4"><FormField label="Remarks *"><Textarea required maxLength={500} placeholder={`Reason to ${decision.toLowerCase()}`}/></FormField></div>}<Actions close={()=>onOpenChange(false)} primary={decision}/></ModalShell>}
export function SuspendAgencyModal({open,onOpenChange}:OpenProps){return <ModalShell open={open} onOpenChange={onOpenChange} title="Suspend Elite Properties?"><FormField label="Reason *"><Textarea required maxLength={500}/></FormField><div className="mt-4"><FormField label="Effective date"><Input type="date"/></FormField></div><div className="mt-4 space-y-2 text-sm"><label className="flex gap-2"><input type="checkbox" defaultChecked/>Prevent new lead attribution</label><label className="flex gap-2"><input type="checkbox" defaultChecked/>Prevent new transactions</label><label className="flex gap-2"><input type="checkbox" defaultChecked disabled/>Keep historical records accessible</label></div><Actions close={()=>onOpenChange(false)} primary="Suspend agency"/></ModalShell>}
export function VerificationModal({open,onOpenChange}:OpenProps){const [decision,setDecision]=useState<"Approve"|"Return for correction"|"Reject">("Approve");return <ModalShell open={open} onOpenChange={onOpenChange} title="Agency verification"><p className="text-sm text-muted-foreground">Elite Properties · AG-0084</p><div className="mt-4 divide-y divide-border rounded-card border border-border">{["Company information","Trade license","Registration certificate","Agreement","Authorized contact","Bank details","Required documents"].map((x,i)=><div key={x} className="flex items-center gap-3 p-3 text-sm"><span className="flex-1">{x}</span><StatusBadge tone={i===6?"warning":"success"}>{i===6?"Pending":"Verified"}</StatusBadge></div>)}</div><div className="mt-4"><FormField label="Decision"><SelectMenu label={decision} items={["Approve","Return for correction","Reject"]}/></FormField></div><div className="mt-4"><FormField label="Reviewer remarks"><Textarea required={decision!=="Approve"} maxLength={500} placeholder="Updated Trade License required."/></FormField></div><Actions close={()=>onOpenChange(false)} primary={decision}/></ModalShell>}
function UploadChecklist({items}:{items:string[]}){return <div><p className="mb-2 text-sm font-semibold">Documents</p><div className="grid gap-2 sm:grid-cols-2">{items.map((item,i)=><label key={item} className="flex h-12 items-center gap-2 rounded-md border border-border px-3 text-xs"><FileUp size={15} className="text-muted-foreground"/><span className="flex-1">{item}</span><StatusBadge tone={i<2?"success":"neutral"}>{i<2?"Uploaded":"Missing"}</StatusBadge><input type="file" className="sr-only"/></label>)}</div></div>}
function Field({label,error,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string;error?:string|undefined}){return <FormField label={label}><Input {...props} maxLength={255}/><FieldError>{error}</FieldError></FormField>}
function Read({label,value}:{label:string;value:string}){return <div><span className="text-xs text-muted-foreground">{label}</span><strong className="mt-1 block text-sm">{value}</strong></div>}
function Warning({children}:{children:ReactNode}){return <div className="mt-4 flex gap-2 rounded-md bg-warning-soft p-3 text-xs text-warning"><AlertTriangle size={15}/>{children}</div>}
function Actions({close,secondary,primary}:{close:()=>void;secondary?:string;primary:string}){return <div className="mt-5 flex justify-end gap-2"><Button type="button" variant="secondary" onClick={close}>Cancel</Button>{secondary&&<Button type="button" variant="secondary">{secondary}</Button>}<Button type="submit" onClick={close}>{primary}</Button></div>}
