import { useState } from "react";
import { z } from "zod";
import { Button,FieldError,FormField,Input,ModalShell,Textarea } from "@/components/ui/crm";
const schema=z.object({note:z.string().min(5,"Enter at least 5 characters")});
function ActionModal({open,onOpenChange,title,label,children}:{open:boolean;onOpenChange:(v:boolean)=>void;title:string;label:string;children?:React.ReactNode}){const [error,setError]=useState("");return <ModalShell open={open} onOpenChange={onOpenChange} title={title}><form className="space-y-4" onSubmit={e=>{e.preventDefault();const value=new FormData(e.currentTarget).get("note");const result=schema.safeParse({note:value});if(!result.success){setError(result.error.issues[0]?.message??"Required");return}setError("");onOpenChange(false)}}>{children}<FormField label="Notes"><Textarea name="note" placeholder="Add an auditable note"/></FormField><FieldError>{error}</FieldError><div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={()=>onOpenChange(false)}>Cancel</Button><Button type="submit">{label}</Button></div></form></ModalShell>}
export function AssignModal(p:{open:boolean;onOpenChange:(v:boolean)=>void}){return <ActionModal {...p} title="Assign case" label="Assign"><FormField label="Assigned team"><Input defaultValue="Facilities Team" required/></FormField><FormField label="Assigned user"><Input defaultValue="Khalid Abbas" required/></FormField></ActionModal>}
export function EscalateModal(p:{open:boolean;onOpenChange:(v:boolean)=>void}){return <ActionModal {...p} title="Escalate case" label="Escalate"><FormField label="Escalation reason"><Input defaultValue="Repeated issue" required/></FormField><FormField label="Escalate to"><Input defaultValue="Customer Care Manager" required/></FormField></ActionModal>}
export function ResolveModal(p:{open:boolean;onOpenChange:(v:boolean)=>void}){return <ActionModal {...p} title="Resolve case" label="Mark resolved"><FormField label="Resolution category"><Input defaultValue="Repair completed" required/></FormField><FormField label="Resolution summary"><Input defaultValue="Cooling performance restored and tested" required/></FormField></ActionModal>}
export function CloseModal(p:{open:boolean;onOpenChange:(v:boolean)=>void}){return <ActionModal {...p} title="Close case" label="Close case"><FormField label="Customer acknowledgement"><Input defaultValue="Received by email" required/></FormField></ActionModal>}
export function ReopenModal(p:{open:boolean;onOpenChange:(v:boolean)=>void}){return <ActionModal {...p} title="Reopen case" label="Reopen case"><div className="rounded-md bg-warning-soft p-3 text-xs text-warning">Authorized Customer Care Manager action. SLA is recalculated and history is retained.</div></ActionModal>}
