export type CareStatus="New"|"Assigned"|"In Progress"|"Waiting for Customer"|"Waiting for Internal Team"|"Resolved"|"Closed"|"Escalated"|"Reopened";
export type CareCase={id:string;customer:string;customerId:string;project:string;unit:string;unitId:string;type:"Enquiry"|"Complaint"|"Service Request"|"Maintenance"|"Defect"|"Snagging Follow-up"|"Other";subject:string;description:string;priority:"Low"|"Medium"|"High";team:string;assignee:string;sla:string;slaState:"On Track"|"Due Soon"|"At Risk"|"Breached";status:CareStatus;updated:string;created:string;handover:string;handoverDate:string;spa:string;nextAction:string};
export const careCases:CareCase[]=[
{id:"CC-2026-00842",customer:"Sarah Ahmed",customerId:"CU-2026-00482",project:"Horizon Residences",unit:"A-1204",unitId:"UNT-HR-A-1204",type:"Service Request",subject:"Air conditioning issue in master bedroom",description:"Cooling performance in the master bedroom is below the expected level after handover.",priority:"Medium",team:"Customer Care Team",assignee:"Nadia Rahman",sla:"Due in 6h",slaState:"On Track",status:"In Progress",updated:"20 min ago",created:"24 Sep 2026 · 9:10 AM",handover:"HND-2026-00182",handoverDate:"04 Oct 2026",spa:"SPA-2026-00142",nextAction:"Technician visit · Today, 3:00 PM"},
{id:"CC-2026-00841",customer:"Mohammed Al Farsi",customerId:"CU-2026-00465",project:"Green Park",unit:"B-0806",unitId:"UNT-GP-B-0806",type:"Complaint",subject:"Repeated access card activation delay",description:"Customer has followed up twice regarding activation of the second access card.",priority:"High",team:"Customer Care Team",assignee:"Ahmed Malik",sla:"At Risk",slaState:"At Risk",status:"Escalated",updated:"1h ago",created:"23 Sep 2026 · 2:30 PM",handover:"HND-2026-00181",handoverDate:"Pending",spa:"SPA-2026-00141",nextAction:"Management response · Today"},
{id:"CC-2026-00839",customer:"Aisha Rahman",customerId:"CU-2026-00479",project:"Horizon Residences",unit:"A-1402",unitId:"UNT-HR-A-1402",type:"Defect",subject:"Balcony door seal requires review",description:"Minor air gap observed around the balcony door seal.",priority:"Medium",team:"Technical Team",assignee:"Layla Noor",sla:"Due Soon",slaState:"Due Soon",status:"Assigned",updated:"Yesterday",created:"22 Sep 2026 · 11:45 AM",handover:"HND-2026-00179",handoverDate:"04 Oct 2026",spa:"SPA-2026-00139",nextAction:"Site inspection · 26 Sep"},
{id:"CC-2026-00836",customer:"Blue Crest Holdings LLC",customerId:"CU-2026-00472",project:"Green Park",unit:"B-0806",unitId:"UNT-GP-B-0806",type:"Snagging Follow-up",subject:"Kitchen cabinet rectification confirmation",description:"Follow-up linked to original handover snagging issue.",priority:"Low",team:"Handover Team",assignee:"Layla Noor",sla:"Completed",slaState:"On Track",status:"Resolved",updated:"23 Sep",created:"20 Sep 2026 · 10:15 AM",handover:"HND-2026-00164",handoverDate:"04 Oct 2026",spa:"SPA-2026-00136",nextAction:"Customer acknowledgement pending"},
{id:"CC-2026-00830",customer:"Yousef Al Mansoori",customerId:"CU-2026-00488",project:"Creek Vista",unit:"C-0603",unitId:"UNT-CV-C-0603",type:"Enquiry",subject:"Community access and move-in guidance",description:"Customer requested information about community access and move-in procedures.",priority:"Low",team:"Customer Care Team",assignee:"Maya Joseph",sla:"Completed",slaState:"On Track",status:"Closed",updated:"20 Sep",created:"18 Sep 2026 · 9:00 AM",handover:"HND-2026-00158",handoverDate:"02 Oct 2026",spa:"SPA-2026-00131",nextAction:"None"}
];
export const careActivity=[["Today · 1:40 PM","Technician assigned","Facilities Team · Khalid Abbas"],["Today · 11:20 AM","Customer called","Visit availability confirmed"],["Today · 10:05 AM","Status changed","Assigned → In Progress"],["Today · 9:30 AM","SLA calculated","Configured Service Request rule applied"],["Today · 9:10 AM","Case created","Nadia Rahman · Customer Care Team"]];
export const careCommunications=[["Call","Today · 11:20 AM","Nadia Rahman","Technician visit confirmation","Completed","Customer available after 2 PM"],["Email","Today · 9:22 AM","System","Case CC-2026-00842 created","Delivered","Reference and next steps shared"],["WhatsApp","Today · 9:18 AM","Nadia Rahman","Case acknowledgement","Not configured","Channel unavailable; no message sent"]];
export const careDocuments=[["AC-inspection-photo-01.jpg","Issue evidence","Customer Care case","v1","Uploaded","Nadia Rahman · Today"],["Technician-visit-note.pdf","Work note","Service request","v1","Draft","Facilities Team · Today"],["Handover-Acknowledgement.pdf","Handover","HND-2026-00182","v1","Linked","Layla Noor · 04 Oct"]];
export const relatedIssues=[["SNG-I-003","SNG-2026-00218","Bathroom mixer pressure","Closed","HND-2026-00182"],["CC-2026-00836","Snagging follow-up","Kitchen cabinet rectification","Resolved","HND-2026-00164"]];
export const slaTimeline=[["Created","24 Sep · 9:10 AM","—","Complete"],["First response target","24 Sep · 11:10 AM","Responded 9:22 AM","Met"],["Resolution target","30 Sep · 5:00 PM","6h 20m remaining","On Track"],["Escalation checkpoint","Configured rule","Not reached","Pending"]];
export const careAudit=[["24 Sep · 1:40 PM","Nadia Rahman","Assignment","Customer Care Team","Facilities Team","Technician assigned"],["24 Sep · 10:05 AM","Nadia Rahman","Status","Assigned","In Progress","Customer availability confirmed"],["24 Sep · 9:30 AM","System","SLA state","—","On Track","Rule SR-MEDIUM applied"],["24 Sep · 9:10 AM","Nadia Rahman","Case created","—","CC-2026-00842","Post-handover service request"]];
export const projectCare=[["Horizon Residences","42","8","3","76"],["Green Park","28","5","3","44"],["Creek Vista","16","1","1","22"]];
export const careReportRows=[["Service Request","36","21","5","2","18"],["Complaint","19","9","4","4","11"],["Defect","14","8","3","1","6"],["Maintenance","9","6","2","0","4"],["Enquiry","8","3","0","0","7"]];
