import { Link,useRouterState } from "@tanstack/react-router";
import { AlertTriangle,Check,Clock,Headphones,MessageCircle,ShieldAlert } from "lucide-react";
import { careActivity,type CareCase } from "./customer-care-data";
import { CompactMetrics,InfoGrid,Timeline,toneFor } from "@/components/sales/sales-ui";
import { DashboardCard,ProgressBar,StatusBadge } from "@/components/ui/crm";
const links=[{label:"Overview",to:"/customer-care" as const},{label:"Cases",to:"/customer-care/cases" as const},{label:"SLA & escalations",to:"/customer-care/sla" as const},{label:"Reports",to:"/customer-care/reports" as const}];
export function CareNavigation(){const path=useRouterState({select:s=>s.location.pathname});return <div className="mb-5 flex gap-6 overflow-x-auto border-b border-border">{links.map(x=><Link key={x.label} to={x.to} activeOptions={{exact:x.to==="/customer-care"}} className={`-mb-px shrink-0 border-b-2 pb-2 text-xs font-medium ${path===x.to||path.startsWith(`${x.to}/`)?"border-primary text-primary":"border-transparent text-muted-foreground"}`}>{x.label}</Link>)}</div>}
export function CareMetrics(){return <CompactMetrics items={[{label:"Open cases",value:"86",detail:"Across active projects",icon:<Headphones/>},{label:"Due today",value:"18",detail:"Requires action",icon:<Clock/>},{label:"Escalated",value:"7",detail:"Needs attention",icon:<ShieldAlert/>},{label:"Closed this month",value:"142",detail:"Customer care cases",icon:<Check/>}]}/>}
export function CareStatus({value}:{value:string}){return <StatusBadge tone={toneFor(value)}>{value}</StatusBadge>}
export function CaseSummary({record:r}:{record:CareCase}){return <DashboardCard className="grid overflow-hidden sm:grid-cols-2 xl:grid-cols-4"><div className="border-b border-border p-4 sm:border-r"><InfoGrid columns="grid-cols-1" items={[["Case type",r.type],["Priority",r.priority]]}/></div><div className="border-b border-border p-4 xl:border-r"><InfoGrid columns="grid-cols-1" items={[["Assigned team",r.team],["Assigned user",r.assignee]]}/></div><div className="border-b border-border p-4 sm:border-r sm:border-b-0"><InfoGrid columns="grid-cols-1" items={[["SLA",r.sla],["SLA state",r.slaState]]}/></div><div className="p-4"><InfoGrid columns="grid-cols-1" items={[["Last activity",r.updated],["Next action",r.nextAction]]}/></div></DashboardCard>}
export function SlaCard({record:r}:{record:CareCase}){return <DashboardCard className="p-5"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold">Service level agreement</h2><p className="text-xs text-muted-foreground">Applied from the configured {r.type} rule.</p></div><CareStatus value={r.slaState}/></div><div className="mt-5"><ProgressBar value={68}/></div><div className="mt-4"><InfoGrid items={[["Created",r.created],["Target response","24 Sep · 11:10 AM"],["Resolution target","30 Sep · 5:00 PM"],["Elapsed","1d 17h"],["Remaining","6h 20m"],["Escalation","Configured checkpoint"]]}/></div></DashboardCard>}
export function CareTimeline(){return <DashboardCard className="p-5"><h2 className="text-lg font-bold">Recent activity</h2><div className="mt-4"><Timeline items={careActivity.map(x=>({icon:Check,time:x[0]??"—",title:x[1]??"Activity",detail:x[2]??"—"}))}/></div></DashboardCard>}
export function AttentionRow({count,text,to="/customer-care/cases"}:{count:string;text:string;to?:"/customer-care/cases"|"/customer-care/sla"}){return <Link to={to} className="flex items-center gap-3 border-b border-border py-3 last:border-0"><span className="grid size-7 place-items-center rounded-md bg-warning-soft text-xs font-bold text-warning">{count}</span><span className="flex-1 text-xs">{text}</span><AlertTriangle size={14} className="text-muted-foreground"/></Link>}
export function ChannelBadge({channel}:{channel:string}){return <span className="inline-flex items-center gap-1 text-xs"><MessageCircle size={13} className="text-muted-foreground"/>{channel}</span>}
