import { ProformaButton } from "@/components/finance/client-feedback";
import { AlertTriangle, Check, Clock, FileCheck2, RefreshCw, WalletCards } from "lucide-react";
import type { ReactNode } from "react";
import { aed, type ERPStatus, type Installment, type PaymentAccount, type PaymentStatus } from "./payment-data";
import { InfoGrid, SimpleTable, Timeline } from "@/components/sales/sales-ui";
import { Button, DashboardCard, ProgressBar, StatusBadge } from "@/components/ui/crm";
export function PaymentStatusBadge({status}:{status:PaymentStatus|string}){const tone=status==="Paid"||status==="Cleared"?"success":status==="Overdue"?"danger":status==="Due"||status==="Partially Paid"||status==="Payment Pending Verification"?"warning":status==="On Hold"||status==="Unallocated"?"info":"neutral";return <StatusBadge tone={tone}>{status}</StatusBadge>}
export function ERPSyncStatus({status,onRetry}:{status:ERPStatus;onRetry?:()=>void}){const tone=status==="Synced"||status==="Confirmed by ERP"?"success":status==="Failed"?"danger":"warning";return <div className="flex items-center gap-2"><StatusBadge tone={tone}>ERP · {status}</StatusBadge>{status==="Failed"&&onRetry&&<Button variant="ghost" className="h-7 px-2 text-xs" onClick={onRetry}><RefreshCw size={13}/>Retry sync</Button>}</div>}
export function PaymentSummary({account}:{account:PaymentAccount}){const items=[{label:"Sale value",value:aed(account.total),detail:"Approved SPA value",icon:<WalletCards/>},{label:"Received",value:aed(account.received),detail:`${((account.received/account.total)*100).toFixed(1)}% collected`,icon:<Check/>},{label:"Outstanding",value:aed(account.outstanding),detail:"Current balance",icon:<Clock/>},{label:"Overdue",value:aed(account.overdue),detail:account.overdue?"Action required":"Account current",icon:<AlertTriangle/>},{label:"Next installment",value:"AED 245K",detail:account.nextDue,icon:<FileCheck2/>}];return <DashboardCard className="grid overflow-hidden sm:grid-cols-2 xl:grid-cols-5">{items.map((item,i)=><div key={item.label} className={`flex min-w-0 gap-3 p-4 ${i<items.length-1?"border-b border-border sm:border-r xl:border-b-0":""}`}><span className="mt-1 text-muted-foreground [&>svg]:size-4">{item.icon}</span><div className="min-w-0"><span className="text-[11px] text-muted-foreground">{item.label}</span><strong className="block text-xl leading-tight">{item.value}</strong><span className="text-[11px] text-muted-foreground">{item.detail}</span></div></div>)}</DashboardCard>}
export function PaymentProgress({account}:{account:PaymentAccount}){const pct=Number(((account.received/account.total)*100).toFixed(1));return <DashboardCard className="p-5"><h2 className="text-lg font-bold">Payment progress</h2><div className="mt-4"><InfoGrid columns="sm:grid-cols-3" items={[["Total",aed(account.total)],["Received",aed(account.received)],["Outstanding",aed(account.outstanding)]]}/></div><div className="mt-5 flex justify-between text-xs"><span>Collection progress</span><strong>{pct}%</strong></div><div className="mt-2"><ProgressBar value={pct}/></div></DashboardCard>}
export function InstallmentTable({rows,onOpen}:{rows:Installment[];onOpen:(row:Installment)=>void}){return <div className="overflow-x-auto"><table className="w-full min-w-[920px] text-left text-xs"><thead className="bg-muted text-muted-foreground"><tr>{["Installment","Milestone","Due date","Amount","Received","Outstanding","Status","Actions"].map(h=><th key={h} className="p-3 font-medium">{h}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-b border-border hover:bg-muted/40"><td className="p-3 font-semibold">{row.name}</td><td className="p-3">{row.milestone}</td><td className="p-3">{row.due}</td><td className="p-3">{aed(row.amount)}</td><td className="p-3">{aed(row.received)}</td><td className="p-3">{aed(row.outstanding)}</td><td className="p-3"><PaymentStatusBadge status={row.status}/></td><td className="p-3"><Button variant="ghost" className="h-7 px-2 text-xs" onClick={()=>onOpen(row)}>View</Button><ProformaButton installment={row}/></td></tr>)}</tbody></table></div>}
export function PromiseCard({broken=false}:{broken?:boolean}){return <DashboardCard className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-muted-foreground">Payment promise</p><strong className="mt-2 block text-2xl">AED 98,000</strong><p className="text-xs text-muted-foreground">Due 30 Sep 2026</p></div><StatusBadge tone={broken?"danger":"info"}>{broken?"Broken":"Active"}</StatusBadge></div><div className="mt-4"><InfoGrid columns="grid-cols-2" items={[["Created","24 Sep"],["Owner","Layla Noor"],["Status",broken?"Promise missed by 2 days":"Active"],["Reminder","30 Sep · 8:00 AM"]]}/></div></DashboardCard>}
export function CollectionsTimeline(){return <DashboardCard className="p-5"><h2 className="text-lg font-bold">Payment activity</h2><div className="mt-4"><Timeline items={[{icon:Check,title:"Payment cleared",detail:"PAY-2026-01894 · Finance Team",time:"24 Sep · 4:15 PM"},{icon:FileCheck2,title:"Proof of Payment verified",detail:"Amount and reference matched",time:"24 Sep · 3:40 PM"},{icon:WalletCards,title:"Payment allocated",detail:"Installment 2 · AED 80,000",time:"24 Sep · 3:25 PM"},{icon:Clock,title:"Reminder sent",detail:"Email · Delivered",time:"23 Sep · 9:00 AM"}]}/></div></DashboardCard>}
export function AgingBars(){const bars=[["1–7 days",28],["8–30 days",36],["31–60 days",19],["61–90 days",10],["90+ days",7]];return <div className="space-y-4">{bars.map(([label,value])=><div key={String(label)}><div className="mb-1 flex justify-between text-xs"><span>{label}</span><strong>{value}%</strong></div><ProgressBar value={Number(value)}/></div>)}</div>}
export function LinkedFinanceSummary({account}:{account:PaymentAccount}){return <DashboardCard className="p-5"><h2 className="text-lg font-bold">Linked transaction</h2><div className="mt-4"><InfoGrid columns="grid-cols-1" items={[["Customer",account.customer],["Project / unit",`${account.project} · ${account.unit}`],["SPA",account.spa],["Reservation",account.reservation],["Payment plan",account.plan],["Salesperson",account.salesperson],["Broker",account.broker],["Oqood",`${account.oqood} · Submitted`],["Payment clearance",account.clearance]]}/></div></DashboardCard>}
export function ReceiptTable(){return <SimpleTable headers={["Payment","Amount","Date","POP","Verification","Receipt","Actions"]} rows={[["PAY-2026-01894","AED 80,000","24 Sep 2026","POP-01894.pdf","Verified","RCT-2026-00941","Preview · Download"],["PAY-2026-01902","AED 40,000","28 Sep 2026","POP-01902.pdf","Verified","RCT-2026-00949","Preview · Download"]]} badges={[4]}/>} 
