export const users=[
["Ahmed Malik","ahmed.malik@greenhorizon.ae","Administrator","Management","All projects","Active","Today · 4:20 PM"],
["Omar Khan","omar.khan@greenhorizon.ae","Salesperson","Sales","Horizon Residences · Green Park","Active","Today · 3:45 PM"],
["Layla Noor","layla.noor@greenhorizon.ae","Handover Team","Property Delivery","All projects","Active","Today · 3:10 PM"],
["Nadia Rahman","nadia.rahman@greenhorizon.ae","Customer Care","Customer Care","Horizon Residences","Active","Today · 2:52 PM"],
["Maya Joseph","maya.joseph@greenhorizon.ae","Finance","Finance","Green Park · Creek Vista","Inactive","18 Sep 2026"]
];
export const roles=[["Administrator","12","All modules","Full authority","Active"],["Management","6","Management · Reports · Finance overview","Management approvals","Active"],["Sales Manager","8","Sales · CRM · Inventory","Sales approvals","Active"],["Salesperson","24","Sales · CRM · limited finance status","Within configured limits","Active"],["Finance Executive","6","Finance ERP · Payments","Create and record","Active"],["Finance Manager","3","Finance ERP · Payments · Reports","Verify, allocate and approve","Active"],["Legal","5","SPA · NOC","Legal approvals","Active"],["Customer Care","11","Customer Care · Customers","Escalation within authority","Active"],["Handover Team","7","Handover · Customer Care","Handover approvals","Active"]];
export const permissionGroups=[
{module:"Customers & KYC",actions:[["View","Yes","Yes","Assigned"],["Edit","Yes","Limited","Assigned"],["View sensitive data","Yes","No","No"],["Export","Yes","No","No"]]},
{module:"Sales & Approvals",actions:[["Create","Yes","Yes","Yes"],["Edit","Yes","Yes","Own"],["Approve","Yes","Conditional","No"],["Delete","Limited","No","No"]]},
{module:"Payments & Reports",actions:[["View","Yes","Summary","No"],["Edit","Yes","No","No"],["Approve","Yes","No","No"],["Export","Yes","Conditional","No"]]}
,{module:"Finance ERP",actions:[["View","Yes","Summary","Limited"],["Create AR / AP","Yes","Conditional","No"],["Verify / Allocate","Yes","Conditional","No"],["Approve","Yes","Conditional","No"],["Reveal bank details","Yes","No","No"],["Export","Yes","Conditional","No"]]}
];
export const workflows=[["SPA Approval","SPA","2","Sequential","Active","24 Sep 2026"],["Sales Offer Discount","Sales Offer","3","Conditional","Active","23 Sep 2026"],["Finance Clearance","Payments","2","Role-based","Active","22 Sep 2026"],["Payable Approval","Finance ERP","2","Configurable","Active","24 Sep 2026"],["Receipt Verification","Finance ERP","1","Role-based","Active","24 Sep 2026"],["NOC Approval","Resale / NOC","3","Sequential","Active","20 Sep 2026"],["Handover Completion","Handover","2","Sequential","Active","18 Sep 2026"],["Customer Care Escalation","Customer Care","2","Conditional","Draft","24 Sep 2026"]];
export const workflowSteps=[["1","Legal Review","Legal Manager","Required","SPA generated","Escalate per configured duration","Return · Reject"],["2","Management Approval","Management","Required","Legal approved","Escalate per configured duration","Return · Reject"]];
export const documentTemplates=[["Standard Residential EOI","EOI","v3.2","01 Sep 2026","Active","Legal Team"],["Standard Sales Offer","Sales Offer","v2.4","01 Sep 2026","Active","Ahmed Malik"],["Residential SPA","SPA","v6.1","15 Sep 2026","Active","Legal Team"],["SPA Addendum","SPA","v2.0","15 Sep 2026","Active","Legal Team"],["Handover Notice","Handover","v3.1","01 Sep 2026","Active","Layla Noor"],["Key Handover Document","Handover","v1.4","01 Sep 2026","Active","Layla Noor"],["No Objection Certificate","NOC","v2.2","12 Sep 2026","Active","Legal Team"],["Customer Care Resolution","Customer Care","v1.1","20 Sep 2026","Draft","Nadia Rahman"]];
export const communicationTemplates=[["Payment reminder","Email","Payment due for {{unit}}","Active","Finance"],["Document request","Email","Documents required for {{reference_id}}","Active","Operations"],["SPA signature reminder","WhatsApp","—","Inactive","Legal"],["Handover appointment","SMS","—","Draft","Handover"],["Customer Care update","Email","Update on case {{reference_id}}","Active","Customer Care"]];
export const integrations=[["Finance / ERP","Finance","Connected","24 Sep · 4:30 PM","Healthy"],["Inventory","Property","Connected","24 Sep · 4:28 PM","Healthy"],["E-signature platform","Documents","Pending","—","Configuration required"],["Email","Communication","Connected","24 Sep · 4:25 PM","Healthy"],["SMS","Communication","Not Connected","—","Unavailable"],["WhatsApp / approved platform","Communication","Not Connected","—","Unavailable"],["Oqood / external registration","Registration","Pending","23 Sep · 6:00 PM","Manual submission mode"],["Payment gateway / systems","Payments","Connected","24 Sep · 4:20 PM","Healthy"]];
export const integrationLogs=[["24 Sep · 4:30 PM","Finance / ERP","Payment sync","PAY-2026-01042","Success","1 record confirmed"],["24 Sep · 4:28 PM","Inventory","Availability sync","UNT-HR-A-1204","Success","Status confirmed"],["24 Sep · 3:55 PM","Oqood / external registration","Submission status","OQD-2026-00108","Pending","External confirmation unavailable"],["24 Sep · 2:18 PM","Payment gateway / systems","Receipt lookup","RCT-2026-00941","Failed","Retry available; idempotency key retained"]];
export const auditLogs=[["24 Sep 2026 · 4:10 PM","Ahmed Malik","SPA","SPA-2026-00142","Approved","Management approval completed"],["24 Sep 2026 · 3:44 PM","Layla Noor","Handover","HND-2026-00182","Status changed","Snagging → Rectification Required"],["24 Sep 2026 · 2:18 PM","Nadia Rahman","Customer Care","CC-2026-00842","Assigned","Facilities Team assigned"],["24 Sep 2026 · 1:05 PM","Finance Team","Payments","ACC-2026-00482","Receipt verified","RCT-2026-00941"],["24 Sep 2026 · 11:40 AM","Ahmed Malik","Permissions","USR-OMAR-KHAN","Project access changed","Green Park added"]];
export const documentAccess=[["24 Sep · 3:18 PM","Sarah Ahmed","SPA-2026-00142-v2.pdf","Viewed","SPA-2026-00142"],["24 Sep · 2:48 PM","Sarah Ahmed","Key-Handover-A1204.pdf","Signed","HND-2026-00182"],["24 Sep · 1:22 PM","Nadia Rahman","AC-inspection-photo-01.jpg","Uploaded","CC-2026-00842"],["23 Sep · 4:15 PM","Omar Khan","Reservation-Form-A1204.pdf","Downloaded","RSV-2026-00182"]];
export const configLists=[["Lead sources","8 values","Website · Referral · Campaign","Active records protected"],["Unit statuses","6 values","Available · Reserved · Sold","Core lifecycle protected"],["Case categories","7 values","Enquiry · Complaint · Service Request","Configurable"],["SLA rules","12 rules","By case type and priority","Configurable durations"],["Resale fee types","5 values","Admin · NOC · Assignment","Configurable"],["Handover checklists","4 templates","Residential · Commercial","Versioned"],["Document types","18 values","Identity · Agreement · Payment","In-use values protected"]];
