import { Link,useRouterState } from "@tanstack/react-router";
import { AlertTriangle,Check,ChevronRight,LockKeyhole } from "lucide-react";
import type { ReactNode } from "react";
import { DashboardCard,StatusBadge } from "@/components/ui/crm";
const nav=[
["General","/settings"],["Users","/settings/users"],["Roles & permissions","/settings/roles"],["Workflows & approvals","/settings/workflows"],["Document templates","/settings/templates"],["Communication","/settings/communication"],["Notifications","/settings/notifications"],["Integrations","/settings/integrations"],["Finance accounting policies","/settings/accounting-policies"],["Projects & sales configuration","/settings/configuration"],["Security","/settings/security"],["Audit logs","/settings/audit"]] as const;
export function SettingsNavigation(){const path=useRouterState({select:s=>s.location.pathname});return <DashboardCard className="h-fit overflow-hidden p-2"><nav className="grid gap-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-1">{nav.map(([label,to])=><Link key={to} to={to} activeOptions={{exact:to==="/settings"}} className={`flex min-h-10 items-center rounded-md px-3 text-xs font-medium ${path===to?"bg-success-soft text-primary":"text-muted-foreground hover:bg-muted hover:text-foreground"}`}>{label}<ChevronRight size={14} className="ml-auto"/></Link>)}</nav></DashboardCard>}
export function SettingsLayout({title,description,children,actions}:{title:string;description:string;children:ReactNode;actions?:ReactNode}){return <div className="mx-auto max-w-[1540px] p-4 md:p-6"><header className="flex flex-col gap-3 xl:flex-row xl:items-start xl:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-muted-foreground">SYSTEM ADMINISTRATION</p><h1 className="mt-1">{title}</h1><p className="text-sm text-muted-foreground">{description}</p></div>{actions}</header><div className="mt-5 grid gap-4 xl:grid-cols-[250px_minmax(0,1fr)]"><SettingsNavigation/><div className="min-w-0 space-y-4">{children}</div></div></div>}
export function SettingsSection({title,description,children}:{title:string;description?:string;children:ReactNode}){return <DashboardCard className="p-5"><div><h2 className="text-lg font-bold">{title}</h2>{description&&<p className="text-xs text-muted-foreground">{description}</p>}</div><div className="mt-5">{children}</div></DashboardCard>}
export function ToggleRow({title,description,enabled=true,locked=false}:{title:string;description:string;enabled?:boolean;locked?:boolean}){return <div className="flex items-center gap-4 border-b border-border py-3 last:border-0"><div className="min-w-0 flex-1"><strong className="text-sm">{title}</strong><p className="text-xs text-muted-foreground">{description}</p></div>{locked?<LockKeyhole size={16} className="text-muted-foreground"/>:<button aria-label={`Toggle ${title}`} className={`relative h-6 w-11 rounded-full ${enabled?"bg-primary":"bg-muted"}`}><span className={`absolute top-1 size-4 rounded-full bg-surface transition-all ${enabled?"left-6":"left-1"}`}/></button>}</div>}
export function ConfigWarning(){return <div className="flex gap-2 rounded-md bg-warning-soft p-3 text-xs text-warning"><AlertTriangle size={15}/><span>Custom user permissions override role defaults and require authorized approval.</span></div>}
export function IntegrationStatus({status}:{status:string}){return <StatusBadge tone={status==="Connected"||status==="Success"?"success":status==="Error"||status==="Failed"?"danger":status==="Pending"?"warning":"neutral"}>{status}</StatusBadge>}
export function StepDot({done=false,value}:{done?:boolean;value:string}){return <span className={`grid size-7 shrink-0 place-items-center rounded-full text-xs font-semibold ${done?"bg-success-soft text-success":"bg-muted text-muted-foreground"}`}>{done?<Check size={14}/>:value}</span>}
