import { useState, type ReactNode } from "react";
import { AlertTriangle, FileUp } from "lucide-react";
import { Button, FormField, Input, ModalShell, SelectMenu, StatusBadge, Textarea } from "@/components/ui/crm";
import { ApprovalChain, InfoGrid, PricingSummary } from "@/components/sales/sales-ui";

type OpenProps={open:boolean;onOpenChange:(open:boolean)=>void};
function Actions({close,primary}:{close:()=>void;primary:string}){return <div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={close}>Cancel</Button><Button onClick={close}>{primary}</Button></div>}
export function ApprovalModal({open,onOpenChange,kind="EOI"}:{open:boolean;onOpenChange:(o:boolean)=>void;kind?:"EOI"|"Sales Offer"}){const [decision,setDecision]=useState("Approve");return <ModalShell open={open} onOpenChange={onOpenChange} title={`${kind} approval`}><InfoGrid columns="sm:grid-cols-2" items={kind==="EOI"?[["Customer","Sarah Ahmed"],["Unit","Horizon Residences · A-1204"],["EOI amount","AED 50,000"],["Expiry","30 Sep 2026"]]:[["Customer","Sarah Ahmed"],["Unit","Horizon Residences · A-1204"],["List price","AED 1,250,000"],["Final price","AED 1,225,000"],["Discount","2% · Director approval"],["Plan","Standard 20/40/40"]]}/>{kind==="Sales Offer"&&<div className="mt-4"><PricingSummary/></div>}<div className="mt-4"><FormField label="Decision"><div className="flex gap-2">{["Approve","Return","Reject"].map(x=><Button key={x} variant={decision===x?"primary":"secondary"} className="h-9 flex-1" onClick={()=>setDecision(x)}>{x}</Button>)}</div></FormField></div>{decision!=="Approve"&&<div className="mt-4"><FormField label="Remarks *"><Textarea required placeholder={`Reason to ${decision.toLowerCase()} this ${kind.toLowerCase()}`}/></FormField></div>}<p className="mt-4 text-xs text-muted-foreground">Available only to the required approver role.</p><Actions close={()=>onOpenChange(false)} primary={decision}/></ModalShell>}
export function ShareDocumentModal({open,onOpenChange,kind="EOI"}:OpenProps&{kind?:"EOI"|"Sales Offer"}){return <ModalShell open={open} onOpenChange={onOpenChange} title={`Send ${kind.toLowerCase()} to customer`}><div className="grid gap-4 sm:grid-cols-2"><Read label="Recipient" value="Sarah Ahmed"/><Read label="Email" value="sarah.ahmed@email.com"/><FormField label="Channel"><SelectMenu label="Email" items={["Email","Approved electronic signature platform"]}/></FormField><div className="sm:col-span-2"><FormField label="Subject"><Input defaultValue={kind==="EOI"?"Expression of Interest — Horizon Residences A-1204":"Sales Offer — Horizon Residences A-1204"}/></FormField></div><div className="sm:col-span-2"><FormField label="Optional message"><Textarea maxLength={500}/></FormField></div></div><div className="mt-4 flex items-center gap-2 rounded-md bg-muted p-3 text-xs"><FileUp size={15}/>{kind==="EOI"?"EOI-2026-00184.pdf":"Sales-Offer-SO-2026-00482-v2.pdf"}<StatusBadge tone="success" className="ml-auto">Attached</StatusBadge></div><Actions close={()=>onOpenChange(false)} primary={`Send ${kind}`}/></ModalShell>}
export function RecordPaymentModal({open,onOpenChange}:OpenProps){return <ModalShell open={open} onOpenChange={onOpenChange} title="Record EOI payment"><div className="grid gap-4 sm:grid-cols-2"><FormField label="Amount *"><Input required type="number" defaultValue="50000"/></FormField><FormField label="Payment date *"><Input required type="date" defaultValue="2026-09-24"/></FormField><FormField label="Payment method *"><SelectMenu label="Bank transfer" items={["Bank transfer","Card","Cheque","Other"]}/></FormField><FormField label="Reference number"><Input defaultValue="PAY-2026-01842"/></FormField><label className="sm:col-span-2 flex h-16 items-center justify-center gap-2 rounded-md border border-dashed border-border text-xs"><FileUp size={15}/>Proof of payment<input className="sr-only" type="file"/></label><div className="sm:col-span-2"><FormField label="Notes"><Textarea maxLength={500}/></FormField></div></div><p className="mt-4 text-xs text-muted-foreground">Partial payments are supported. Outstanding value and status update automatically.</p><Actions close={()=>onOpenChange(false)} primary="Record payment"/></ModalShell>}
export function CancelEoiModal({open,onOpenChange}:OpenProps){return <ModalShell open={open} onOpenChange={onOpenChange} title="Cancel EOI"><div className="flex gap-2 rounded-md bg-warning-soft p-3 text-xs text-warning"><AlertTriangle size={15}/>The EOI remains in history and cannot be deleted.</div><div className="mt-4"><FormField label="Reason *"><SelectMenu label="Select reason" items={["Customer withdrew","Unit changed","Pricing changed","Duplicate EOI","Expired","Management decision","Other"]}/></FormField></div><div className="mt-4"><FormField label="Optional remarks"><Textarea maxLength={500}/></FormField></div><Actions close={()=>onOpenChange(false)} primary="Cancel EOI"/></ModalShell>}
export function ChangeSalesAttributionModal({open,onOpenChange}:OpenProps){return <ModalShell open={open} onOpenChange={onOpenChange} title="Change broker attribution"><InfoGrid columns="sm:grid-cols-2" items={[["Current agency","Elite Properties"],["Current broker","Hassan Ali"],["Source","Inherited from customer"],["Effective since","17 Sep 2026"]]}/><div className="mt-4 grid gap-4 sm:grid-cols-2"><FormField label="New agency"><SelectMenu label="Select agency" items={["Elite Properties","Prime Gate Realty"]}/></FormField><FormField label="New broker"><SelectMenu label="Select broker" items={["Hassan Ali","Ahmed Raza"]}/></FormField><FormField label="Effective date"><Input type="date"/></FormField><div className="sm:col-span-2"><FormField label="Reason *"><Textarea required/></FormField></div></div><div className="mt-4 flex gap-2 rounded-md bg-warning-soft p-3 text-xs text-warning"><AlertTriangle size={15}/>This change affects future commission attribution and creates a permanent audit entry.</div><Actions close={()=>onOpenChange(false)} primary="Update attribution"/></ModalShell>}
export function VersionComparisonModal({open,onOpenChange}:OpenProps){return <ModalShell open={open} onOpenChange={onOpenChange} title="Compare offer versions"><div className="grid gap-4 sm:grid-cols-2"><Version title="Version 1" price="AED 1,237,500" discount="1% · AED 12,500"/><Version title="Version 2 · Current" price="AED 1,225,000" discount="2% · AED 25,000"/></div><div className="mt-4 rounded-md bg-info-soft p-3 text-xs text-info">Payment plan unchanged · Standard 20/40/40</div><Actions close={()=>onOpenChange(false)} primary="Close comparison"/></ModalShell>}
export function ReservationPlaceholderModal({open,onOpenChange}:OpenProps){return <ModalShell open={open} onOpenChange={onOpenChange} title="Ready for reservation"><ApprovalChain offer/><div className="mt-4"><InfoGrid columns="sm:grid-cols-2" items={[["Customer","Sarah Ahmed"],["Project / Unit","Horizon Residences · A-1204"],["Final price","AED 1,225,000"],["Payment plan","Standard 20/40/40"],["Linked EOI","EOI-2026-00184"],["Offer","SO-2026-00482 · Version 2"]]}/></div><div className="mt-4 flex gap-2 rounded-md bg-info-soft p-3 text-xs text-info"><AlertTriangle size={15}/>Reservation workflow will be completed in the future Reservation module.</div><Actions close={()=>onOpenChange(false)} primary="Confirm readiness"/></ModalShell>}
export function CustomerResponseModal({open,onOpenChange}:OpenProps){const [response,setResponse]=useState("Accepted");return <ModalShell open={open} onOpenChange={onOpenChange} title="Record customer response"><div className="flex gap-2">{["Accepted","Rejected"].map(x=><Button className="flex-1" key={x} variant={response===x?"primary":"secondary"} onClick={()=>setResponse(x)}>{x}</Button>)}</div>{response==="Rejected"&&<div className="mt-4"><FormField label="Reason"><SelectMenu label="Select reason" items={["Price","Payment terms","Unit changed","Customer withdrew","Purchased elsewhere","Other"]}/></FormField></div>}<div className="mt-4"><FormField label="Remarks"><Textarea/></FormField></div><Actions close={()=>onOpenChange(false)} primary={`Mark ${response.toLowerCase()}`}/></ModalShell>}
function Read({label,value}:{label:string;value:string}){return <div><span className="text-[11px] text-muted-foreground">{label}</span><strong className="mt-1 block text-sm">{value}</strong></div>}
function Version({title,price,discount}:{title:string;price:string;discount:string}){return <div className="rounded-card border border-border p-4"><strong>{title}</strong><div className="mt-4 space-y-3"><Read label="Final price" value={price}/><Read label="Discount" value={discount}/><Read label="Payment plan" value="Standard 20/40/40"/></div></div>}
export function InlineWarning({children}:{children:ReactNode}){return <div className="flex gap-2 rounded-md bg-warning-soft p-3 text-xs text-warning"><AlertTriangle size={15}/>{children}</div>}