import * as DropdownMenu from "@radix-ui/react-dropdown-menu";
import { Link } from "@tanstack/react-router";
import { ChevronRight, Ellipsis, Filter, Plus, Search } from "lucide-react";
import { useMemo, useState, type ReactNode } from "react";
import { CompactMetrics, toneFor } from "@/components/sales/sales-ui";
import { Button, DashboardCard, IconButton, Pagination, SelectMenu, StatusBadge } from "@/components/ui/crm";
import { CircleDollarSign, Clock, FileCheck2, Send } from "lucide-react";

const eois=[
 {id:"EOI-2026-00184",customer:"Sarah Ahmed",customerId:"CU-2026-00482",project:"Horizon Residences",unit:"A-1204",salesperson:"Omar Khan",broker:"Direct",amount:"AED 50,000",signature:"Signed",payment:"Received",status:"Active",expiry:"30 Sep 2026"},
 {id:"EOI-2026-00183",customer:"Mohammed Al Farsi",customerId:"CU-2026-00481",project:"Green Park",unit:"B-0806",salesperson:"Layla Noor",broker:"Elite Properties",amount:"AED 40,000",signature:"Awaiting customer",payment:"Pending",status:"Awaiting signature",expiry:"27 Sep 2026"},
 {id:"EOI-2026-00179",customer:"Aisha Rahman",customerId:"CU-2026-00466",project:"Horizon Residences",unit:"A-1402",salesperson:"Omar Khan",broker:"Prime Gate Realty",amount:"AED 60,000",signature:"Not sent",payment:"Not recorded",status:"Pending approval",expiry:"02 Oct 2026"},
 {id:"EOI-2026-00172",customer:"Blue Crest Holdings LLC",customerId:"CU-2026-00472",project:"Green Park",unit:"C-1510",salesperson:"Ahmed Malik",broker:"Elite Properties",amount:"AED 75,000",signature:"Signed",payment:"Partially paid",status:"Ready for sales offer",expiry:"04 Oct 2026"},
];
const offers=[
 {id:"SO-2026-00482",customer:"Sarah Ahmed",project:"Horizon Residences",unit:"A-1204",list:"AED 1.25M",discount:"2% · AED 25K",final:"AED 1.225M",plan:"20 / 40 / 40",status:"Awaiting customer",valid:"30 Sep 2026",eoi:"EOI-2026-00184"},
 {id:"SO-2026-00481",customer:"Mohammed Al Farsi",project:"Green Park",unit:"B-0806",list:"AED 980K",discount:"1% · AED 9.8K",final:"AED 970.2K",plan:"30 / 30 / 40",status:"Pending approval",valid:"29 Sep 2026",eoi:"EOI-2026-00183"},
 {id:"SO-2026-00476",customer:"Aisha Rahman",project:"Horizon Residences",unit:"A-1402",list:"AED 1.42M",discount:"0%",final:"AED 1.42M",plan:"20 / 40 / 40",status:"Accepted",valid:"02 Oct 2026",eoi:"EOI-2026-00179"},
 {id:"SO-2026-00461",customer:"Blue Crest Holdings LLC",project:"Green Park",unit:"C-1510",list:"AED 1.86M",discount:"3% · AED 55.8K",final:"AED 1.804M",plan:"Custom",status:"Ready for reservation",valid:"04 Oct 2026",eoi:"EOI-2026-00172"},
];
export function EoiList(){const [q,setQ]=useState("");const [quick,setQuick]=useState("All");const filtered=useMemo(()=>eois.filter(x=>`${Object.values(x).join(" ")}`.toLowerCase().includes(q.toLowerCase())&&(quick==="All"||x.status.includes(quick))),[q,quick]);return <ListFrame metrics={[{label:"Total active",value:"46",detail:"Across 4 active projects",icon:<FileCheck2/>},{label:"Pending approval",value:"8",detail:"Sales Manager review",icon:<Clock/>},{label:"Awaiting signature",value:"12",detail:"Customer action required",icon:<Send/>},{label:"EOI payments received",value:"AED 2.6M",detail:"Current active EOIs",icon:<CircleDollarSign/>}]} q={q} setQ={setQ} placeholder="Search by EOI ID, customer, unit, project or broker" filters={["EOI status","Project","Payment status","Signature status","More filters"]} quick={["All","Draft","Pending approval","Awaiting signature","Payment pending","Active","Expiring soon","Expired","Cancelled","Ready for offer"]} selected={quick} setSelected={setQuick}><DashboardCard className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[1250px] text-left text-xs"><thead className="bg-muted text-muted-foreground"><tr>{["EOI","Customer","Project / Unit","Salesperson","Broker / Agency","EOI amount","Signature","Payment","Status","Expiry","Actions"].map(x=><th key={x} className="p-3 font-medium">{x}</th>)}</tr></thead><tbody>{filtered.map(x=><tr key={x.id} className="border-b border-border hover:bg-muted/40"><td className="p-3"><Link to="/sales/eoi/$eoiId" params={{eoiId:x.id}} className="font-bold text-primary">{x.id}</Link></td><td className="p-3"><strong>{x.customer}</strong><span className="block text-muted-foreground">{x.customerId}</span></td><td className="p-3"><strong>{x.project}</strong><span className="block text-muted-foreground">{x.unit}</span></td><td className="p-3">{x.salesperson}</td><td className="p-3">{x.broker}</td><td className="p-3 font-semibold">{x.amount}</td><td className="p-3"><StatusBadge tone={toneFor(x.signature)}>{x.signature}</StatusBadge></td><td className="p-3"><StatusBadge tone={toneFor(x.payment)}>{x.payment}</StatusBadge></td><td className="p-3"><StatusBadge tone={toneFor(x.status)}>{x.status}</StatusBadge></td><td className="p-3">{x.expiry}</td><td className="p-3"><RowMenu items={actionsForEoi(x.status)}/></td></tr>)}</tbody></table></div>{!filtered.length&&<Empty title="No EOIs found"/>}<Footer count={filtered.length} total="46"/></DashboardCard></ListFrame>}
export function OfferList(){const [q,setQ]=useState("");const [quick,setQuick]=useState("All");const filtered=useMemo(()=>offers.filter(x=>`${Object.values(x).join(" ")}`.toLowerCase().includes(q.toLowerCase())&&(quick==="All"||x.status.includes(quick))),[q,quick]);return <ListFrame metrics={[{label:"Active offers",value:"38",detail:"AED 42.8M active value",icon:<FileCheck2/>},{label:"Pending approval",value:"7",detail:"3 require Sales Director",icon:<Clock/>},{label:"Awaiting customer",value:"14",detail:"Response pending",icon:<Send/>},{label:"Accepted value",value:"AED 18.4M",detail:"11 ready for reservation",icon:<CircleDollarSign/>}]} q={q} setQ={setQ} placeholder="Search offer ID, customer, project, unit or EOI" filters={["Status","Project","Customer","Discount status","More filters"]} quick={["All","Draft","Pending approval","Awaiting customer","Accepted","Rejected","Expired","Ready for reservation"]} selected={quick} setSelected={setQuick}><DashboardCard className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[1120px] text-left text-xs"><thead className="bg-muted text-muted-foreground"><tr>{["Offer","Customer","Project / Unit","List price","Discount","Final price","Payment plan","Status","Valid until","Actions"].map(x=><th key={x} className="p-3 font-medium">{x}</th>)}</tr></thead><tbody>{filtered.map(x=><tr key={x.id} className="border-b border-border hover:bg-muted/40"><td className="p-3"><Link to="/sales/offers/$offerId" params={{offerId:x.id}} className="font-bold text-primary">{x.id}</Link><span className="block text-muted-foreground">{x.eoi}</span></td><td className="p-3 font-semibold">{x.customer}</td><td className="p-3"><strong>{x.project}</strong><span className="block text-muted-foreground">{x.unit}</span></td><td className="p-3">{x.list}</td><td className="p-3">{x.discount}</td><td className="p-3 font-semibold">{x.final}</td><td className="p-3">{x.plan}</td><td className="p-3"><StatusBadge tone={toneFor(x.status)}>{x.status}</StatusBadge></td><td className="p-3">{x.valid}</td><td className="p-3"><RowMenu items={actionsForOffer(x.status)}/></td></tr>)}</tbody></table></div>{!filtered.length&&<Empty title="No sales offers found"/>}<Footer count={filtered.length} total="38"/></DashboardCard></ListFrame>}
function ListFrame({metrics,q,setQ,placeholder,filters,quick,selected,setSelected,children}:{metrics:{label:string;value:string;detail:string;icon:ReactNode}[];q:string;setQ:(x:string)=>void;placeholder:string;filters:string[];quick:string[];selected:string;setSelected:(x:string)=>void;children:ReactNode}){return <div className="mt-5 space-y-3"><CompactMetrics items={metrics}/><DashboardCard className="p-4"><div className="flex flex-wrap gap-2"><label className="relative min-w-[260px] flex-1"><Search size={16} className="absolute left-3 top-3.5 text-muted-foreground"/><input value={q} onChange={e=>setQ(e.target.value)} className="h-11 w-full rounded-[10px] border border-border bg-surface pl-9 pr-3 text-sm outline-none focus:border-primary" placeholder={placeholder}/></label>{filters.slice(0,4).map(x=><SelectMenu key={x} label={x} items={[`All ${x.toLowerCase()}`,"Active","Pending","Expired"]}/>) }<Button variant="secondary"><Filter size={15}/>{filters[4]}</Button></div></DashboardCard><div className="flex gap-1 overflow-x-auto">{quick.map(x=><Button key={x} variant="ghost" className={`h-9 shrink-0 text-xs ${selected===x?"bg-primary text-primary-foreground hover:bg-primary/90":""}`} onClick={()=>setSelected(x)}>{x}</Button>)}</div>{children}</div>}
function RowMenu({items}:{items:string[]}){return <DropdownMenu.Root><DropdownMenu.Trigger asChild><IconButton label="Open actions"><Ellipsis size={16}/></IconButton></DropdownMenu.Trigger><DropdownMenu.Portal><DropdownMenu.Content align="end" className="z-50 min-w-48 rounded-md border border-border bg-surface p-1 shadow-menu">{items.map(x=><DropdownMenu.Item key={x} className="cursor-pointer rounded px-3 py-2 text-xs outline-none hover:bg-muted">{x}</DropdownMenu.Item>)}</DropdownMenu.Content></DropdownMenu.Portal></DropdownMenu.Root>}
function actionsForEoi(status:string){return status.includes("Pending")?["View EOI","Edit","View document","View history","Cancel EOI"]:status.includes("Awaiting")?["View EOI","Resend","View document","Record payment","View history","Cancel EOI"]:["View EOI","View document","Download","Record payment","Create sales offer","View history","Cancel EOI"]}
function actionsForOffer(status:string){return status.includes("Pending")?["View offer","Edit","View document","View history"]:status.includes("Accepted")||status.includes("Ready")?["View offer","Download","Convert to reservation","View history"]:["View offer","Send to customer","Download","Create revised offer","View history"]}
function Footer({count,total}:{count:number;total:string}){return <div className="flex items-center gap-3 px-4 py-3 text-xs text-muted-foreground"><span>Showing {count} of {total}</span><span className="ml-auto">Rows per page: <strong className="text-foreground">20</strong></span><Pagination/></div>}
function Empty({title}:{title:string}){return <div className="grid min-h-44 place-items-center text-center"><div><Search className="mx-auto text-muted-foreground"/><strong className="mt-2 block">{title}</strong><p className="text-xs text-muted-foreground">Try changing your search or filters.</p></div></div>}