import { Link, useRouterState } from "@tanstack/react-router";
import { AlertTriangle, Check, Clock, FileCheck2, type LucideIcon } from "lucide-react";
import type { ReactNode } from "react";
import { CompactMetrics, InfoGrid, SimpleTable, Timeline, toneFor } from "@/components/brokers/broker-ui";
import { Button, DashboardCard, StatusBadge } from "@/components/ui/crm";

export { CompactMetrics, InfoGrid, SimpleTable, Timeline, toneFor };

const salesLinks=[
  {label:"Pipeline",to:"/sales" as const},
  {label:"EOI",to:"/sales/eoi" as const},
  {label:"Sales offers",to:"/sales/offers" as const},
  {label:"KYC",to:"/sales/kyc" as const},
  {label:"Reservations",to:"/sales/reservations" as const},
  {label:"SPA",to:"/sales/spa" as const},
];
export function SalesNavigation(){const path=useRouterState({select:s=>s.location.pathname});return <div className="mt-5 flex gap-6 overflow-x-auto border-b border-border"><div className="contents">{salesLinks.map(item=><Link key={item.label} to={item.to} activeOptions={{exact:item.to==="/sales"}} className={`-mb-px shrink-0 border-b-2 pb-2 text-xs font-medium ${path===item.to||path.startsWith(`${item.to}/`)?"border-primary text-primary":"border-transparent text-muted-foreground"}`}>{item.label}</Link>)}</div></div>}

export function PipelineSteps(){const stages=[["EOI Draft",8],["EOI Approval",12],["EOI Signed",26],["Sales Offer",38],["Offer Accepted",14],["Ready for Reservation",11]] as const;return <div className="overflow-x-auto"><div className="flex min-w-[850px] items-center py-4">{stages.map(([label,count],i)=><div key={label} className="contents"><div className="min-w-28 flex-1 rounded-card border border-border bg-surface p-4 text-center"><span className="text-[11px] text-muted-foreground">{label}</span><strong className="mt-1 block text-2xl">{count}</strong></div>{i<stages.length-1&&<span className="mx-2 text-muted-foreground">→</span>}</div>)}</div></div>}

export function DocumentPreview({kind="EOI"}:{kind?:"EOI"|"Sales Offer"}){const offer=kind==="Sales Offer";return <DashboardCard className="overflow-hidden"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-md bg-success-soft text-success"><FileCheck2 size={17}/></span><div><h2 className="font-bold">{kind} document preview</h2><p className="text-[11px] text-muted-foreground">{offer?"Standard Sales Offer · v2.4":"Standard Residential EOI · v3.2"}</p></div></div><StatusBadge tone="neutral">Preview</StatusBadge></div><div className="mx-auto my-6 min-h-[520px] max-w-[720px] border border-border bg-surface p-6 md:p-10"><p className="text-center text-[10px] font-semibold uppercase text-muted-foreground">Green Horizon Developments</p><h3 className="mt-2 text-center text-xl font-bold">{offer?"SALES OFFER":"EXPRESSION OF INTEREST"}</h3><p className="mt-1 text-center text-xs text-muted-foreground">{offer?"SO-2026-00482 · Version 2":"EOI-2026-00184"}</p><div className="mt-8"><InfoGrid columns="sm:grid-cols-2" items={offer?[["Customer","Sarah Ahmed · CU-2026-00482"],["Unit","Horizon Residences · A-1204"],["List price","AED 1,250,000"],["Discount","2% · AED 25,000"],["Final price","AED 1,225,000"],["Payment plan","Standard 20/40/40"],["Valid until","30 Sep 2026"],["Broker","Direct"]]:[["Customer","Sarah Ahmed · CU-2026-00482"],["Joint purchaser","Omar Ahmed"],["Project / Unit","Horizon Residences · A-1204"],["Property type","2 Bedroom Apartment"],["EOI amount","AED 50,000"],["Salesperson","Omar Khan"],["Issue / expiry","24–30 Sep 2026"],["Broker","Direct"]]}/></div><div className="mt-8 border-t border-border pt-5 text-xs leading-6 text-muted-foreground">This preview is populated from linked CRM records. Customer, property, pricing, attribution and validity data remain synchronized with the approved record.</div><div className="mt-20 grid gap-8 border-t border-border pt-6 sm:grid-cols-2"><div className="border-b border-border pb-2 text-xs">Customer signature</div><div className="border-b border-border pb-2 text-xs">Authorized signatory</div></div></div></DashboardCard>}

export function ApprovalChain({offer=false}:{offer?:boolean}){const steps:string[][]=offer?[["Sales Manager","Approved","Ahmed Malik · 24 Sep, 10:40 AM"],["Sales Director","Pending","Awaiting action"],["Management","Not required","Within approved pricing band"]]:[["Sales Manager","Approved","Ahmed Malik · 24 Sep, 11:02 AM"]];return <div className="divide-y divide-border rounded-card border border-border">{steps.map(([role="",status="",detail=""],i)=><div key={role} className="flex items-center gap-3 p-4"><span className={`grid size-7 place-items-center rounded-full ${status==="Approved"?"bg-success-soft text-success":"bg-muted text-muted-foreground"}`}>{status==="Approved"?<Check size={14}/>:i+1}</span><div className="flex-1"><strong className="text-sm">{role}</strong><p className="text-[11px] text-muted-foreground">{detail}</p></div><StatusBadge tone={toneFor(status)}>{status}</StatusBadge></div>)}</div>}

export function PricingSummary({discount=2}:{discount?:number}){const value=1250000*discount/100;const final=1250000-value;return <DashboardCard className="p-5"><h2 className="text-lg font-bold">Discount calculation</h2><div className="mt-5 grid items-center gap-4 sm:grid-cols-[1fr_auto_1fr_auto_1fr]"><Calc label="List price" value="AED 1,250,000"/><strong className="text-muted-foreground">−</strong><Calc label="Discount" value={`${discount}% · AED ${value.toLocaleString()}`}/><strong className="text-muted-foreground">=</strong><Calc label="Final selling price" value={`AED ${final.toLocaleString()}`} emphasis/></div><div className="mt-4 flex items-center gap-2 rounded-md bg-warning-soft p-3 text-xs text-warning"><AlertTriangle size={15}/>Salesperson authority is 1%. Sales Director approval is required.</div></DashboardCard>}
function Calc({label,value,emphasis}:{label:string;value:string;emphasis?:boolean}){return <div className={emphasis?"rounded-md bg-success-soft p-3":""}><span className="text-[11px] text-muted-foreground">{label}</span><strong className={`block ${emphasis?"text-xl text-success":"text-lg"}`}>{value}</strong></div>}

export function PaymentPlanPreview(){return <DashboardCard className="overflow-hidden"><div className="p-4"><h2 className="text-lg font-bold">Payment plan preview</h2><p className="text-xs text-muted-foreground">Standard 20/40/40 · Final price AED 1,225,000</p></div><SimpleTable headers={["Installment","Percentage","Amount","Due trigger"]} rows={[["Booking","10%","AED 122,500","Reservation"],["Construction milestone 1","20%","AED 245,000","30% construction"],["Construction milestone 2","20%","AED 245,000","60% construction"],["Handover","50%","AED 612,500","Handover notice"]]}/></DashboardCard>}

export function VersionHistory({onCompare}:{onCompare:()=>void}){return <DashboardCard className="p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-bold">Offer versions</h2><p className="text-xs text-muted-foreground">Material revisions create immutable versions.</p></div><Button variant="secondary" className="h-9" onClick={onCompare}>Compare versions</Button></div><div className="mt-4 space-y-3">{[["Version 2","Current · 24 Sep 2026, 2:30 PM","Discount changed 1% → 2%"],["Version 1","24 Sep 2026, 10:15 AM","Initial offer generated"]].map(([v,time,detail],i)=><div key={v} className="flex gap-3 rounded-md border border-border p-3"><span className="grid size-8 place-items-center rounded-full bg-muted text-xs font-bold">{i===0?<Check size={14}/>:"1"}</span><div><strong className="text-sm">{v}</strong><p className="text-[11px] text-muted-foreground">{time}</p><p className="mt-1 text-xs">{detail}</p></div></div>)}</div></DashboardCard>}

export function ResponseTimeline({signed=false}:{signed?:boolean}){const items:{icon:LucideIcon;title:string;detail:string;time:string}[]=signed?[{icon:Check,title:"Signed",detail:"Sarah Ahmed · electronic signature",time:"24 Sep · 12:12 PM"},{icon:Clock,title:"Viewed",detail:"Customer opened document",time:"24 Sep · 12:04 PM"},{icon:FileCheck2,title:"Sent and delivered",detail:"sarah.ahmed@email.com",time:"24 Sep · 11:20 AM"}]:[{icon:Check,title:"Accepted",detail:"Sarah Ahmed · Version 2",time:"24 Sep · 4:06 PM"},{icon:Clock,title:"Viewed",detail:"Customer opened offer",time:"24 Sep · 3:48 PM"},{icon:FileCheck2,title:"Sent and delivered",detail:"Sales Offer PDF by email",time:"24 Sep · 3:15 PM"}];return <Timeline items={items}/>} 

export function Reminder({children,tone="warning"}:{children:ReactNode;tone?:"warning"|"info"}){return <div className={`flex items-center gap-2 rounded-md p-3 text-xs ${tone==="warning"?"bg-warning-soft text-warning":"bg-info-soft text-info"}`}><AlertTriangle size={14}/>{children}</div>}