import { AlertTriangle, Check, Clock, FileCheck2, PauseCircle, Send } from "lucide-react";
import { CompactMetrics, InfoGrid, SimpleTable, Timeline } from "@/components/sales/sales-ui";
import { Button, DashboardCard, StatusBadge } from "@/components/ui/crm";
import { registrationChecklist, type RegistrationRecord, type RegistrationStatus } from "./registration-data";
export function OqoodStatusBadge({status}:{status:RegistrationStatus}){const tone=status==="Approved / Registered"?"success":status==="On Hold"?"danger":status==="Documents Pending"?"warning":status==="Submitted"||status==="Initiated"?"info":"neutral";return <StatusBadge tone={tone}>{status}</StatusBadge>}
export function RegistrationSummary({record:r}:{record:RegistrationRecord}){return <CompactMetrics items={[{label:"Registration status",value:r.status,detail:r.updated,icon:<FileCheck2/>},{label:"Linked SPA",value:r.spa,detail:"Executed · 24 Sep 2026",icon:<Check/>},{label:"Documents",value:r.documents,detail:"Shared linked records",icon:<FileCheck2/>},{label:"Submission",value:r.submitted,detail:"Registration Team",icon:<Send/>},{label:"Owner",value:r.owner,detail:"Assigned case owner",icon:<Clock/>}]}/>}
export function RegistrationChecklist(){return <DashboardCard className="overflow-hidden"><div className="p-4"><h2 className="text-lg font-bold">Registration document checklist</h2><p className="text-xs text-muted-foreground">Configurable categories linked from Customer, KYC, Reservation, SPA and Unit records.</p></div><SimpleTable headers={["Category","Requirement","Upload","Status","Source"]} rows={registrationChecklist} badges={[2,3]}/></DashboardCard>}
export function RegistrationPrecheck({blocked=false}:{blocked?:boolean}){const rows=[["SPA",blocked?"Not executed":"Executed · SPA-2026-00142"],["Customer","Complete · Sarah Ahmed"],["Unit",blocked?"State requires review":"Sold · correct transaction"],["Required documents",blocked?"2 categories pending":"Complete and verified"]];return <DashboardCard className="p-5"><h2 className="text-lg font-bold">Registration prerequisites</h2><div className="mt-4 grid gap-2 sm:grid-cols-2">{rows.map(([label,value])=>{const bad=value?.includes("Not")||value?.includes("review")||value?.includes("pending");return <div key={label} className={`flex gap-2 rounded-md p-3 text-xs ${bad?"bg-danger-soft text-danger":"bg-success-soft text-success"}`}>{bad?<AlertTriangle size={14}/>:<Check size={14}/>}<span><strong>{label}:</strong> {value}</span></div>})}</div>{blocked&&<p className="mt-3 text-xs font-semibold text-danger">Registration cannot be initiated until all prerequisites are complete.</p>}</DashboardCard>}
export function OnHoldAlert({onResolve}:{onResolve:()=>void}){return <DashboardCard className="border-danger/20 p-5"><div className="flex items-start gap-3"><span className="grid size-9 place-items-center rounded-md bg-danger-soft text-danger"><PauseCircle size={18}/></span><div><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-danger">Registration on hold</p><h2 className="mt-1 text-lg font-bold">Document clarification required</h2></div></div><div className="mt-4"><InfoGrid columns="sm:grid-cols-3" items={[["Since","26 Sep 2026"],["Owner","Registration Team"],["Next action","Upload corrected document"]]}/></div><Button className="mt-4" onClick={onResolve}>Resolve issue</Button></DashboardCard>}
export function RegistrationTimeline({withHold=true}:{withHold?:boolean}){return <DashboardCard className="p-5"><h2 className="text-lg font-bold">Registration timeline</h2><div className="mt-4"><Timeline items={[{icon:Check,title:"Submitted",detail:"External reference pending",time:"25 Sep · 11:40 AM"},...(withHold?[{icon:PauseCircle,title:"On Hold · exception",detail:"Document clarification required · later resolved",time:"25 Sep · 10:55 AM"}]:[]),{icon:Check,title:"Initiated",detail:"Registration Team",time:"25 Sep · 9:10 AM"},{icon:FileCheck2,title:"Documents completed",detail:"Required categories verified",time:"25 Sep · 8:45 AM"},{icon:Clock,title:"Not Initiated",detail:"Created from executed SPA",time:"24 Sep · 4:30 PM"}]}/></div></DashboardCard>}