export type RegistrationStatus="Not Initiated"|"Documents Pending"|"Initiated"|"Submitted"|"On Hold"|"Approved / Registered";
export type RegistrationRecord={id:string;customer:string;customerId:string;project:string;unit:string;unitId:string;spa:string;status:RegistrationStatus;documents:string;submitted:string;updated:string;owner:string;pendingReason:string;price:number;broker:string;salesperson:string};
export const registrations:RegistrationRecord[]=[
 {id:"OQD-2026-00108",customer:"Sarah Ahmed",customerId:"CU-2026-00482",project:"Horizon Residences",unit:"A-1204",unitId:"UNT-HR-A-1204",spa:"SPA-2026-00142",status:"Submitted",documents:"Complete",submitted:"25 Sep 2026",updated:"Today",owner:"Registration Team",pendingReason:"—",price:1225000,broker:"Direct",salesperson:"Omar Khan"},
 {id:"OQD-2026-00107",customer:"Mohammed Al Farsi",customerId:"CU-2026-00465",project:"Green Park",unit:"B-0806",unitId:"UNT-GP-B-0806",spa:"SPA-2026-00141",status:"Documents Pending",documents:"2 missing",submitted:"—",updated:"Yesterday",owner:"Nadia Rahman",pendingReason:"Customer documents",price:980000,broker:"Hassan Ali · Elite Properties",salesperson:"Omar Khan"},
 {id:"OQD-2026-00102",customer:"Aisha Rahman",customerId:"CU-2026-00479",project:"Horizon Residences",unit:"A-1402",unitId:"UNT-HR-A-1402",spa:"SPA-2026-00139",status:"On Hold",documents:"Pending review",submitted:"22 Sep 2026",updated:"3 days ago",owner:"Registration Team",pendingReason:"Document clarification required",price:1420000,broker:"Direct",salesperson:"Layla Noor"},
 {id:"OQD-2026-00096",customer:"Blue Crest Holdings LLC",customerId:"CU-2026-00472",project:"Green Park",unit:"B-0806",unitId:"UNT-GP-B-0806",spa:"SPA-2026-00130",status:"Approved / Registered",documents:"Complete",submitted:"18 Sep 2026",updated:"23 Sep 2026",owner:"Registration Team",pendingReason:"—",price:980000,broker:"Daniel Thomas · Prime Gate Realty",salesperson:"Ahmed Malik"},
];
export const registrationChecklist=[["Customer documents","Required","Uploaded","Verified","Linked from KYC"],["Signed SPA","Required","Uploaded","Verified","SPA-2026-00142-Signed.pdf"],["Unit / transaction documents","Required","Uploaded","Verified","Linked from Unit 360"],["Payment / finance documents","Configurable","Uploaded","Pending Review","Linked receipt"],["Other required registration documents","Configurable","Missing","Missing","Request if applicable"]];
export const registrationAudit=[["25 Sep · 11:40 AM","Registration Team","Status change","Initiated","Submitted","External submission completed"],["25 Sep · 10:30 AM","Nadia Rahman","Documents verified","Pending Review","Verified","Required set complete"],["25 Sep · 9:10 AM","Nadia Rahman","Registration initiated","Not Initiated","Initiated","Assigned to Registration Team"],["24 Sep · 4:30 PM","System","Case created","—","Not Initiated","Created from executed SPA"]];
export const reminders=[["OQD-2026-00107","Documents pending","2 required categories pending","Nadia Rahman","View case"],["OQD-2026-00102","On Hold","Unresolved for 3 days","Registration Manager","Escalated"],["OQD-2026-00111","Not Initiated","Executed SPA awaiting initiation","Registration Team","View case"]];