import { useState, type FormEvent } from "react";
import { AlertTriangle, FileUp } from "lucide-react";
import { z } from "zod";
import { InfoGrid } from "@/components/sales/sales-ui";
import { Button, FieldError, FormField, Input, ModalShell, SelectMenu, Textarea } from "@/components/ui/crm";
type Props={open:boolean;onOpenChange:(open:boolean)=>void};
const notes=z.string().trim().min(5,"Add at least 5 characters").max(500);
export function InitiateRegistrationModal({open,onOpenChange}:Props){return <ModalShell open={open} onOpenChange={onOpenChange} title="Initiate registration"><InfoGrid columns="sm:grid-cols-2" items={[["SPA","SPA-2026-00142 · Executed"],["Customer","Sarah Ahmed · Complete"],["Unit","A-1204 · Sold"],["Documents","Required categories complete"],["Assigned officer","Nadia Rahman"],["Next action","Validate and submit"]]}/><div className="mt-4 flex justify-end gap-2"><Button variant="secondary" onClick={()=>onOpenChange(false)}>Cancel</Button><Button onClick={()=>onOpenChange(false)}>Initiate registration</Button></div></ModalShell>}
export function SubmitRegistrationModal({open,onOpenChange}:Props){return <ModalShell open={open} onOpenChange={onOpenChange} title="Submit registration"><div className="rounded-md bg-success-soft p-3 text-xs text-success">All required information and documents are complete.</div><div className="mt-4"><InfoGrid columns="sm:grid-cols-2" items={[["Registration","OQD-2026-00108"],["Customer","Sarah Ahmed"],["Project / unit","Horizon Residences · A-1204"],["SPA","SPA-2026-00142"],["Sale price","AED 1,225,000"],["Documents","Complete"]]}/></div><div className="mt-4"><FormField label="External reference · optional"><Input maxLength={100} placeholder="Add after submission if available"/></FormField></div><div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={()=>onOpenChange(false)}>Back</Button><Button onClick={()=>onOpenChange(false)}>Confirm submission</Button></div></ModalShell>}
export function OnHoldModal({open,onOpenChange}:Props){const [error,setError]=useState("");function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const result=z.object({remarks:notes,date:z.string().min(1),owner:z.string().min(1)}).safeParse(data);if(!result.success){setError("Remarks, date and responsible owner are required");return}onOpenChange(false)}return <ModalShell open={open} onOpenChange={onOpenChange} title="Place registration on hold"><form onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2"><FormField label="Reason *"><SelectMenu label="Document clarification required" items={["Document clarification required","Customer document issue","Transaction information requires review","External registration query","Payment / clearance issue","Other"]}/></FormField><FormField label="Date *"><Input name="date" type="date" defaultValue="2026-09-26"/></FormField><FormField label="Responsible team / owner *"><Input name="owner" defaultValue="Registration Team" maxLength={120}/></FormField><div className="sm:col-span-2"><FormField label="Remarks *"><Textarea name="remarks" maxLength={500}/><FieldError>{error}</FieldError></FormField></div></div><Actions close={()=>onOpenChange(false)} label="Place on hold"/></form></ModalShell>}
export function ResolveHoldModal({open,onOpenChange}:Props){const [error,setError]=useState("");function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const value=String(new FormData(e.currentTarget).get("resolution")??"");if(!notes.safeParse(value).success){setError("Resolution notes are required");return}onOpenChange(false)}return <ModalShell open={open} onOpenChange={onOpenChange} title="Resolve on-hold issue"><form onSubmit={submit}><div className="rounded-md bg-warning-soft p-3 text-xs text-warning"><strong>Issue:</strong> Document clarification required</div><div className="mt-4"><FormField label="Resolution notes *"><Textarea name="resolution" maxLength={500}/><FieldError>{error}</FieldError></FormField></div><label className="mt-4 flex h-16 cursor-pointer items-center justify-center gap-2 rounded-md border border-dashed border-border text-xs"><FileUp size={15}/>Supporting document<input className="sr-only" type="file"/></label><div className="mt-4"><FormField label="New status"><SelectMenu label="Submitted" items={["Documents Pending","Initiated","Submitted"]}/></FormField></div><p className="mt-3 text-xs text-muted-foreground">The previous hold reason remains in history.</p><Actions close={()=>onOpenChange(false)} label="Resolve"/></form></ModalShell>}
export function MarkRegisteredModal({open,onOpenChange}:Props){return <ModalShell open={open} onOpenChange={onOpenChange} title="Mark registered"><div className="grid gap-4 sm:grid-cols-2"><FormField label="Registration date *"><Input type="date" defaultValue="2026-09-27"/></FormField><FormField label="Registration reference *"><Input defaultValue="REG-DXB-2026-18492"/></FormField><label className="sm:col-span-2 flex h-16 cursor-pointer items-center justify-center gap-2 rounded-md border border-dashed border-border text-xs"><FileUp size={15}/>Official registration document · optional<input className="sr-only" type="file"/></label></div><div className="mt-4 flex gap-2 rounded-md bg-info-soft p-3 text-xs text-info"><AlertTriangle size={15}/>No official document structure is assumed; uploaded records remain permission-controlled.</div><div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={()=>onOpenChange(false)}>Cancel</Button><Button onClick={()=>onOpenChange(false)}>Confirm registration</Button></div></ModalShell>}
function Actions({close,label}:{close:()=>void;label:string}){return <div className="mt-5 flex justify-end gap-2"><Button type="button" variant="secondary" onClick={close}>Cancel</Button><Button type="submit">{label}</Button></div>}